<?php
# This file was automatically generated by the MediaWiki 1.23alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Словник";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";
$wgArticlePath = '/$1';

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://slovnik.chitanka.info";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = array(
	"$wgStylePath/common/images/logo/logo_1.png",
	"$wgStylePath/common/images/logo/logo_2.png",
	"$wgStylePath/common/images/logo/logo_3.png",
	"$wgStylePath/common/images/logo/logo_4.png",
	"$wgStylePath/common/images/logo/logo_5.png",
	"$wgStylePath/common/images/logo/logo_6.png",
	"$wgStylePath/common/images/logo/logo_7.png",
	"$wgStylePath/common/images/logo/logo_8.png",
	"$wgStylePath/common/images/logo/logo_9.png",
	"$wgStylePath/common/images/logo/logo_10.png",
);
$wgLogo = $wgLogos[array_rand($wgLogos)];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "slovnik@bulogos.info";
$wgPasswordSender = "slovnik@bulogos.info";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "DATABASE_NAME";
$wgDBuser = "DATABASE_USER";
$wgDBpassword = "DATABASE_PASSWORD";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "bg";

$wgSecretKey = "a3a450efcb63c2a08ce3b11b72544b760a4740111eccdf4d5c75962e4a82f421";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "885088be87741e4f";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://creativecommons.org/licenses/by/3.0/";
$wgRightsText = "Криейтив Комънс Признание";
$wgRightsIcon = "{$wgStylePath}/common/images/cc-by.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

# Set $wgNoFollowLinks to true if you open up your wiki to editing by
# the general public and wish to apply nofollow to external links as a
# deterrent to spammers. Nofollow is not a comprehensive anti-spam solution
# and open wikis will generally require other anti-spam measures; for more
# information, see https://www.mediawiki.org/wiki/Manual:Combating_spam
$wgNoFollowLinks = false;

# End of automatically generated settings.
# Add more configuration options below.

$wgAllowUserJs = true;
$wgAllowUserCss = true;

require_once "$IP/extensions/ParserFunctions/ParserFunctions.php";
$wgPFEnableStringFunctions = true;

require_once "$IP/extensions/InputBox/InputBox.php";

require_once "$IP/extensions/Scribunto/Scribunto.php";
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoUseGeSHi = true;
$wgScribuntoUseCodeEditor = true;

require_once "$IP/extensions/CodeEditor/CodeEditor.php";

require_once "$IP/extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php";
