
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"2",
  
  "macros":[{
      "function":"__e"
    },{
      "function":"__c",
      "vtp_value":"UA-2010376-1"
    },{
      "function":"__gas",
      "vtp_cookieDomain":"auto",
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_enableLinkId":false,
      "vtp_enableEcommerce":false,
      "vtp_trackingId":["macro",1],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false
    },{
      "function":"__c",
      "vtp_value":"GTM-PJT45LV"
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__f",
      "vtp_component":"URL"
    },{
      "function":"__e"
    }],
  "tags":[{
      "function":"__ua",
      "metadata":["map"],
      "setup_tags":["list",["tag",1,0]],
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",2],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "tag_id":5
    },{
      "function":"__opt",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_optimizeContainerId":["macro",3],
      "vtp_gaSettings":["macro",2],
      "tag_id":7
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    }],
  "rules":[
    [["if",0],["add",0]]]
},
"runtime":[]




};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ca;if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={Lf:!0},fa={};try{fa.__proto__=ea;da=fa.Lf;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca,ia=this||self,ja=/^[\w+/_-]+[=]{0,2}$/,ka=null;var ma=function(){},na=function(a){return"function"==typeof a},g=function(a){return"string"==typeof a},oa=function(a){return"number"==typeof a&&!isNaN(a)},pa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},qa=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},sa=function(a,b){if(a&&pa(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},va=function(a,b){if(!oa(a)||
!oa(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},xa=function(a,b){for(var c=new wa,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},ya=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Aa=function(a){return Math.round(Number(a))||0},Ca=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Da=function(a){var b=[];if(pa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Ea=function(a){return a?
a.replace(/^\s+|\s+$/g,""):""},Fa=function(){return(new Date).getTime()},wa=function(){this.prefix="gtm.";this.values={}};wa.prototype.set=function(a,b){this.values[this.prefix+a]=b};wa.prototype.get=function(a){return this.values[this.prefix+a]};
var Ha=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ia=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Ja=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ka=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},La=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Ma=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},Oa=function(a){var b=
[];ya(a,function(c,d){10>c.length&&d&&b.push(c)});return b.join(",")};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Pa=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Qa=function(a){if(null==a)return String(a);var b=Pa.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Sa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ta=function(a){if(!a||"object"!=Qa(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Sa(a,"constructor")&&!Sa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Sa(a,b)},n=function(a,b){var c=b||("array"==Qa(a)?[]:{}),d;for(d in a)if(Sa(a,d)){var e=a[d];"array"==Qa(e)?("array"!=Qa(c[d])&&(c[d]=[]),c[d]=n(e,c[d])):Ta(e)?(Ta(c[d])||(c[d]={}),c[d]=n(e,c[d])):c[d]=e}return c};var qb;
var rb=[],sb=[],tb=[],ub=[],vb=[],wb={},xb,yb,zb,Ab=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},Bb=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=wb[c],e={},f;for(f in a)a.hasOwnProperty(f)&&0===f.indexOf("vtp_")&&(e[void 0!==d?f:f.substr(4)]=a[f]);return void 0!==d?d(e):qb(c,e,b)},Eb=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Cb(a[e],b,c));
return d},Fb=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=wb[b];return c?c.priorityOverride||0:0},Cb=function(a,b,c){if(pa(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Cb(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var h=rb[f];if(!h||b.Zc(h))return;c[f]=!0;try{var k=Eb(h,b,c);k.vtp_gtmEventId=b.id;d=Bb(k,b);zb&&(d=zb.kg(d,k))}catch(x){b.Fe&&b.Fe(x,Number(f)),d=!1}c[f]=
!1;return d;case "map":d={};for(var l=1;l<a.length;l+=2)d[Cb(a[l],b,c)]=Cb(a[l+1],b,c);return d;case "template":d=[];for(var m=!1,p=1;p<a.length;p++){var r=Cb(a[p],b,c);yb&&(m=m||r===yb.Kb);d.push(r)}return yb&&m?yb.ng(d):d.join("");case "escape":d=Cb(a[1],b,c);if(yb&&pa(a[1])&&"macro"===a[1][0]&&yb.Lg(a))return yb.bh(d);d=String(d);for(var t=2;t<a.length;t++)Ua[a[t]]&&(d=Ua[a[t]](d));return d;case "tag":var q=a[1];if(!ub[q])throw Error("Unable to resolve tag reference "+q+".");return d={se:a[2],
index:q};case "zb":var u={arg0:a[2],arg1:a[3],ignore_case:a[5]};u["function"]=a[1];var w=Gb(u,b,c),v=!!a[4];return v||2!==w?v!==(1===w):null;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Gb=function(a,b,c){try{return xb(Eb(a,b,c))}catch(d){JSON.stringify(a)}return 2};var Hb=function(){var a=function(b){return{toString:function(){return b}}};return{Cd:a("convert_case_to"),Dd:a("convert_false_to"),Ed:a("convert_null_to"),Fd:a("convert_true_to"),Gd:a("convert_undefined_to"),Hh:a("debug_mode_metadata"),wa:a("function"),jf:a("instance_name"),pf:a("live_only"),rf:a("malware_disabled"),sf:a("metadata"),Ih:a("original_vendor_template_id"),wf:a("once_per_event"),Md:a("once_per_load"),Ud:a("setup_tags"),Wd:a("tag_id"),Xd:a("teardown_tags")}}();var Ib=null,Lb=function(a){function b(r){for(var t=0;t<r.length;t++)d[r[t]]=!0}var c=[],d=[];Ib=Jb(a);for(var e=0;e<sb.length;e++){var f=sb[e],h=Kb(f);if(h){for(var k=f.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(f.block||[])}else null===h&&b(f.block||[])}for(var m=[],p=0;p<ub.length;p++)c[p]&&!d[p]&&(m[p]=!0);return m},Kb=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Ib(b[c]);if(0===d)return!1;if(2===d)return null}for(var e=a.unless||[],f=0;f<e.length;f++){var h=Ib(e[f]);if(2===h)return null;
if(1===h)return!1}return!0},Jb=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Gb(tb[c],a));return b[c]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var C={ab:"_ee",Lc:"_syn",Kh:"_uei",Ac:"event_callback",Jb:"event_timeout",I:"gtag.config",fa:"allow_ad_personalization_signals",Bc:"restricted_data_processing",Za:"allow_google_signals",ia:"cookie_expires",Ib:"cookie_update",$a:"session_duration",ka:"user_properties",va:"transport_url",N:"ads_data_redaction"};C.Ce=[C.fa,C.Za,C.Ib];C.Ge=[C.ia,C.Jb,C.$a];var E=window,F=document,fc=navigator,gc=F.currentScript&&F.currentScript.src,hc=function(a,b){var c=E[a];E[a]=void 0===c?b:c;return E[a]},ic=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},jc=function(a,b,c){var d=F.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;ic(d,b);c&&(d.onerror=c);var e;if(null===ka)b:{var f=ia.document,h=f.querySelector&&f.querySelector("script[nonce]");
if(h){var k=h.nonce||h.getAttribute("nonce");if(k&&ja.test(k)){ka=k;break b}}ka=""}e=ka;e&&d.setAttribute("nonce",e);var l=F.getElementsByTagName("script")[0]||F.body||F.head;l.parentNode.insertBefore(d,l);return d},kc=function(){if(gc){var a=gc.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},lc=function(a,b){var c=F.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=F.body&&F.body.lastChild||
F.body||F.head;d.parentNode.insertBefore(c,d);ic(c,b);void 0!==a&&(c.src=a);return c},mc=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},nc=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},oc=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},G=function(a){E.setTimeout(a,0)},pc=function(a,b){return a&&
b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},qc=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},rc=function(a){var b=F.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},sc=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var f=a,h=0;f&&h<=c;h++){if(d[String(f.tagName).toLowerCase()])return f;
f=f.parentElement}return null},tc=function(a){fc.sendBeacon&&fc.sendBeacon(a)||mc(a)},uc=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};var vc={},I=function(a,b){vc[a]=vc[a]||[];vc[a][b]=!0},wc=function(a){for(var b=[],c=vc[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};var xc=[];function yc(){var a=hc("google_tag_data",{});a.ics||(a.ics={entries:{},set:zc,update:Ac,addListener:Bc,notifyListeners:Dc,active:!1});return a.ics}
function zc(a,b,c,d,e,f){var h=yc();h.active=!0;if(void 0!=b){var k=h.entries,l=k[a]||{},m=l.region,p=c&&g(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(p===e||(p===d?m!==e:!p&&!m)){var r=!!(f&&0<f&&void 0===l.update),t={region:p,initial:"granted"===b,update:l.update,quiet:r};k[a]=t;r&&E.setTimeout(function(){k[a]===t&&t.quiet&&(t.quiet=!1,Ec(a),Dc(),I("TAGGING",2))},f)}}}
function Ac(a,b){var c=yc();c.active=!0;if(void 0!=b){var d=Fc(a),e=c.entries,f=e[a]=e[a]||{};f.update="granted"===b;var h=Fc(a);f.quiet?(f.quiet=!1,Ec(a)):h!==d&&Ec(a)}}function Bc(a,b){xc.push({me:a,xg:b})}function Ec(a){for(var b=0;b<xc.length;++b){var c=xc[b];pa(c.me)&&-1!==c.me.indexOf(a)&&(c.Ne=!0)}}function Dc(){for(var a=0;a<xc.length;++a){var b=xc[a];if(b.Ne){b.Ne=!1;try{b.xg.call()}catch(c){}}}}
var Fc=function(a){var b=yc().entries[a]||{};return void 0!==b.update?b.update:void 0!==b.initial?b.initial:void 0},Gc=function(a){return!(yc().entries[a]||{}).quiet},Hc=function(){return yc().active},Ic=function(a,b){yc().addListener(a,b)},Jc=function(a,b){function c(){for(var e=0;e<b.length;e++)if(!Gc(b[e]))return!0;return!1}if(c()){var d=!1;Ic(b,function(){d||c()||(d=!0,a())})}else a()},Kc=function(a,b){if(!1===Fc(b)){var c=!1;Ic([b],function(){!c&&Fc(b)&&(a(),c=!0)})}};var Lc=[C.o,C.H],Mc=function(a){var b=a[C.oh];b&&I("GTM",40);var c=a[C.uh];c&&I("GTM",41);for(var d=pa(b)?b:[b],e=0;e<d.length;++e)for(var f=0;f<Lc.length;f++){var h=Lc[f],k=a[Lc[f]],l=d[e];yc().set(h,k,l,"BG","BG-16",c)}},Nc=function(a){for(var b=0;b<Lc.length;b++){var c=Lc[b],d=a[Lc[b]];yc().update(c,d)}yc().notifyListeners()},Oc=function(a){var b=Fc(a);return void 0!=b?b:!0},Pc=function(){for(var a=[],b=0;b<Lc.length;b++){var c=Fc(Lc[b]);a[b]=!0===c?"1":!1===c?"0":"-"}return"G1"+
a.join("")},Qc=function(a){Kc(a,C.o)},Rc=function(a,b){Jc(a,b)};var Tc=function(a){return Sc?F.querySelectorAll(a):null},Uc=function(a,b){if(!Sc)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!F.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},Vc=!1;if(F.querySelectorAll)try{var Wc=F.querySelectorAll(":root");Wc&&1==Wc.length&&Wc[0]==F.documentElement&&(Vc=!0)}catch(a){}var Sc=Vc;var jd={},kd=null,ld=Math.random();jd.s="GTM-KP4CRCM";jd.Ob="5r0";jd.Ld="";var md={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0,__paused:!0,__tg:!0},od="www.googletagmanager.com/gtm.js";
var pd=od,qd=null,rd=null,sd=null,td="//www.googletagmanager.com/a?id="+jd.s+"&cv=2",ud={},vd={},wd=function(){var a=kd.sequence||0;kd.sequence=a+1;return a};
var xd=function(){return"&tc="+ub.filter(function(a){return a}).length},Ad=function(){yd||(yd=E.setTimeout(zd,500))},zd=function(){yd&&(E.clearTimeout(yd),yd=void 0);void 0===Bd||Cd[Bd]&&!Dd&&!Ed||(Fd[Bd]||Gd.Ng()||0>=Hd--?(I("GTM",1),Fd[Bd]=!0):(Gd.jh(),mc(Id()),Cd[Bd]=!0,Jd=Kd=Ed=Dd=""))},Id=function(){var a=Bd;if(void 0===a)return"";var b=wc("GTM"),c=wc("TAGGING");return[Ld,Cd[a]?"":"&es=1",Md[a],b?"&u="+b:"",c?"&ut="+c:"",xd(),Dd,Ed,Kd,Jd,"&z=0"].join("")},Nd=function(){return[td,"&v=3&t=t","&pid="+
va(),"&rv="+jd.Ob].join("")},Od="0.005000">Math.random(),Ld=Nd(),Pd=function(){Ld=Nd()},Cd={},Dd="",Ed="",Jd="",Kd="",Bd=void 0,Md={},Fd={},yd=void 0,Gd=function(a,b){var c=0,d=0;return{Ng:function(){if(c<a)return!1;Fa()-d>=b&&(c=0);return c>=a},jh:function(){Fa()-d>=b&&(c=0);c++;d=Fa()}}}(2,1E3),Hd=1E3,Qd=function(a,b){if(Od&&!Fd[a]&&Bd!==a){zd();Bd=a;Jd=Dd="";var c;c=0===b.indexOf("gtm.")?encodeURIComponent(b):"*";Md[a]="&e="+c+"&eid="+a;Ad()}},Rd=function(a,b,c){if(Od&&!Fd[a]&&
b){a!==Bd&&(zd(),Bd=a);var d,e=String(b[Hb.wa]||"").replace(/_/g,"");0===e.indexOf("cvt")&&(e="cvt");d=e;var f=c+d;Dd=Dd?Dd+"."+f:"&tr="+f;var h=b["function"];if(!h)throw Error("Error: No function name given for function call.");var k=(wb[h]?"1":"2")+d;Jd=Jd?Jd+"."+k:"&ti="+k;Ad();2022<=Id().length&&zd()}},Sd=function(a,b,c){if(Od&&!Fd[a]){a!==Bd&&(zd(),Bd=a);var d=c+b;Ed=Ed?Ed+
"."+d:"&epr="+d;Ad();2022<=Id().length&&zd()}};var Td={},Ud=new wa,Vd={},Wd={},Zd={name:"dataLayer",set:function(a,b){n(Ma(a,b),Vd);Xd()},get:function(a){return Yd(a,2)},reset:function(){Ud=new wa;Vd={};Xd()}},Yd=function(a,b){if(2!=b){var c=Ud.get(a);if(Od){var d=$d(a);c!==d&&I("GTM",5)}return c}return $d(a)},$d=function(a){var b=a.split("."),c=!1,d=void 0;return c?d:ae(b)},ae=function(a){for(var b=Vd,c=0;c<a.length;c++){if(null===b)return!1;if(void 0===b)break;b=b[a[c]]}return b};
var be=function(a,b){Wd.hasOwnProperty(a)||(Ud.set(a,b),n(Ma(a,b),Vd),Xd())},Xd=function(a){ya(Wd,function(b,c){Ud.set(b,c);n(Ma(b,void 0),Vd);n(Ma(b,c),Vd);a&&delete Wd[b]})},ce=function(a,b,c){Td[a]=Td[a]||{};var d=1!==c?$d(b):Ud.get(b);"array"===Qa(d)||"object"===Qa(d)?Td[a][b]=n(d):Td[a][b]=d},de=function(a,b){if(Td[a])return Td[a][b]},ee=function(a,b){Td[a]&&delete Td[a][b]};var he=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var ie=/:[0-9]+$/,je=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(decodeURIComponent(f[0]).replace(/\+/g," ")===b){var h=f.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},me=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=ke(a.protocol)||ke(E.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:E.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||E.location.hostname).replace(ie,"").toLowerCase());return le(a,b,c,d,e)},le=function(a,b,c,d,e){var f,h=ke(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":f=ne(a);break;case "protocol":f=h;break;case "host":f=a.hostname.replace(ie,"").toLowerCase();if(c){var k=/^www\d*\./.exec(f);k&&k[0]&&(f=f.substr(k[0].length))}break;case "port":f=String(Number(a.port)||("http"==h?80:"https"==h?443:""));break;case "path":a.pathname||a.hostname||I("TAGGING",1);
f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=qa(d||[],l[l.length-1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");e&&(f=je(f,e,void 0));break;case "extension":var m=a.pathname.split(".");f=1<m.length?m[m.length-1]:"";f=f.split("/")[0];break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},ke=function(a){return a?a.replace(":","").toLowerCase():""},ne=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");
b=0>c?a.href:a.href.substr(0,c)}return b},oe=function(a){var b=F.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||I("TAGGING",1),c="/"+c);var d=b.hostname.replace(ie,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}},pe=function(a){function b(m){var p=m.split("=")[0];return 0>d.indexOf(p)?m:p+"=0"}function c(m){return m.split("&").map(b).filter(function(p){return void 0!=p}).join("&")}var d="gclid dclid gclaw gcldc gclgp gclha gclgf _gl".split(" "),
e=oe(a),f=a.split(/[?#]/)[0],h=e.search,k=e.hash;"?"===h[0]&&(h=h.substring(1));"#"===k[0]&&(k=k.substring(1));h=c(h);k=c(k);""!==h&&(h="?"+h);""!==k&&(k="#"+k);var l=""+f+h+k;"/"===l[l.length-1]&&(l=l.substring(0,l.length-1));return l};function qe(a,b,c){for(var d=[],e=b.split(";"),f=0;f<e.length;f++){var h=e[f].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d};var re={},se=function(a){return void 0==re[a]?!1:re[a]};var ue=function(a,b,c,d){return te(d)?qe(a,String(b||document.cookie),c):[]},xe=function(a,b,c,d,e){if(te(e)){var f=ve(a,d,e);if(1===f.length)return f[0].id;if(0!==f.length){f=we(f,function(h){return h.Tb},b);if(1===f.length)return f[0].id;f=we(f,function(h){return h.yb},c);return f[0]?f[0].id:void 0}}};function ye(a,b,c,d){var e=document.cookie;document.cookie=a;var f=document.cookie;return e!=f||void 0!=c&&0<=ue(b,f,!1,d).indexOf(c)}
var Ce=function(a,b,c){function d(q,u,w){if(null==w)return delete h[u],q;h[u]=w;return q+"; "+u+"="+w}function e(q,u){if(null==u)return delete h[u],q;h[u]=!0;return q+"; "+u}if(!te(c.Ca))return 2;var f;void 0==b?f=a+"=deleted; expires="+(new Date(0)).toUTCString():(c.encode&&(b=encodeURIComponent(b)),b=ze(b),f=a+"="+b);var h={};f=d(f,"path",c.path);var k;c.expires instanceof Date?k=c.expires.toUTCString():null!=c.expires&&(k=""+c.expires);f=d(f,"expires",k);f=d(f,"max-age",c.Uh);f=d(f,"samesite",
c.Zh);c.$h&&(f=e(f,"secure"));f=e(f,c.flags);var l=c.domain;if("auto"===l){for(var m=Ae(),p=0;p<m.length;++p){var r="none"!==m[p]?m[p]:void 0,t=d(f,"domain",r);if(!Be(r,c.path)&&ye(t,a,b,c.Ca))return 0}return 1}l&&"none"!==l&&(f=d(f,"domain",l));return Be(l,c.path)?1:ye(f,a,b,c.Ca)?0:1},De=function(a,b,c){null==c.path&&(c.path="/");c.domain||(c.domain="auto");return Ce(a,b,c)};
function we(a,b,c){for(var d=[],e=[],f,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===f||l<f?(e=[k],f=l):l===f&&e.push(k)}return 0<d.length?d:e}function ve(a,b,c){for(var d=[],e=ue(a,void 0,void 0,c),f=0;f<e.length;f++){var h=e[f].split("."),k=h.shift();if(!b||-1!==b.indexOf(k)){var l=h.shift();l&&(l=l.split("-"),d.push({id:h.join("."),Tb:1*l[0]||1,yb:1*l[1]||1}))}}return d}
var ze=function(a){a&&1200<a.length&&(a=a.substring(0,1200));return a},Ee=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Fe=/(^|\.)doubleclick\.net$/i,Be=function(a,b){return Fe.test(document.location.hostname)||"/"===b&&Ee.test(a)},Ae=function(){var a=[],b=document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));var e=document.location.hostname;Fe.test(e)||Ee.test(e)||a.push("none");
return a},te=function(a){if(!se("gtag_cs_api")||!a||!Hc())return!0;if(!Gc(a))return!1;var b=Fc(a);return null==b?!0:!!b};var Ge=function(){for(var a=fc.userAgent+(F.cookie||"")+(F.referrer||""),b=a.length,c=E.history.length;0<c;)a+=c--^b++;var d=1,e,f,h;if(a)for(d=0,f=a.length-1;0<=f;f--)h=a.charCodeAt(f),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(Fa()/1E3)].join(".")},Je=function(a,b,c,d,e){var f=He(b);return xe(a,f,Ie(c),d,e)},Ke=function(a,b,c,d){var e=""+He(c),f=Ie(d);1<f&&(e+="-"+f);return[b,e,a].join(".")},He=function(a){if(!a)return 1;
a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},Ie=function(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function Le(a,b,c){var d,e=a.wb;null==e&&(e=7776E3);0!==e&&(d=new Date((b||Fa())+1E3*e));return{path:a.path,domain:a.domain,flags:a.flags,encode:!!c,expires:d}};var Me=["1"],Ne={},Re=function(a){var b=Oe(a.prefix);Ne[b]||Pe(b,a.path,a.domain)||(Qe(b,Ge(),a),Pe(b,a.path,a.domain))};function Qe(a,b,c){var d=Ke(b,"1",c.domain,c.path),e=Le(c);e.Ca="ad_storage";De(a,d,e)}function Pe(a,b,c){var d=Je(a,b,c,Me,"ad_storage");d&&(Ne[a]=d);return d}function Oe(a){return(a||"_gcl")+"_au"};function Se(){for(var a=Te,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function Ue(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}var Te,Ve;function We(a){Te=Te||Ue();Ve=Ve||Se();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,f=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=f>>2,m=(f&3)<<4|h>>4,p=(h&15)<<2|k>>6,r=k&63;e||(r=64,d||(p=64));b.push(Te[l],Te[m],Te[p],Te[r])}return b.join("")}
function Xe(a){function b(l){for(;d<a.length;){var m=a.charAt(d++),p=Ve[m];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Te=Te||Ue();Ve=Ve||Se();for(var c="",d=0;;){var e=b(-1),f=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=h&&(c+=String.fromCharCode(f<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Ye;var bf=function(){var a=Ze,b=$e,c=af(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){nc(F,"mousedown",d);nc(F,"keyup",d);nc(F,"submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},cf=function(a,b,c,d,e){var f={callback:a,domains:b,fragment:2===c,placement:c,forms:d,sameHost:e};af().decorators.push(f)},df=function(a,b,c){for(var d=af().decorators,e={},f=0;f<d.length;++f){var h=
d[f],k;if(k=!c||h.forms)a:{var l=h.domains,m=a,p=!!h.sameHost;if(l&&(p||m!==F.location.hostname))for(var r=0;r<l.length;r++)if(l[r]instanceof RegExp){if(l[r].test(m)){k=!0;break a}}else if(0<=m.indexOf(l[r])||p&&0<=l[r].indexOf(m)){k=!0;break a}k=!1}if(k){var t=h.placement;void 0==t&&(t=h.fragment?2:1);t===b&&Ja(e,h.callback())}}return e},af=function(){var a=hc("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var ef=/(.*?)\*(.*?)\*(.*)/,ff=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,gf=/^(?:www\.|m\.|amp\.)+/,hf=/([^?#]+)(\?[^#]*)?(#.*)?/;function jf(a){return new RegExp("(.*?)(^|&)"+a+"=([^&]*)&?(.*)")}
var lf=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(We(String(d))))}var e=b.join("*");return["1",kf(e),e].join("*")},kf=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=Ye)){for(var e=Array(256),f=0;256>f;f++){for(var h=f,k=0;8>k;k++)h=
h&1?h>>>1^3988292384:h>>>1;e[f]=h}d=e}Ye=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^Ye[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},nf=function(){return function(a){var b=oe(E.location.href),c=b.search.replace("?",""),d=je(c,"_gl",!0)||"";a.query=mf(d)||{};var e=me(b,"fragment").match(jf("_gl"));a.fragment=mf(e&&e[3]||"")||{}}},of=function(a){var b=nf(),c=af();c.data||(c.data={query:{},fragment:{}},b(c.data));var d={},e=c.data;e&&(Ja(d,e.query),a&&Ja(d,e.fragment));return d},mf=
function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var f=ef.exec(d);if(f){c=f;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var m=h[2],p=0;p<b;++p)if(m===kf(k,p)){l=!0;break a}l=!1}if(l){for(var r={},t=k?k.split("*"):[],q=0;q<t.length;q+=2)r[t[q]]=Xe(t[q+1]);return r}}}}catch(u){}};
function pf(a,b,c,d){function e(p){var r=p,t=jf(a).exec(r),q=r;if(t){var u=t[2],w=t[4];q=t[1];w&&(q=q+u+w)}p=q;var v=p.charAt(p.length-1);p&&"&"!==v&&(p+="&");return p+m}d=void 0===d?!1:d;var f=hf.exec(c);if(!f)return"";var h=f[1],k=f[2]||"",l=f[3]||"",m=a+"="+b;d?l="#"+e(l.substring(1)):k="?"+e(k.substring(1));return""+h+k+l}
function qf(a,b){var c="FORM"===(a.tagName||"").toUpperCase(),d=df(b,1,c),e=df(b,2,c),f=df(b,3,c);if(Ka(d)){var h=lf(d);c?rf("_gl",h,a):sf("_gl",h,a,!1)}if(!c&&Ka(e)){var k=lf(e);sf("_gl",k,a,!0)}for(var l in f)if(f.hasOwnProperty(l))a:{var m=l,p=f[l],r=a;if(r.tagName){if("a"===r.tagName.toLowerCase()){sf(m,p,r,void 0);break a}if("form"===r.tagName.toLowerCase()){rf(m,p,r);break a}}"string"==typeof r&&pf(m,p,r,void 0)}}
function sf(a,b,c,d){if(c.href){var e=pf(a,b,c.href,void 0===d?!1:d);he.test(e)&&(c.href=e)}}
function rf(a,b,c){if(c&&c.action){var d=(c.method||"").toLowerCase();if("get"===d){for(var e=c.childNodes||[],f=!1,h=0;h<e.length;h++){var k=e[h];if(k.name===a){k.setAttribute("value",b);f=!0;break}}if(!f){var l=F.createElement("input");l.setAttribute("type","hidden");l.setAttribute("name",a);l.setAttribute("value",b);c.appendChild(l)}}else if("post"===d){var m=pf(a,b,c.action);he.test(m)&&(c.action=m)}}}
var Ze=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var f=e.protocol;"http:"!==f&&"https:"!==f||qf(e,e.hostname)}}catch(h){}},$e=function(a){try{if(a.action){var b=me(oe(a.action),"host");qf(a,b)}}catch(c){}},tf=function(a,b,c,d){bf();cf(a,b,"fragment"===c?2:1,!!d,!1)},uf=function(a,b){bf();cf(a,[le(E.location,"host",!0)],b,!0,!0)},vf=function(){var a=F.location.hostname,b=ff.exec(F.referrer);if(!b)return!1;
var c=b[2],d=b[1],e="";if(c){var f=c.split("/"),h=f[1];e="s"===h?decodeURIComponent(f[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}var k=a.replace(gf,""),l=e.replace(gf,""),m;if(!(m=k===l)){var p="."+l;m=k.substring(k.length-p.length,k.length)===p}return m},wf=function(a,b){return!1===a?!1:a||b||vf()};var xf=/^\w+$/,yf=/^[\w-]+$/,zf=/^~?[\w-]+$/,Af={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp"},Bf=function(){if(!se("gtag_cs_api")||!Hc())return!0;var a=Fc("ad_storage");return null==a?!0:!!a},Cf=function(a,b){Gc("ad_storage")?Bf()?a():Kc(a,"ad_storage"):b?I("TAGGING",3):Jc(function(){Cf(a,!0)},["ad_storage"])},Ff=function(a){var b=[];if(!F.cookie)return b;var c=ue(a,F.cookie,void 0,"ad_storage");if(!c||0==c.length)return b;for(var d=0;d<c.length;d++){var e=Df(c[d]);e&&-1===qa(b,e)&&b.push(e)}return Ef(b)};
function Gf(a){return a&&"string"==typeof a&&a.match(xf)?a:"_gcl"}
var If=function(){var a=oe(E.location.href),b=me(a,"query",!1,void 0,"gclid"),c=me(a,"query",!1,void 0,"gclsrc"),d=me(a,"query",!1,void 0,"dclid");if(!b||!c){var e=a.hash.replace("#","");b=b||je(e,"gclid",void 0);c=c||je(e,"gclsrc",void 0)}return Hf(b,c,d)},Hf=function(a,b,c){var d={},e=function(f,h){d[h]||(d[h]=[]);d[h].push(f)};d.gclid=a;d.gclsrc=b;d.dclid=c;if(void 0!==a&&a.match(yf))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "3p.ds":se("gtm_3pds")&&
e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha");break;case "gp":e(a,"gp")}c&&e(c,"dc");return d},Kf=function(a){var b=If();Cf(function(){return Jf(b,a)})};
function Jf(a,b,c){function d(m,p){var r=Lf(m,e);r&&(De(r,p,f),h=!0)}b=b||{};var e=Gf(b.prefix);c=c||Fa();var f=Le(b,c,!0);f.Ca="ad_storage";var h=!1,k=Math.round(c/1E3),l=function(m){return["GCL",k,m].join(".")};a.aw&&(!0===b.di?d("aw",l("~"+a.aw[0])):d("aw",l(a.aw[0])));a.dc&&d("dc",l(a.dc[0]));a.gf&&d("gf",l(a.gf[0]));a.ha&&d("ha",l(a.ha[0]));a.gp&&d("gp",l(a.gp[0]));return h}
var Nf=function(a,b){var c=of(!0);Cf(function(){for(var d=Gf(b.prefix),e=0;e<a.length;++e){var f=a[e];if(void 0!==Af[f]){var h=Lf(f,d),k=c[h];if(k){var l=Math.min(Mf(k),Fa()),m;b:{for(var p=l,r=ue(h,F.cookie,void 0,"ad_storage"),t=0;t<r.length;++t)if(Mf(r[t])>p){m=!0;break b}m=!1}if(!m){var q=Le(b,l,!0);q.Ca="ad_storage";De(h,k,q)}}}}Jf(Hf(c.gclid,c.gclsrc),b)})},Lf=function(a,b){var c=Af[a];if(void 0!==c)return b+c},Mf=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||
0)};function Df(a){var b=a.split(".");if(3==b.length&&"GCL"==b[0]&&b[1])return b[2]}
var Of=function(a,b,c,d,e){if(pa(b)){var f=Gf(e),h=function(){for(var k={},l=0;l<a.length;++l){var m=Lf(a[l],f);if(m){var p=ue(m,F.cookie,void 0,"ad_storage");p.length&&(k[m]=p.sort()[p.length-1])}}return k};Cf(function(){tf(h,b,c,d)})}},Ef=function(a){return a.filter(function(b){return zf.test(b)})},Pf=function(a,b){for(var c=Gf(b.prefix),d={},e=0;e<a.length;e++)Af[a[e]]&&(d[a[e]]=Af[a[e]]);Cf(function(){ya(d,function(f,h){var k=ue(c+h,F.cookie,void 0,"ad_storage");if(k.length){var l=k[0],m=Mf(l),
p={};p[f]=[Df(l)];Jf(p,b,m)}})})};function Qf(a,b){for(var c=0;c<b.length;++c)if(a[b[c]])return!0;return!1}
var Rf=function(){function a(e,f,h){h&&(e[f]=h)}var b=["aw","dc"];if(Hc()){var c=If();if(Qf(c,b)){var d={};a(d,"gclid",c.gclid);a(d,"dclid",c.dclid);a(d,"gclsrc",c.gclsrc);uf(function(){return d},3);uf(function(){var e={};return e._up="1",e},1)}}},Sf=function(){var a;if(Bf()){for(var b=[],c=F.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({sd:f[1],value:f[2]})}var h={};if(b&&b.length)for(var k=0;k<b.length;k++){var l=b[k].value.split(".");
"1"==l[0]&&3==l.length&&l[1]&&(h[b[k].sd]||(h[b[k].sd]=[]),h[b[k].sd].push({timestamp:l[1],zg:l[2]}))}a=h}else a={};return a};var Tf=/^\d+\.fls\.doubleclick\.net$/;function Uf(a,b){Gc(C.o)?Oc(C.o)?a():Qc(a):b?I("GTM",42):Rc(function(){Uf(a,!0)},[C.o])}function Vf(a){var b=oe(E.location.href),c=me(b,"host",!1);if(c&&c.match(Tf)){var d=me(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Wf(a,b,c){if("aw"==a||"dc"==a){var d=Vf("gcl"+a);if(d)return d.split(".")}var e=Gf(b);if("_gcl"==e){c=void 0===c?!0:c;var f=!Oc(C.o)&&c,h;h=If()[a]||[];if(0<h.length)return f?["0"]:h}var k=Lf(a,e);return k?Ff(k):[]}
var Xf=function(a){var b=Vf("gac");if(b)return!Oc(C.o)&&a?"0":decodeURIComponent(b);var c=Sf(),d=[];ya(c,function(e,f){for(var h=[],k=0;k<f.length;k++)h.push(f[k].zg);h=Ef(h);h.length&&d.push(e+":"+h.join(","))});return d.join(";")},Yf=function(a,b){var c=If().dc||[];Uf(function(){Re(b);var d=Ne[Oe(b.prefix)],e=!1;if(d&&0<c.length){var f=kd.joined_au=kd.joined_au||{},h=b.prefix||"_gcl";if(!f[h])for(var k=0;k<c.length;k++){var l="https://adservice.google.com/ddm/regclk";l=l+"?gclid="+c[k]+"&auiddc="+d;tc(l);e=f[h]=
!0}}null==a&&(a=e);if(a&&d){var m=Oe(b.prefix),p=Ne[m];p&&Qe(m,p,b)}})};var Zf=/[A-Z]+/,$f=/\s/,ag=function(a){if(g(a)&&(a=Ea(a),!$f.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(Zf.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],B:d}}}}},cg=function(a){for(var b={},c=0;c<a.length;++c){var d=ag(a[c]);d&&(b[d.id]=d)}bg(b);var e=[];ya(b,function(f,h){e.push(h)});return e};
function bg(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.B[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var dg=function(){var a=!1;return a};var fg=function(a,b,c,d){return(2===eg()||d||"http:"!=E.location.protocol?a:b)+c},eg=function(){var a=kc(),b;if(1===a)a:{var c=pd;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,f=1,h=F.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===f&&0===l.indexOf(d)&&(f=2)}}b=f}else b=a;return b};
var tg=function(a){return Oc(C.o)?a:a.replace(/&url=([^&#]+)/,function(b,c){var d=pe(decodeURIComponent(c));return"&url="+encodeURIComponent(d)})};var ug=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),vg={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},wg={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},xg="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var zg=function(a){var b=Yd("gtm.whitelist");b&&I("GTM",9);var c=b&&La(Da(b),vg),d=Yd("gtm.blacklist");d||(d=Yd("tagTypeBlacklist"))&&I("GTM",3);d?
I("GTM",8):d=[];yg()&&(d=Da(d),d.push("nonGooglePixels","nonGoogleScripts","sandboxedScripts"));0<=qa(Da(d),"google")&&I("GTM",2);var e=d&&La(Da(d),wg),f={};return function(h){var k=h&&h[Hb.wa];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==f[k])return f[k];var l=vd[k]||[],m=a(k,l);if(b){var p;if(p=m)a:{if(0>qa(c,k))if(l&&0<l.length)for(var r=
0;r<l.length;r++){if(0>qa(c,l[r])){I("GTM",11);p=!1;break a}}else{p=!1;break a}p=!0}m=p}var t=!1;if(d){var q=0<=qa(e,k);if(q)t=q;else{var u=xa(e,l||[]);u&&I("GTM",10);t=u}}var w=!m||t;w||!(0<=qa(l,"sandboxedScripts"))||c&&-1!==qa(c,"sandboxedScripts")||(w=xa(e,xg));return f[k]=w}},yg=function(){return ug.test(E.location&&E.location.hostname)};var Bg={kg:function(a,b){b[Hb.Cd]&&"string"===typeof a&&(a=1==b[Hb.Cd]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(Hb.Ed)&&null===a&&(a=b[Hb.Ed]);b.hasOwnProperty(Hb.Gd)&&void 0===a&&(a=b[Hb.Gd]);b.hasOwnProperty(Hb.Fd)&&!0===a&&(a=b[Hb.Fd]);b.hasOwnProperty(Hb.Dd)&&!1===a&&(a=b[Hb.Dd]);return a}};var Cg={active:!0,isWhitelisted:function(){return!0}},Dg=function(a){var b=kd.zones;!b&&a&&(b=kd.zones=a());return b};var Eg=function(){};var Fg=!1,Gg=0,Hg=[];function Ig(a){if(!Fg){var b=F.createEventObject,c="complete"==F.readyState,d="interactive"==F.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Fg=!0;for(var e=0;e<Hg.length;e++)G(Hg[e])}Hg.push=function(){for(var f=0;f<arguments.length;f++)G(arguments[f]);return 0}}}function Jg(){if(!Fg&&140>Gg){Gg++;try{F.documentElement.doScroll("left"),Ig()}catch(a){E.setTimeout(Jg,50)}}}var Kg=function(a){Fg?a():Hg.push(a)};var Lg={},Mg={},Ng=function(a,b,c,d){if(!Mg[a]||md[b]||"__zone"===b)return-1;var e={};Ta(d)&&(e=n(d,e));e.id=c;e.status="timeout";return Mg[a].tags.push(e)-1},Og=function(a,b,c,d){if(Mg[a]){var e=Mg[a].tags[b];e&&(e.status=c,e.executionTime=d)}};function Pg(a){for(var b=Lg[a]||[],c=0;c<b.length;c++)b[c]();Lg[a]={push:function(d){d(jd.s,Mg[a])}}}
var Sg=function(a,b,c){Mg[a]={tags:[]};na(b)&&Qg(a,b);c&&E.setTimeout(function(){return Pg(a)},Number(c));return Rg(a)},Qg=function(a,b){Lg[a]=Lg[a]||[];Lg[a].push(Ia(function(){return G(function(){b(jd.s,Mg[a])})}))};function Rg(a){var b=0,c=0,d=!1;return{add:function(){c++;return Ia(function(){b++;d&&b>=c&&Pg(a)})},Xf:function(){d=!0;b>=c&&Pg(a)}}};var Tg=function(){function a(d){return!oa(d)||0>d?0:d}if(!kd._li&&E.performance&&E.performance.timing){var b=E.performance.timing.navigationStart,c=oa(Zd.get("gtm.start"))?Zd.get("gtm.start"):0;kd._li={cst:a(c-b),cbt:a(rd-b)}}};var Xg={},Yg=function(){return E.GoogleAnalyticsObject&&E[E.GoogleAnalyticsObject]},Zg=!1;
var $g=function(a){E.GoogleAnalyticsObject||(E.GoogleAnalyticsObject=a||"ga");var b=E.GoogleAnalyticsObject;if(E[b])E.hasOwnProperty(b)||I("GTM",12);else{var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(new Date);E[b]=c}Tg();return E[b]},ah=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Yg();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};
var ch=function(a){},bh=function(){return E.GoogleAnalyticsObject||"ga"};function ih(a,b,c,d){var e=ub[a],f=jh(a,b,c,d);if(!f)return null;var h=Cb(e[Hb.Ud],c,[]);if(h&&h.length){var k=h[0];f=ih(k.index,{D:f,C:1===k.se?b.terminate:f,terminate:b.terminate},c,d)}return f}
function jh(a,b,c,d){function e(){if(f[Hb.rf])k();else{var v=Eb(f,c,[]),x=Ng(c.id,String(f[Hb.wa]),Number(f[Hb.Wd]),v[Hb.sf]),y=!1;v.vtp_gtmOnSuccess=function(){if(!y){y=!0;var z=Fa()-B;Rd(c.id,ub[a],"5");Og(c.id,x,"success",z);h()}};v.vtp_gtmOnFailure=function(){if(!y){y=!0;var z=Fa()-B;Rd(c.id,ub[a],"6");Og(c.id,x,"failure",z);k()}};v.vtp_gtmTagId=f.tag_id;
v.vtp_gtmEventId=c.id;Rd(c.id,f,"1");var A=function(){var z=Fa()-B;Rd(c.id,f,"7");Og(c.id,x,"exception",z);y||(y=!0,k())};var B=Fa();try{Bb(v,c)}catch(z){A(z)}}}var f=ub[a],h=b.D,k=b.C,l=b.terminate;if(c.Zc(f))return null;var m=Cb(f[Hb.Xd],c,[]);if(m&&m.length){var p=m[0],r=ih(p.index,{D:h,C:k,terminate:l},c,d);if(!r)return null;h=r;k=2===p.se?l:r}if(f[Hb.Md]||f[Hb.wf]){var t=f[Hb.Md]?vb:c.sh,q=h,u=k;if(!t[a]){e=Ia(e);var w=kh(a,t,e);h=w.D;k=w.C}return function(){t[a](q,u)}}return e}
function kh(a,b,c){var d=[],e=[];b[a]=lh(d,e,c);return{D:function(){b[a]=mh;for(var f=0;f<d.length;f++)d[f]()},C:function(){b[a]=nh;for(var f=0;f<e.length;f++)e[f]()}}}function lh(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function mh(a){a()}function nh(a,b){b()};var qh=function(a,b){for(var c=[],d=0;d<ub.length;d++)if(a.xb[d]){var e=ub[d];var f=b.add();try{var h=ih(d,{D:f,C:f,terminate:f},a,d);h?c.push({Ve:d,Oe:Fb(e),vg:h}):(oh(d,a),f())}catch(l){f()}}b.Xf();c.sort(ph);for(var k=0;k<c.length;k++)c[k].vg();return 0<c.length};function ph(a,b){var c,d=b.Oe,e=a.Oe;c=d>e?1:d<e?-1:0;var f;if(0!==c)f=c;else{var h=a.Ve,k=b.Ve;f=h>k?1:h<k?-1:0}return f}
function oh(a,b){if(!Od)return;var c=function(d){var e=b.Zc(ub[d])?"3":"4",f=Cb(ub[d][Hb.Ud],b,[]);f&&f.length&&c(f[0].index);Rd(b.id,ub[d],e);var h=Cb(ub[d][Hb.Xd],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var rh=!1,sh=function(a,b,c,d,e){if("gtm.js"==b){if(rh)return!1;rh=!0}Qd(a,b);var f=Sg(a,d,e);ce(a,"event",1);ce(a,"ecommerce",1);ce(a,"gtm");var h={id:a,name:b,Zc:zg(c),xb:[],sh:[],Fe:function(){I("GTM",6)}};h.xb=Lb(h);var k=qh(h,f);"gtm.js"!==b&&"gtm.sync"!==b||ch(jd.s);if(!k)return k;for(var l=0;l<h.xb.length;l++)if(h.xb[l]){var m=ub[l];if(m&&!md[String(m[Hb.wa])])return!0}return!1};function uh(a,b){}function vh(a,b){return wh()?uh(a,b):void 0}
function wh(){var a=!1;return a};var xh=function(){this.eventModel={};this.targetConfig={};this.containerConfig={};this.h={};this.globalConfig={};this.D=function(){};this.C=function(){};this.eventId=void 0},yh=function(a){var b=new xh;b.eventModel=a;return b},zh=function(a,b){a.targetConfig=b;return a},Ah=function(a,b){a.containerConfig=b;return a},Bh=function(a,b){a.h=b;return a},Ch=function(a,b){a.globalConfig=b;return a},Dh=function(a,b){a.D=b;return a},Eh=function(a,b){a.C=b;return a};
xh.prototype.getWithConfig=function(a){if(void 0!==this.eventModel[a])return this.eventModel[a];if(void 0!==this.targetConfig[a])return this.targetConfig[a];if(void 0!==this.containerConfig[a])return this.containerConfig[a];if(void 0!==this.h[a])return this.h[a];if(void 0!==this.globalConfig[a])return this.globalConfig[a]};
var Fh=function(a){function b(e){ya(e,function(f){c[f]=null})}var c={};b(a.eventModel);b(a.targetConfig);b(a.containerConfig);b(a.globalConfig);var d=[];ya(c,function(e){d.push(e)});return d};var Gh;if(3===jd.Ob.length)Gh="g";else{var Hh="G";Gh=Hh}
var Ih={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:Gh,OPT:"o"},Jh=function(a){var b=jd.s.split("-"),c=b[0].toUpperCase(),d=Ih[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",f;if(3===jd.Ob.length){var h="w";f="2"+h}else f="";return f+d+jd.Ob+e};function Kh(){var a=!1;a=Hc();return a}
function Lh(a,b,c){function d(r){var t;kd.reported_gclid||(kd.reported_gclid={});t=kd.reported_gclid;var q=f+(r?"gcu":"gcs");if(!t[q]){t[q]=!0;var u=[],w=function(B,z){z&&u.push(B+"="+encodeURIComponent(z))},v="https://www.google.com";if(Hc()){var x=Oc(C.o);w("gcs",Pc());r&&w("gcu","1");w("rnd",p);if((!f||h&&"aw.ds"!==h)&&Oc(C.o)){var y=Ff("_gcl_aw");w("gclaw",y.join("."))}w("url",String(E.location).split(/[?#]/)[0]);w("dclid",Mh(b,k));!x&&b&&(v="https://pagead2.googlesyndication.com")}
w("gclid",Mh(b,f));w("gclsrc",h);w("gtm",Jh(!c));var A=v+"/pagead/landing?"+u.join("&");tc(A)}}var e=If(),f=e.gclid||"",h=e.gclsrc,k=e.dclid||"",l=!a&&(!f||h&&"aw.ds"!==h?!1:!0),m=Kh();if(l||m){var p=""+Ge();m?Rc(function(){d();Oc(C.o)||Qc(function(){return d(!0)})},[C.o]):d()}}
function Mh(a,b){var c=a&&!Oc(C.o);if(b&&c)return"0";return b}var Pi={},Qi=["G","GP"];Pi.Xe="";var Ri=Pi.Xe.split(",");function Si(){var a=kd;return a.gcq=a.gcq||new Ti}
var Ui=function(a,b,c){Si().register(a,b,c)},Vi=function(a,b,c,d){Si().push("event",[b,a],c,d)},Wi=function(a,b){Si().push("config",[a],b)},Xi={},Yi=function(a){return!0},Zi=function(){this.status=1;this.containerConfig={};this.targetConfig={};this.i={};this.m=null;this.h=!1},$i=function(a,b,c,d,e){this.type=a;this.m=b;this.ba=c||
"";this.h=d;this.i=e},Ti=function(){this.m={};this.i={};this.h=[]},aj=function(a,b){var c=ag(b);return a.m[c.containerId]=a.m[c.containerId]||new Zi},bj=function(a,b,c){if(b){var d=ag(b);if(d&&1===aj(a,b).status&&Yi(d.prefix)){aj(a,b).status=2;var e={};Od&&(e.timeoutId=E.setTimeout(function(){I("GTM",38);Ad()},3E3));a.push("require",[e],d.containerId);Xi[d.containerId]=Fa();if(dg()){}else{var h="/gtag/js?id="+encodeURIComponent(d.containerId)+"&l=dataLayer&cx=c",k=("http:"!=E.location.protocol?"https:":"http:")+("//www.googletagmanager.com"+h),l=vh(c,h)||k;jc(l)}}}},cj=function(a,b,c,d){if(d.ba){var e=aj(a,d.ba),
f=e.m;if(f){var h=n(c),k=n(e.targetConfig[d.ba]),l=n(e.containerConfig),m=n(e.i),p=n(a.i),r=Yd("gtm.uniqueEventId"),t=ag(d.ba).prefix,q=Eh(Dh(Ch(Bh(Ah(zh(yh(h),k),l),m),p),function(){Sd(r,t,"2");}),function(){Sd(r,t,"3");});try{Sd(r,t,"1");f(d.ba,b,d.m,q)}catch(u){
Sd(r,t,"4");}}}};
Ti.prototype.register=function(a,b,c){if(3!==aj(this,a).status){aj(this,a).m=b;aj(this,a).status=3;c&&(aj(this,a).i=c);var d=ag(a),e=Xi[d.containerId];if(void 0!==e){var f=kd[d.containerId].bootstrap,h=d.prefix.toUpperCase();kd[d.containerId]._spx&&(h=h.toLowerCase());var k=Yd("gtm.uniqueEventId"),l=h,m=Fa()-f;if(Od&&!Fd[k]){k!==Bd&&(zd(),Bd=k);var p=l+"."+Math.floor(f-e)+"."+Math.floor(m);Kd=Kd?Kd+","+p:"&cl="+p}delete Xi[d.containerId]}this.flush()}};
Ti.prototype.push=function(a,b,c,d){var e=Math.floor(Fa()/1E3);bj(this,c,b[0][C.va]||this.i[C.va]);this.h.push(new $i(a,e,c,b,d));d||this.flush()};
Ti.prototype.flush=function(a){for(var b=this;this.h.length;){var c=this.h[0];if(c.i)c.i=!1,this.h.push(c);else switch(c.type){case "require":if(3!==aj(this,c.ba).status&&!a)return;Od&&E.clearTimeout(c.h[0].timeoutId);break;case "set":ya(c.h[0],function(l,m){n(Ma(l,m),b.i)});break;case "config":var d=c.h[0],e=!!d[C.jc];delete d[C.jc];var f=aj(this,c.ba),h=ag(c.ba),k=h.containerId===h.id;e||(k?f.containerConfig={}:f.targetConfig[c.ba]={});f.h&&e||cj(this,C.I,d,c);f.h=!0;delete d[C.ab];k?n(d,f.containerConfig):
n(d,f.targetConfig[c.ba]);break;case "event":cj(this,c.h[1],c.h[0],c)}this.h.shift()}};var dj=["HA","GF","GP","G"],ej="G".split(/,/);ej.push("DC");ej.push("UA");ej.push("AW");var fj=!1;
fj=!0;var gj=null,hj={},ij={},jj;function kj(a,b){var c={event:a};b&&(c.eventModel=n(b),b[C.Ac]&&(c.eventCallback=b[C.Ac]),b[C.Jb]&&(c.eventTimeout=b[C.Jb]));return c}
var pj={config:function(a){},event:function(a){var b=a[1];if(g(b)&&!(3<a.length)){var c;if(2<a.length){if(!Ta(a[2])&&void 0!=a[2])return;c=a[2]}var d=kj(b,c);return d}},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},policy:function(){},set:function(a){var b;2==a.length&&Ta(a[1])?b=n(a[1]):3==a.length&&g(a[1])&&(b={},
Ta(a[2])||pa(a[2])?b[a[1]]=n(a[2]):b[a[1]]=a[2]);if(b){b._clear=!0;return b}}};var qj={policy:!0};var rj=function(a,b){var c=a.hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}},tj=function(a){var b=sj(),c=b&&b.hide;c&&c.end&&(c[a]=!0)};var uj=!1,vj=[];function wj(){if(!uj){uj=!0;for(var a=0;a<vj.length;a++)G(vj[a])}}var xj=function(a){uj?G(a):vj.push(a)};var Pj=function(a){if(Oj(a))return a;this.h=a};Pj.prototype.Dg=function(){return this.h};var Oj=function(a){return!a||"object"!==Qa(a)||Ta(a)?!1:"getUntrustedUpdateValue"in a};Pj.prototype.getUntrustedUpdateValue=Pj.prototype.Dg;var Qj=[],Rj=!1,Sj=function(a){return E["dataLayer"].push(a)},Tj=function(a){var b=kd["dataLayer"],c=b?b.subscribers:1,d=0;return function(){++d===c&&a()}};
function Uj(a){var b=a._clear;ya(a,function(f,h){"_clear"!==f&&(b&&be(f,void 0),be(f,h))});qd||(qd=a["gtm.start"]);var c=a.event,d=a["gtm.uniqueEventId"];if(!c)return!1;d||(d=wd(),a["gtm.uniqueEventId"]=d,be("gtm.uniqueEventId",d));sd=c;var e=Vj(a);sd=null;switch(c){case "gtm.init":I("GTM",19),e&&I("GTM",20)}return e}
function Vj(a){var b=a.event,c=a["gtm.uniqueEventId"],d,e=kd.zones;d=e?e.checkState(jd.s,c):Cg;return d.active?sh(c,b,d.isWhitelisted,a.eventCallback,a.eventTimeout)?!0:!1:!1}
function Wj(){for(var a=!1;!Rj&&0<Qj.length;){Rj=!0;delete Vd.eventModel;Xd();var b=Qj.shift();if(null!=b){var c=Oj(b);if(c){var d=b;b=Oj(d)?d.getUntrustedUpdateValue():void 0;for(var e=["gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],f=0;f<e.length;f++){var h=e[f],k=Yd(h,1);if(pa(k)||Ta(k))k=n(k);Wd[h]=k}}try{if(na(b))try{b.call(Zd)}catch(w){}else if(pa(b)){var l=b;if(g(l[0])){var m=
l[0].split("."),p=m.pop(),r=l.slice(1),t=Yd(m.join("."),2);if(void 0!==t&&null!==t)try{t[p].apply(t,r)}catch(w){}}}else{var q=b;if(q&&("[object Arguments]"==Object.prototype.toString.call(q)||Object.prototype.hasOwnProperty.call(q,"callee"))){a:{if(b.length&&g(b[0])){var u=pj[b[0]];if(u&&(!c||!qj[b[0]])){b=u(b);break a}}b=void 0}if(!b){Rj=!1;continue}}a=Uj(b)||a}}finally{c&&Xd(!0)}}Rj=!1}
return!a}function Xj(){var a=Wj();try{rj(E["dataLayer"],jd.s)}catch(b){}return a}
var Zj=function(){var a=hc("dataLayer",[]),b=hc("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};Kg(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});xj(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||0)+1;var c=a.push;a.push=function(){var d;if(0<kd.SANDBOXED_JS_SEMAPHORE){d=[];for(var e=0;e<arguments.length;e++)d[e]=new Pj(arguments[e])}else d=[].slice.call(arguments,0);var f=c.apply(a,d);Qj.push.apply(Qj,d);if(300<
this.length)for(I("GTM",4);300<this.length;)this.shift();var h="boolean"!==typeof f||f;return Wj()&&h};Qj.push.apply(Qj,a.slice(0));Yj()&&G(Xj)},Yj=function(){var a=!0;return a};var ak={};ak.Kb=new String("undefined");
var bk=function(a){this.h=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===ak.Kb?b:a[d]);return c.join("")}};bk.prototype.toString=function(){return this.h("undefined")};bk.prototype.valueOf=bk.prototype.toString;ak.Ff=bk;ak.Kc={};ak.ng=function(a){return new bk(a)};var ck={};ak.kh=function(a,b){var c=wd();ck[c]=[a,b];return c};ak.ne=function(a){var b=a?0:1;return function(c){var d=ck[c];if(d&&"function"===typeof d[b])d[b]();ck[c]=void 0}};ak.Lg=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=
b||8===a[d],c=c||16===a[d];return b&&c};ak.bh=function(a){if(a===ak.Kb)return a;var b=wd();ak.Kc[b]=a;return'google_tag_manager["'+jd.s+'"].macro('+b+")"};ak.Vg=function(a,b,c){a instanceof ak.Ff&&(a=a.h(ak.kh(b,c)),b=ma);return{Xc:a,D:b}};var dk=function(a,b,c){function d(f,h){var k=f[h];return k}var e={event:b,"gtm.element":a,"gtm.elementClasses":d(a,"className"),"gtm.elementId":a["for"]||pc(a,"id")||"","gtm.elementTarget":a.formTarget||d(a,"target")||""};c&&(e["gtm.triggers"]=c.join(","));e["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||d(a,"href")||a.src||a.code||a.codebase||
"";return e},ek=function(a){kd.hasOwnProperty("autoEventsSettings")||(kd.autoEventsSettings={});var b=kd.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},fk=function(a,b,c){ek(a)[b]=c},gk=function(a,b,c,d){var e=ek(a),f=Ha(e,b,d);e[b]=c(f)},hk=function(a,b,c){var d=ek(a);return Ha(d,b,c)};var ik=["input","select","textarea"],jk=["button","hidden","image","reset","submit"],kk=function(a){var b=a.tagName.toLowerCase();return!sa(ik,function(c){return c===b})||"input"===b&&sa(jk,function(c){return c===a.type.toLowerCase()})?!1:!0},lk=function(a){return a.form?a.form.tagName?a.form:F.getElementById(a.form):sc(a,["form"],100)},mk=function(a,b,c){if(!a.elements)return 0;for(var d=b.getAttribute(c),e=0,f=1;e<a.elements.length;e++){var h=a.elements[e];if(kk(h)){if(h.getAttribute(c)===d)return f;
f++}}return 0};var nk=!!E.MutationObserver,ok=void 0,pk=function(a){if(!ok){var b=function(){var c=F.body;if(c)if(nk)(new MutationObserver(function(){for(var e=0;e<ok.length;e++)G(ok[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;nc(c,"DOMNodeInserted",function(){d||(d=!0,G(function(){d=!1;for(var e=0;e<ok.length;e++)G(ok[e])}))})}};ok=[];F.body?b():G(b)}ok.push(a)};var Kk=E.clearTimeout,Lk=E.setTimeout,K=function(a,b,c){if(dg()){b&&G(b)}else return jc(a,b,c)},Mk=function(){return E.location.href},Nk=function(a){return me(oe(a),"fragment")},Ok=function(a){return ne(oe(a))},Q=function(a,b){return Yd(a,b||2)},Pk=function(a,b,c){var d;b?(a.eventCallback=b,c&&(a.eventTimeout=c),d=Sj(a)):d=Sj(a);return d},Qk=function(a,b){E[a]=b},R=function(a,b,c){b&&(void 0===E[a]||c&&!E[a])&&(E[a]=
b);return E[a]},Rk=function(a,b,c){return ue(a,b,void 0===c?!0:!!c)},Sk=function(a,b){if(dg()){b&&G(b)}else lc(a,b)},Tk=function(a){return!!hk(a,"init",!1)},Uk=function(a){fk(a,"init",!0)},Vk=function(a,b){var c=(void 0===b?0:b)?"www.googletagmanager.com/gtag/js":pd;c+="?id="+encodeURIComponent(a)+"&l=dataLayer";K(fg("https://","http://",c))},Wk=function(a,b){var c=a[b];return c};
var Xk=ak.Vg;function tl(a,b){a=String(a);b=String(b);var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var ul=new wa;function vl(a,b){function c(h){var k=oe(h),l=me(k,"protocol"),m=me(k,"host",!0),p=me(k,"port"),r=me(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==p||"https"==l&&"443"==p)l="web",p="default";return[l,m,p,r]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0}
function wl(a){return xl(a)?1:0}
function xl(a){var b=a.arg0,c=a.arg1;if(a.any_of&&pa(c)){for(var d=0;d<c.length;d++)if(wl({"function":a["function"],arg0:b,arg1:c[d]}))return!0;return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var e;a:{if(b){var f=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var h=0;h<f.length;h++)if(b[f[h]]){e=b[f[h]](c);break a}}catch(t){}}e=!1}return e;case "_ew":return tl(b,c);case "_eq":return String(b)==String(c);
case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var k;k=String(b).split(",");return 0<=qa(k,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var l;var m=a.ignore_case?"i":void 0;try{var p=String(c)+m,r=ul.get(p);r||(r=new RegExp(c,m),ul.set(p,r));l=r.test(b)}catch(t){l=!1}return l;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return vl(b,c)}return!1};var yl=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var zl={},Al=encodeURI,V=encodeURIComponent,Bl=mc;var Cl=function(a,b){if(!a)return!1;var c=me(oe(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var Dl=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};zl.Mg=function(){var a=!1;return a};function Vm(){return E.gaGlobal=E.gaGlobal||{}}var Wm=function(){var a=Vm();a.hid=a.hid||va();return a.hid};var gn=window,hn=document,jn=function(a){var b=gn._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===gn["ga-disable-"+a])return!0;try{var c=gn.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(f){}for(var d=qe("AMP_TOKEN",String(hn.cookie),!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return hn.getElementById("__gaOptOutExtension")?!0:!1};function mn(a,b){delete b.eventModel[C.ab];if(a!==C.I){var c=b.getWithConfig(C.bc);if(pa(c)){I("GTM",26);for(var d={},e=0;e<c.length;e++){var f=c[e],h=b.getWithConfig(f);void 0!==h&&(d[f]=h)}b.eventModel=d}}on(b.eventModel)}var on=function(a){ya(a,function(c){"_"===c.charAt(0)&&delete a[c]});var b=a[C.ka]||{};ya(b,function(c){"_"===c.charAt(0)&&delete b[c]})};var rn=function(a,b,c){Vi(b,c,a)},sn=function(a,b,c){Vi(b,c,a,!0)},un=function(a,b){};
function tn(a,b){}var W={a:{}};

W.a.c=["google"],function(){(function(a){W.__c=a;W.__c.b="c";W.__c.g=!0;W.__c.priorityOverride=0})(function(a){return a.vtp_value})}();

W.a.e=["google"],function(){(function(a){W.__e=a;W.__e.b="e";W.__e.g=!0;W.__e.priorityOverride=0})(function(a){return String(de(a.vtp_gtmEventId,"event"))})}();
W.a.f=["google"],function(){(function(a){W.__f=a;W.__f.b="f";W.__f.g=!0;W.__f.priorityOverride=0})(function(a){var b=Q("gtm.referrer",1)||F.referrer;return b?a.vtp_component&&"URL"!=a.vtp_component?me(oe(String(b)),a.vtp_component,a.vtp_stripWww,a.vtp_defaultPages,a.vtp_queryKey):Ok(String(b)):String(b)})}();

W.a.u=["google"],function(){var a=function(b){return{toString:function(){return b}}};(function(b){W.__u=b;W.__u.b="u";W.__u.g=!0;W.__u.priorityOverride=0})(function(b){var c;b.vtp_customUrlSource?c=b.vtp_customUrlSource:c=Q("gtm.url",1);c=c||Mk();var d=b[a("vtp_component")];if(!d||"URL"==d)return Ok(String(c));var e=oe(String(c)),f;if("QUERY"===d)a:{var h=b[a("vtp_multiQueryKeys").toString()],k=b[a("vtp_queryKey").toString()]||"",l=b[a("vtp_ignoreEmptyQueryParam").toString()],m;h?pa(k)?m=k:m=String(k).replace(/\s+/g,
"").split(","):m=[String(k)];for(var p=0;p<m.length;p++){var r=me(e,"QUERY",void 0,void 0,m[p]);if(void 0!=r&&(!l||""!==r)){f=r;break a}}f=void 0}else f=me(e,d,"HOST"==d?b[a("vtp_stripWww")]:void 0,"PATH"==d?b[a("vtp_defaultPages")]:void 0,void 0);return f})}();
W.a.ua=["google"],function(){var a,b={},c=function(e){Rc(function(){d(e)},[C.H,C.o])},d=function(e){var f={},h={},k={},l={},m={};if(e.vtp_gaSettings){var p=e.vtp_gaSettings;n(Dl(p.vtp_fieldsToSet,"fieldName","value"),h);n(Dl(p.vtp_contentGroup,"index","group"),k);n(Dl(p.vtp_dimension,"index","dimension"),l);n(Dl(p.vtp_metric,"index","metric"),m);e.vtp_gaSettings=null;p.vtp_fieldsToSet=void 0;p.vtp_contentGroup=void 0;p.vtp_dimension=void 0;p.vtp_metric=void 0;var r=n(p);e=n(e,r)}n(Dl(e.vtp_fieldsToSet,
"fieldName","value"),h);n(Dl(e.vtp_contentGroup,"index","group"),k);n(Dl(e.vtp_dimension,"index","dimension"),l);n(Dl(e.vtp_metric,"index","metric"),m);Oc(C.H)||(h.storage="none"),Oc(C.o)||(h.allowAdFeatures=!1,h.storeGac=!1);var t=$g(e.vtp_functionName);if(na(t)){var q="",u="";e.vtp_setTrackerName&&"string"==typeof e.vtp_trackerName?""!==e.vtp_trackerName&&(u=e.vtp_trackerName,q=u+"."):(u="gtm"+wd(),
q=u+".");var w={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,cookieFlags:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0,useAmpClientId:!0,storeGac:!0},v={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,storeGac:!0,
allowAdFeatures:!0,allowAdPersonalizationSignals:!0},x=function(O){var P=[].slice.call(arguments,0);P[0]=q+P[0];t.apply(window,P)},y=function(O,P){return void 0===P?P:O(P)},A=function(O,P){if(P)for(var Ba in P)P.hasOwnProperty(Ba)&&x("set",O+Ba,P[Ba])},B=function(){},
z=function(O,P,Ba){var Ra=0;if(O)for(var za in O)if(O.hasOwnProperty(za)&&(Ba&&w[za]||!Ba&&void 0===w[za])){var Na=v[za]?Ca(O[za]):O[za];"anonymizeIp"!=za||Na||(Na=void 0);P[za]=Na;Ra++}return Ra},D={name:u};z(h,D,!0);t("create",e.vtp_trackingId||f.trackingId,D);x("set","&gtm",Jh(!0));Hc()&&x("set","&gcs",Pc());e.vtp_enableRecaptcha&&x("require","recaptcha","recaptcha.js");(function(O,P){void 0!==e[P]&&x("set",O,e[P])})("nonInteraction","vtp_nonInteraction");A("contentGroup",k);A("dimension",l);A("metric",m);var H={};z(h,H,!1)&&x("set",H);var M;
e.vtp_enableLinkId&&x("require","linkid","linkid.js");x("set","hitCallback",function(){var O=h&&h.hitCallback;na(O)&&O();e.vtp_gtmOnSuccess()});if("TRACK_EVENT"==e.vtp_trackType){}else if("TRACK_SOCIAL"==e.vtp_trackType){}else if("TRACK_TRANSACTION"==e.vtp_trackType){}else if("TRACK_TIMING"==
e.vtp_trackType){}else if("DECORATE_LINK"==e.vtp_trackType){}else if("DECORATE_FORM"==e.vtp_trackType){}else if("TRACK_DATA"==e.vtp_trackType){}else{e.vtp_enableEcommerce&&(x("require","ec","ec.js"),B());if(e.vtp_doubleClick||"DISPLAY_FEATURES"==e.vtp_advertisingFeaturesType){var T=
"_dc_gtm_"+String(e.vtp_trackingId).replace(/[^A-Za-z0-9-]/g,"");x("require","displayfeatures",void 0,{cookieName:T})}if("DISPLAY_FEATURES_WITH_REMARKETING_LISTS"==e.vtp_advertisingFeaturesType){var ra="_dc_gtm_"+String(e.vtp_trackingId).replace(/[^A-Za-z0-9-]/g,"");x("require","adfeatures",{cookieName:ra})}M?x("send","pageview",M):x("send","pageview");}if(!a){var ua=e.vtp_useDebugVersion?"u/analytics_debug.js":"analytics.js";e.vtp_useInternalVersion&&!e.vtp_useDebugVersion&&(ua="internal/"+ua);a=!0;var Ga=vh(h._x_19,"/analytics.js"),la=fg("https:","http:","//www.google-analytics.com/"+ua,h&&h.forceSSL);K("analytics.js"===ua&&Ga?Ga:la,function(){var O=Yg();O&&O.loaded||e.vtp_gtmOnFailure();},e.vtp_gtmOnFailure)}}else G(e.vtp_gtmOnFailure)};
W.__ua=c;W.__ua.b="ua";W.__ua.g=!0;W.__ua.priorityOverride=0}();



W.a.opt=["google"],function(){var a,b=function(c){var d={};if(c.vtp_gaSettings){var e=c.vtp_gaSettings;n(Dl(e.vtp_fieldsToSet,"fieldName","value"),d);c.vtp_gaSettings=null;e.vtp_fieldsToSet=void 0;var f=n(e);c=n(c,f)||{}}n(Dl(c.vtp_fieldsToSet,"fieldName","value"),d);var h=$g(c.vtp_functionName);if(na(h)){h.r=!0;var k="",l="";c.vtp_setTrackerName&&"string"===typeof c.vtp_trackerName?""!==c.vtp_trackerName&&(l=c.vtp_trackerName,k=l+"."):(l="gtm"+wd(),k=l+".");var m={name:!0,clientId:!0,sampleRate:!0,
siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0,useAmpClientId:!0,storeGac:!0},p={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,storeGac:!0},r=function(x,y,A){var B=0,z;for(z in x)if(x.hasOwnProperty(z)&&
(A&&m[z]||!A&&void 0===m[z])){var D=p[z]?Ca(x[z]):x[z];"anonymizeIp"!==z||D||(D=void 0);y[z]=D;B++}return B},t={name:l};r(d,t,!0);var q={"&gtm":Jh(!0)};r(d,q,!1);var u=encodeURI(fg("https:","http:","//www.google-analytics.com/"+(c.vtp_useDebugVersion?"u/analytics_debug.js":"analytics.js"),!!d.forceSSL));h("create",c.vtp_trackingId,t);h(k+"set",q);h(k+"require",c.vtp_optimizeContainerId,{dataLayer:"dataLayer"});h(c.vtp_gtmOnSuccess);h(k+"require","render");a||(a=!0,K(u,function(){return Yg().loaded||
c.vtp_gtmOnFailure()},c.vtp_gtmOnFailure));var w=R("dataLayer"),v=w&&w.hide;v&&(v.end||!0===v["GTM-KP4CRCM"])&&(v[c.vtp_optimizeContainerId]=!0)}else G(c.vtp_gtmOnFailure)};W.__opt=b;W.__opt.b="opt";W.__opt.g=!0;W.__opt.priorityOverride=0}();



W.a.gas=["google"],function(){function a(b,c,d){b.vtp_fieldsToSet=b.vtp_fieldsToSet||[];var e=b[c];void 0!==e&&(b.vtp_fieldsToSet.push({fieldName:d,value:e}),delete b[c])}(function(b){W.__gas=b;W.__gas.b="gas";W.__gas.g=!0;W.__gas.priorityOverride=0})(function(b){var c=n(b),d=c;d[Hb.wa]=null;d[Hb.jf]=null;c=d;a(c,"vtp_cookieDomain","cookieDomain");return c})}();














var vn={};vn.macro=function(a){if(ak.Kc.hasOwnProperty(a))return ak.Kc[a]},vn.onHtmlSuccess=ak.ne(!0),vn.onHtmlFailure=ak.ne(!1);vn.dataLayer=Zd;vn.callback=function(a){ud.hasOwnProperty(a)&&na(ud[a])&&ud[a]();delete ud[a]};function wn(){kd[jd.s]=vn;Ja(vd,W.a);yb=yb||ak;zb=Bg}
function xn(){re.gtm_3pds=!0;kd=E.google_tag_manager=E.google_tag_manager||{};if(kd[jd.s]){var a=kd.zones;a&&a.unregisterChild(jd.s);}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)rb.push(c[d]);for(var e=b.tags||[],f=0;f<e.length;f++)ub.push(e[f]);for(var h=b.predicates||[],k=0;k<h.length;k++)tb.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var p=l[m],r={},t=0;t<p.length;t++)r[p[t][0]]=Array.prototype.slice.call(p[t],1);sb.push(r)}wb=W;xb=wl;wn();Zj();Fg=!1;Gg=0;if("interactive"==F.readyState&&!F.createEventObject||"complete"==F.readyState)Ig();
else{nc(F,"DOMContentLoaded",Ig);nc(F,"readystatechange",Ig);if(F.createEventObject&&F.documentElement.doScroll){var q=!0;try{q=!E.frameElement}catch(x){}q&&Jg()}nc(E,"load",Ig)}uj=!1;"complete"===F.readyState?wj():nc(E,"load",wj);a:{if(!Od)break a;E.setInterval(Pd,
864E5);}rd=(new Date).getTime();}}
(function(a){a()})(xn);

})()
