(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function l(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function n(a){if(!(a instanceof Array)){a=l(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},r;
if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var u;a:{var ca={Ha:!0},da={};try{da.__proto__=ca;u=da.Ha;break a}catch(a){}u=!1}r=u?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ea=r,v="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,w="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function fa(){fa=function(){};v.Symbol||(v.Symbol=ha)}function ia(a,b){this.a=a;w(this,"description",{configurable:!0,writable:!0,value:b})}ia.prototype.toString=function(){return this.a};
var ha=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ia("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function y(){fa();var a=v.Symbol.iterator;a||(a=v.Symbol.iterator=v.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&w(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ja(aa(this))}});y=function(){}}function ja(a){y();a={next:a};a[v.Symbol.iterator]=function(){return this};return a}
function z(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function A(a,b){if(b){var c=v;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&w(c,a,{configurable:!0,writable:!0,value:b})}}
A("WeakMap",function(a){function b(f){this.a=(m+=Math.random()+1).toString();if(f){f=l(f);for(var h;!(h=f.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(f){if(!z(f,g)){var h=new c;w(f,g,{value:h})}}function e(f){var h=Object[f];h&&(Object[f]=function(k){if(k instanceof c)return k;d(k);return h(k)})}if(function(){if(!a||!Object.seal)return!1;try{var f=Object.seal({}),h=Object.seal({}),k=new a([[f,2],[h,3]]);if(2!=k.get(f)||3!=k.get(h))return!1;k.delete(f);k.set(h,4);return!k.has(f)&&
4==k.get(h)}catch(p){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var m=0;b.prototype.set=function(f,h){d(f);if(!z(f,g))throw Error("WeakMap key fail: "+f);f[g][this.a]=h;return this};b.prototype.get=function(f){return z(f,g)?f[g][this.a]:void 0};b.prototype.has=function(f){return z(f,g)&&z(f[g],this.a)};b.prototype.delete=function(f){return z(f,g)&&z(f[g],this.a)?delete f[g][this.a]:!1};return b});
A("Map",function(a){function b(){var f={};return f.s=f.next=f.head=f}function c(f,h){var k=f.a;return ja(function(){if(k){for(;k.head!=f.a;)k=k.s;for(;k.next!=k.head;)return k=k.next,{done:!1,value:h(k)};k=null}return{done:!0,value:void 0}})}function d(f,h){var k=h&&typeof h;"object"==k||"function"==k?g.has(h)?k=g.get(h):(k=""+ ++m,g.set(h,k)):k="p_"+h;var p=f.b[k];if(p&&z(f.b,k))for(f=0;f<p.length;f++){var t=p[f];if(h!==h&&t.key!==t.key||h===t.key)return{id:k,list:p,index:f,j:t}}return{id:k,list:p,
index:-1,j:void 0}}function e(f){this.b={};this.a=b();this.size=0;if(f){f=l(f);for(var h;!(h=f.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),h=new a(l([[f,"s"]]));if("s"!=h.get(f)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var k=h.entries(),p=k.next();if(p.done||p.value[0]!=f||"s"!=p.value[1])return!1;p=k.next();return p.done||4!=p.value[0].x||
"t"!=p.value[1]||!k.next().done?!1:!0}catch(t){return!1}}())return a;y();var g=new WeakMap;e.prototype.set=function(f,h){f=0===f?0:f;var k=d(this,f);k.list||(k.list=this.b[k.id]=[]);k.j?k.j.value=h:(k.j={next:this.a,s:this.a.s,head:this.a,key:f,value:h},k.list.push(k.j),this.a.s.next=k.j,this.a.s=k.j,this.size++);return this};e.prototype.delete=function(f){f=d(this,f);return f.j&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.b[f.id],f.j.s.next=f.j.next,f.j.next.s=f.j.s,f.j.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.s=b();this.size=0};e.prototype.has=function(f){return!!d(this,f).j};e.prototype.get=function(f){return(f=d(this,f).j)&&f.value};e.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};e.prototype.keys=function(){return c(this,function(f){return f.key})};e.prototype.values=function(){return c(this,function(f){return f.value})};e.prototype.forEach=function(f,h){for(var k=this.entries(),p;!(p=k.next()).done;)p=
p.value,f.call(h,p[1],p[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var m=0;return e});A("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});A("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});
A("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});var ka="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)z(d,e)&&(a[e]=d[e])}return a};
A("Object.assign",function(a){return a||ka});var la=this;function C(a,b){a=a.split(".");var c=la;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};function ma(){var a=void 0===a?[]:a;this.l=[];this.g=[];this.h=[];this.a=na();this.b="";Array.isArray(a)||(a=[a]);a.forEach(this.f.bind(this));this.c=this.i.bind(this);window.addEventListener("DOMContentReady",this.c);window.addEventListener("resize",this.c);window.addEventListener("orientationchange",this.c)}function oa(a,b){"function"==typeof b?a.g.push(b):a.f(b)}
ma.prototype.f=function(a){if(a.Ia)pa(this,a);else if(a.media){var b=qa(a.transform,a.nb),c=b.bind(this),d=window.matchMedia(a.media);d.addListener(c);this.l.push({eb:a,mb:d,Ta:c});d.matches&&b(d)}};function pa(a,b){function c(d){var e=b.Ia;-1==e.indexOf(a.b)&&-1!=e.indexOf(a.a)?b.enter(d):b.leave&&-1!=e.indexOf(a.b)&&-1==e.indexOf(a.a)&&b.leave(d)}a.h.push({eb:b,Ta:c});c(a.a);oa(a,c)}function qa(a,b){return function(c){c.matches?a(c):b&&b(c)}}
ma.prototype.i=function(){var a=na();if(this.a!=a){this.b=this.a;this.a=a;a=0;for(var b;b=this.g[a];a++)b(this.a)}};function na(){return window.getComputedStyle(document.body,":after").getPropertyValue("content").replace(/["']/g,"")};function D(a){this.a=a;this.c=new ma;oa(this.c,this.b.bind(this))}D.prototype.b=function(a){this.a.$broadcast("glue.breakpoint.update",a)};D.prototype.constructor=D.prototype.constructor;D.$inject=["$rootScope","$log"];var ra=angular.module("glueCommonBreakpoint",[]);ra.service("glueBreakpoint",D);function sa(a){a=void 0===a?window:a;return 0!=a.glueAppSupported}var ta=/\bglue-app-?\w*\b/;var ua=angular.module("glueApp",[]);ua.run(function(){var a=void 0===a?window:a;sa(a)&&(a=void 0===a?window:a,a=a.document.documentElement,ta.test(a.className)?a.className=a.className.replace(ta,"glue-app-ready"):a.className+=(a.className?" ":"")+"glue-app-ready")});function E(a,b){a.startSymbol("{[");a.endSymbol("]}");b.preAssignBindingsEnabled(!0)}E.$inject=["$interpolateProvider","$compileProvider"];E.module=angular.module("glueCommonConfig",[]);E.module.config(E);var va=angular.module("glueCommon",[ua.name,ra.name,E.module.name]);var wa={qa:"Enter",Ea:" ",Fa:"Tab",ra:"Escape",za:"ArrowLeft",Ga:"ArrowUp",Ca:"ArrowRight",oa:"ArrowDown"},xa={qa:13,Ea:32,Fa:9,ra:27,za:37,Ga:38,Ca:39,oa:40};(function(){var a=new Map;Object.keys(xa).forEach(function(b){a.set(xa[b],wa[b])});return a})();var ya=angular.module("glueState",[E.module.name]);function za(a,b){this.b=a;this.c=b;this.a={};this.b.$on("$locationChangeSuccess",angular.bind(this,this.f))}function Aa(a,b){a.a.modal=b;Ba(a)}function Ca(a,b){b=b||a.a.modal;var c=!1,d=a.c.search(),e;for(e in b)if(b.hasOwnProperty(e)){var g="modal"+Da+e,m=b[e];d[g]!==m&&(c=!0,d[g]=m)}c&&(a.c.search(d),"$apply"!=a.b.$$phase&&"$digest"!=a.b.$$phase&&(a.b.$apply(),a.a.modal=b))}
za.prototype.f=function(){var a={},b=Ba(this),c;for(c in b)if(b.hasOwnProperty(c)){var d=!0;a[c]=this.a[c]}d&&this.b.$broadcast("glue.state.update",a)};function Ba(a){var b=a.c.search(),c={},d;for(d in b)if(b.hasOwnProperty(d)){var e=d.split(Da);if(2===e.length)var g=e;else 2<=e.length?(g=e.pop(),g=[e.join(Da),g]):g=[];if(g&&2===g.length){e=g[0];g=g[1];var m=b[d];if(a.a.hasOwnProperty(e)){var f=a.a[e];void 0===f||void 0!==f[g]&&f[g]===m||(f[g]=m,c[e]=!0)}}}return c}za.$inject=["$rootScope","$location"];
var Da="_";ya.service("glueState",za);var F=angular.module("glueModalService",[E.module.name,ya.name]);function G(a,b,c,d){this.c=a;this.l=b;this.h=d||!1;this.i={};this.f=c;this.b=this.g=null;this.a={active:"none"};Ea(this)}function Ea(a){a.h||(Aa(a.f,a.a),Ca(a.f,a.a));a.c.$on("glue.state.update",angular.bind(a,function(b,c){c.modal&&c.modal.active&&this.c.$broadcast(Fa,this.g,!0)}))}G.prototype.ga=function(){return this.a.active};G.prototype.la=function(){this.a={active:"none"};this.h||Ca(this.f,this.a);this.g="none"};
G.prototype.ja=function(a){this.i[a]={name:a};var b=this.ga();b==a&&this.showModal(b)};G.prototype.showModal=function(a){this.b=this.l[0].activeElement;this.c.$broadcast(Ga,a);this.a={active:a};this.h||Ca(this.f,this.a);this.g=a};G.prototype.A=function(a){this.c.$broadcast(Fa,a,!0)};G.prototype.hideModal=G.prototype.A;G.prototype.showModal=G.prototype.showModal;G.prototype.registerModal=G.prototype.ja;G.prototype.setActiveModalToNone=G.prototype.la;G.prototype.getActiveModalFromState=G.prototype.ga;
G.$inject=["$rootScope","$document","glueState","glueModalServiceStoreRouteDisable"];F.service("glueModalService",G);F.value("glueModalServiceStoreRouteDisable",!1);var Ga="glue.modal.container.showModal",Fa="glue.modal.container.hideModal";(function(a){a=void 0===a?window:a;return a.Element.prototype.closest?!1:(a.Element.prototype.closest=function(b){var c=this;if(!a.document.documentElement.contains(c))return null;do{if(c.matches(b))return c;c=c.parentElement||c.parentNode}while(null!==c&&1===c.nodeType);return null},!0)})();function H(a,b,c,d,e){this.b=a;this.g=b;this.a=c;this.c=d;this.h=e;this.f=!1}
H.prototype.$onInit=function(){this.closeLabel||this.h.warn('An aria label has not been defined for modal "'+this.modalName_+'". Without defining the label, it will fallback to "Close" without localization. Please define a localized label with the data-glue-modal-close-label attribute.');this.closeLabel=this.closeLabel||"Close";Ha(this);this.modalName_&&(this.c.ja(this.modalName_),this.b.$emit(Ia,this.modalName_));this.a.addClass(Ja)};
function Ha(a){a.b.$on(Ka,angular.bind(a,function(b,c){this.modalName_===c&&this.showModal()}));a.b.$on(La,angular.bind(a,function(b,c,d){this.modalName_===c&&this.A(b,d)}));angular.element(document.body).bind("keyup",angular.bind(a,function(b){var c=b.which||b.keyCode;this.f&&27===c&&this.A(b,!0)}));a.a.on("click",angular.bind(a,a.A))}
function Ma(){var a=[].concat(n(document.getElementsByTagName("input"))),b=[].concat(n(document.getElementsByTagName("a"))),c=[].concat(n(document.getElementsByTagName("textarea"))),d=[].concat(n(document.getElementsByTagName("select"))),e=[].concat(n(document.getElementsByTagName("button"))),g=[].concat(n(document.getElementsByTagName("iframe"))),m=[].concat(n(document.querySelectorAll('[role="button"]')));return[].concat(a,b,c,d,e,g,m)}
function Na(a){a=a.a[0];var b=a.querySelectorAll("h2")[0],c=a.querySelectorAll("h3")[0],d=a.querySelectorAll("h4")[0],e=a.querySelectorAll("h5")[0],g=a.querySelectorAll("h6")[0];return(a=a.querySelectorAll("h1")[0]||b||c||d||e||g)?a.textContent:!1}
function Oa(a,b){Ma().forEach(function(c){if(!a.a[0].contains(c))if(b){var d=c.getAttribute(I);d?c.setAttribute(J,d):c.setAttribute(J,"auto");c.setAttribute(I,-1)}else d=c.getAttribute(J),"auto"==d?c.removeAttribute(I):c.setAttribute(I,d),c.removeAttribute(J)})}function Pa(a){var b=angular.element(document).find("body");a.f?b.addClass(Qa):b.removeClass(Qa)}H.prototype.Ra=function(){return this.f};
H.prototype.showModal=function(){this.g(function(){this.f=!0;Pa(this);var a=Na(this);this.b.$emit(Ra,this.modalName_,this.a);this.b.$broadcast("glue.isVisible",this.a);Oa(this,!0);a&&this.a[0].setAttribute(Sa,a);this.g(function(){var b=this.a[0].querySelector("."+Ta);b&&(b.setAttribute(I,"0"),b.focus())}.bind(this),200,!1)}.bind(this))};
H.prototype.A=function(a,b){a=a.target;!b&&a&&a.closest("."+Ua)||this.g(function(){this.f=!1;Pa(this);Oa(this);this.c.la();this.b.$emit(Va,this.modalName_,this.a);this.b.$broadcast("glue.isHidden",this.a);this.a[0].removeAttribute(Sa);this.g(function(){var c=this.a[0].querySelector("."+Ta);c&&c.removeAttribute(I);this.c.b&&(this.c.b.focus(),this.c.b=null)}.bind(this),200,!1)}.bind(this))};H.prototype.hideModal=H.prototype.A;H.prototype.showModal=H.prototype.showModal;H.prototype.getModalVisible=H.prototype.Ra;
H.prototype.constructor=H.prototype.constructor;H.$inject=["$scope","$timeout","$element","glueModalService","$log"];var Ja="glue-c-modal",Ta="glue-c-modal__dialog",Qa="glue-is-showing-modal",Ua="glue-c-modal__content",Sa="aria-label",I="tabindex",J="data-glue-tabindex-previous-value",Ka="glue.modal.container.showModal",La="glue.modal.container.hideModal",Ia="glue.modal.container.modalReady",Ra="glue.modal.container.modalShown",Va="glue.modal.container.modalHidden";var Wa=angular.module("glueShow",["ngAnimate",E.module.name]);function Xa(a){return{restrict:"A",link:function(b,c,d){b.$watch(d.glueShow,function(e){a[e?"addClass":"removeClass"](c,"glue-is-shown");c.attr("aria-hidden",e?"false":"true")})}}}Xa.$inject=["$animate"];Wa.directive("glueShow",Xa);var Ya=angular.module("glueModalContainer",[E.module.name,Wa.name,F.name]);
function Za(a){a.get("/glue/modal/modal-template.html")||a.put("/glue/modal/modal-template.html",'<div>  <div class="glue-c-modal__overlay"      data-glue-show="modalCtrl.getModalVisible()">    <div class="'+Ta+'"        data-glue-show="modalCtrl.getModalVisible()"        role="dialog" tabindex="-1">      <button class="glue-c-modal__close"          aria-label="{[modalCtrl.closeLabel]}">\u00d7</button>      <div class="'+Ua+'          " data-ng-transclude></div>    </div>  </div></div>');return{restrict:"A",
transclude:!0,scope:{modalName_:"@glueModal",closeLabel:"@glueModalCloseLabel"},bindToController:!0,controller:H,controllerAs:"modalCtrl",templateUrl:"/glue/modal/modal-template.html"}}Za.$inject=["$templateCache"];Ya.directive("glueModal",Za);function K(a,b,c){this.g=a;this.c=b;this.b=c;this.a=this.g[$a];this.f=this.g[ab];navigator.userAgent.includes("Mobile")&&navigator.userAgent.includes("Android")?(!this.f||this.f&&1!=this.f)&&bb(this):bb(this)}
function bb(a){a.c.on("click",angular.bind(a,function(b){b.preventDefault();null!=this.a&&this.b.showModal(this.a)}));a.c.on("keypress keydown",angular.bind(a,function(b){var c=b.which||b.keyCode;if(32===c||13===c)b.preventDefault(),null!=this.a&&this.b.showModal(this.a),this.b.b=this.c[0]}.bind(a)))}K.prototype.constructor=K.prototype.constructor;K.$inject=["$scope","$element","glueModalService"];var $a="modalToTrigger",ab="disabledOnMobile";var cb=angular.module("glueModalTrigger",[E.module.name,F.name]);cb.directive("glueModalTrigger",function(){return{restrict:"A",scope:{modalToTrigger:"@glueModalTrigger",disabledOnMobile:"=glueModalDisabledOnMobile"},controller:K,controllerAs:"triggerCtrl"}});var db=angular.module("glueModal",[va.name,Wa.name,F.name,Ya.name,cb.name]);var eb=angular.module("glueYtVideoService",[E.module.name]);function L(a,b){this.EventType={va:"glue.ng.ytVideo.service.IframeApiInitalized"};this.b=a;this.c=b;this.Events={na:"glue.ng.ytVideo.service.IframeApiInitalized"};this.scriptLoaded=this.apiInitialized=!1;this.a={};this.apiInitialized||fb(this)}function fb(a){a.c.onYouTubeIframeAPIReady=angular.bind(a,function(){this.apiInitialized=!0;this.b.$broadcast(this.EventType.va,this)})}
L.prototype.ia=function(){var a=document.createElement("script");a.src="https://www.youtube.com/iframe_api";angular.element(document.body).append(a);this.scriptLoaded=!0};L.prototype.Va=function(){return window.YT&&window.YT.Player?!0:!1};L.prototype.ma=function(a,b){this.a[a]=b};L.prototype.w=function(a){return this.a[a]};L.prototype.getYtPlayer=L.prototype.w;L.prototype.setYtPlayer=L.prototype.ma;L.prototype.isApiReady=L.prototype.Va;L.prototype.initApi=L.prototype.ia;L.$inject=["$rootScope","$window"];
eb.service("glueYtVideoService",L);function M(a,b,c,d,e,g,m){this.h=a;this.b=m;this.f=c;this.D=d;this.g=b;this.u=e?Object.assign({},e):{};this.o=g?Object.assign({},g):{}}
M.prototype.$onInit=function(){this.l=this.ytPlayerVars||{};0!=Object.keys(this.l).length&&Object.assign(this.u,this.l);this.i=this.ytPlayerListeners||{};0!=Object.keys(this.i).length&&Object.assign(this.o,this.i);this.G={width:this.h.glueYtVideoWidth||"",height:this.h.glueYtVideoHeight||"",videoId:this.h.glueYtVideoVid||"",playerVars:this.u,events:this.o};this.c=!1;this.a="";this.F="true"==this.f.attr("data-glue-yt-video-autoplay")};
M.prototype.X=function(){if(!this.c){this.c=!0;var a=this.f.attr("id");angular.isString(a)&&""!==a?this.a=a:(this.a="youtube-player-"+this.g.$id,this.f.attr("id",this.a));this.b.ma(this.a,new this.D.YT.Player(this.f[0],this.G));gb(this)}};M.prototype.w=function(){if(this.c)return this.b.w(this.a)};
function gb(a){a.g.$on("glue.isHidden",function(){return a.b.w(a.a).stopVideo()});a.g.$on("glue.isVisible",function(b,c){b=document.getElementById(a.a);a.c&&c[0].contains(b)&&a.F&&a.b.w(a.a).playVideo()})}M.prototype.$onDestroy=function(){this.c&&delete this.b.a[this.a]};M.prototype.getYtPlayer=M.prototype.w;M.prototype.initializeVideo=M.prototype.X;M.$inject="$attrs $scope $element $window glueYtVideoPlayerVars glueYtVideoPlayerEvents glueYtVideoService".split(" ");var N=angular.module("glueYtVideo",[E.module.name,eb.name]);N.value("glueYtVideoPlayerEvents",{});N.value("glueYtVideoPlayerVars",{});function hb(a){return{restrict:"C",controller:M,scope:{ytPlayerVars:"=glueYtVideoPlayerVars",ytPlayerListeners:"=glueYtVideoListeners"},bindToController:!0,controllerAs:"glueYtVideo",link:function(b,c,d,e){a.apiInitialized||a.scriptLoaded||a.ia();a.apiInitialized?e.X():b.$on(a.Events.na,function(){e.X()})}}}hb.$inject=["glueYtVideoService"];
N.directive("glueYtVideo",hb);var ib={U:"h-is-visible",I:"h-is-showing-drawer",J:"h-is-wholly-scrolled",T:"h-c-header--reversed"},jb={P:".h-js-header__drawer-toggle-link",pa:"#h-js-header__drawer",ba:"#h-js-header__drawer",Z:"#h-js-header__drawer-backdrop",aa:"#h-js-header__drawer-close-btn",H:"data-cached-tabindex",W:"glue-header-vertical-scroll-threshold",V:"glue-header-throttle-timeout",sa:"a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), iframe, object, embed, [tabindex], [contenteditable]"},
kb={W:400,V:50,da:250,ta:350,Da:10};function Q(a){this.a=a=void 0===a?{}:a}v.Object.defineProperties(Q,{b:{configurable:!0,enumerable:!0,get:function(){return{}}},a:{configurable:!0,enumerable:!0,get:function(){return{}}},c:{configurable:!0,enumerable:!0,get:function(){return{}}}});function lb(a,b){function c(){e=setTimeout(d,b);a.apply(void 0,m)}function d(){e=0;g&&(g=!1,c())}var e=0,g=!1,m=[];return function(f){for(var h=[],k=0;k<arguments.length;++k)h[k]=arguments[k];m=h;e?g=!0:c()}};function R(a){Q.call(this,a);this.g=this.u=this.c=this.i=this.G=null;this.R=this.ca=this.f=this.h=0;this.N=!1;this.O=0;this.M=!1}R.prototype=ba(Q.prototype);R.prototype.constructor=R;if(ea)ea(R,Q);else for(var S in Q)if("prototype"!=S)if(Object.defineProperties){var mb=Object.getOwnPropertyDescriptor(Q,S);mb&&Object.defineProperty(R,S,mb)}else R[S]=Q[S];R.f=Q.prototype;R.prototype.Aa=function(){this.a.hasClass(this.b,R.b.J)&&!1===this.N&&this.a.removeClass(this.b,R.b.J)};
R.prototype.ya=function(a){var b=this;a.preventDefault();this.i=a.currentTarget;nb(this,!0);this.i&&this.a.B(this.i,"aria-expanded",!0);this.a.addClass(this.l,R.b.I);this.c&&this.a.addClass(this.c,R.b.U);setTimeout(function(){b.u&&b.a.fa(b.u)},1)};
function nb(a,b){b=void 0===b?!1:b;[].concat(n(a.a.Qa())).forEach(function(c){var d;a.c&&!a.a.Wa(a.c,c)&&(b?((d=a.a.K(c,"tabindex"))?a.a.B(c,R.a.H,d):a.a.B(c,R.a.H,"auto"),a.a.B(c,"tabindex",-1)):(d=a.a.K(c,R.a.H),"auto"===d?a.a.ka(c,"tabindex"):a.a.B(c,"tabindex",d),a.a.ka(c,R.a.H)))})}
R.prototype.L=function(a){var b=this;a.preventDefault();this.a.hasClass(this.l,R.b.I)&&(nb(this,!1),this.i&&this.a.B(this.i,"aria-expanded",!1),this.a.removeClass(this.l,R.b.I),setTimeout(function(){var c=b.G[0];c&&b.a.fa(c)},1),setTimeout(function(){b.c&&b.a.removeClass(b.c,R.b.U)},R.c.ta+1))};R.prototype.xa=function(a){var b=a.key||a.keyCode;"Escape"!==b&&27!==b||this.L(a)};
R.prototype.Ba=function(){var a=this,b=R.b,c=b.J,d=b.T;this.f=this.a.ha();10>=this.f&&this.a.removeClass(this.b,c);this.h&&this.f&&(this.h<this.f?this.f>=this.ca&&(this.a.addClass(this.b,c),setTimeout(function(){var e=a.a.hasClass(a.b,d);a.M&&e&&a.a.removeClass(a.b,d)},R.c.da+1),null!==this.O&&(this.N=!0,clearTimeout(this.O)),this.O=setTimeout(function(){a.N=!1},this.R)):this.f<this.h-R.c.Da&&(this.a.removeClass(this.b,c),0>=this.f&&setTimeout(function(){var e=a.a.hasClass(a.b,d);a.M&&!e&&a.a.addClass(a.b,
d)},R.c.da+2)));this.h=this.f};v.Object.defineProperties(R,{b:{configurable:!0,enumerable:!0,get:function(){return ib}},a:{configurable:!0,enumerable:!0,get:function(){return jb}},c:{configurable:!0,enumerable:!0,get:function(){return kb}}});var T=R.a,ob=T.P,pb=T.pa,qb=T.ba,rb=T.Z,sb=T.aa,tb=T.sa;function U(a,b){this.a=a;this.c=angular.element(b);this.b=angular.element(b.document);this.g=angular.element(b.document.body)}U.prototype.h=function(a,b,c){for(var d=angular.element(c.target);d&&!d.hasClass(a)&&this.a[0].contains(d.parent()[0]);)d=d.parent();d.hasClass(a)&&b(c)};
U.prototype.$onInit=function(){var a=this,b=null,c=this.a[0];this.f=new R({Sa:function(){return a.a},Ka:function(){return a.g},K:function(d,e){return angular.element(d).attr(e)},B:function(d,e,g){return angular.element(d).attr(e,g)},ka:function(d,e){return angular.element(d).removeAttr(e)},ha:function(){return a.c[0].pageYOffset},Pa:function(){return angular.element(c.querySelectorAll(ob))},Na:function(){return ub(a)},Oa:function(){return angular.element(c.querySelector(qb))},La:function(){return angular.element(c.querySelector(rb))},
Ma:function(){return vb(a)[0]},Qa:function(){return a.b[0].querySelectorAll(tb)},Wa:function(d,e){return d[0].contains(e)},ab:function(d){return c.addEventListener("focus",d,!0)},ib:function(d){return c.removeEventListener("focus",d,!0)},Ya:function(d,e){return d.on("click",e)},gb:function(d,e){return d.off("click",e)},Xa:function(d,e){b=a.h.bind(a,d,e);a.a.on("click",b)},fb:function(){a.a.off("click",b)},bb:function(d){return a.b.on("keyup",d)},jb:function(d){return a.b.off("keyup",d)},cb:function(d){return a.c.on("scroll",
d)},kb:function(d){return a.c.off("scroll",d)},Za:function(d){var e=vb(a);if(e)e.on("click",d)},hb:function(d){var e=vb(a);e&&e.off("click",d)},fa:function(d){return angular.element(d)[0].focus()},Ua:function(){return ub(a).attr("role","dialog")},Ja:function(){return ub(a).removeAttr("role")},hasClass:function(d,e){return d.hasClass(e)},addClass:function(d,e){return d.addClass(e)},removeClass:function(d,e){return d.removeClass(e)}})};
function ub(a){return angular.element(a.a[0].querySelector(pb))}function vb(a){return angular.element(a.a[0].querySelector(sb))}
U.prototype.$postLink=function(){var a=this.f;a.b=a.a.Sa();a.l=a.a.Ka();var b=a.a.K(a.b,R.a.W);var c=a.a.K(a.b,R.a.V);a.ca=b?parseInt(b,10):R.c.W;a.R=c?parseInt(c,10):R.c.V;a.M=a.a.hasClass(a.b,R.b.T);a.a.Ua();if(b=a.a.Na()){a.c=b;c=a.a.Pa();var d=a.a.Oa(),e=a.a.La(),g=a.a.Ma();0<c.length?a.G=c:console.warn("Glue Header - Element(s) not found! Element(s) must exist:",R.a.P);d?a.u=d:console.warn("Glue Header - Element(s) not found! Element(s) must exist:",R.a.ba);e?a.g=e:console.warn("Glue Header - Element(s) not found! Element(s) must exist:",
R.a.Z);!g&&b&&console.warn("Glue Header - Element(s) not found! Element(s) must exist if you have a drawer:",R.a.aa);a.G&&a.u&&a.a.Xa(R.a.P.substr(1),a.ya.bind(a));a.g&&(a.D=a.L.bind(a),a.o=a.L.bind(a),a.g&&a.a.Ya(a.g,a.D),a.o&&a.a.Za(a.o));a.F=a.xa.bind(a);a.a.bb(a.F)}a.Y=a.Aa.bind(a);a.a.ab(a.Y);a.h=a.a.ha();a.S=lb(a.Ba.bind(a),a.R);a.a.cb(a.S)};
U.prototype.$onDestroy=function(){var a=this.f,b=R.b,c=b.I,d=b.U,e=b.J;b=b.T;a.Y&&a.a.ib(a.Y);a.a.fb();a.F&&a.a.jb(a.F);a.S&&a.a.kb(a.S);a.g&&a.D&&a.a.gb(a.g,a.D);a.o&&a.a.hb(a.o);a.a.removeClass(a.l,c);a.a.removeClass(a.b,e);a.a.removeClass(a.b,b);a.c&&a.a.removeClass(a.c,d);a.a.Ja()};U.$inject=["$element","$window"];var wb=angular.module("glueMDCHeader",[]);wb.directive("glueHeader",function(){return{restrict:"AC",controller:U,bindToController:!0}});function xb(a){var b=new yb(a),c=b.b.bind(b);c.cancel=function(){b.cancel();return c}.bind(this);return c}function yb(a){this.c=a;this.a=null}yb.prototype.b=function(){clearTimeout(this.a);this.a=setTimeout(this.c,250)};yb.prototype.cancel=function(){clearTimeout(this.a)};function zb(a,b){this.x=void 0===a?0:a;this.a=void 0===b?0:b};function Ab(){var a=window.document;a=a.scrollingElement?a.scrollingElement:a.documentElement||a.body;return new zb(a.scrollLeft,a.scrollTop)};function Bb(a,b,c,d,e){return b+c*e(a/d)}C("ease$$module$node_modules$$google$glue$lib$fx$easing",Bb);function Cb(a){return 0==a||1==a?a:1-Math.cos(Math.PI/2*a)}C("easeInSine$$module$node_modules$$google$glue$lib$fx$easing",Cb);function Db(a){return 0==a||1==a?a:Math.sin(Math.PI/2*a)}C("easeOutSine$$module$node_modules$$google$glue$lib$fx$easing",Db);function Eb(a){return 0==a||1==a?a:-.5*(Math.cos(Math.PI*a)-1)}C("easeInOutSine$$module$node_modules$$google$glue$lib$fx$easing",Eb);
function Fb(a){return 0==a||1==a?a:a*a}C("easeInQuad$$module$node_modules$$google$glue$lib$fx$easing",Fb);function Gb(a){return 0==a||1==a?a:a*(2-a)}C("easeOutQuad$$module$node_modules$$google$glue$lib$fx$easing",Gb);function Ib(a){return 0==a||1==a?a:.5>a?2*a*a:-1+(4-2*a)*a}C("easeInOutQuad$$module$node_modules$$google$glue$lib$fx$easing",Ib);function Jb(a){return 0==a||1==a?a:a*a*a}C("easeInCubic$$module$node_modules$$google$glue$lib$fx$easing",Jb);function Kb(a){return 0==a||1==a?a:--a*a*a+1}
C("easeOutCubic$$module$node_modules$$google$glue$lib$fx$easing",Kb);function Lb(a){return 0==a||1==a?a:.5>a?4*a*a*a:(a-1)*(2*a-2)*(2*a-2)+1}C("easeInOutCubic$$module$node_modules$$google$glue$lib$fx$easing",Lb);function Mb(a){return 0==a||1==a?a:a*a*a*a}C("easeInQuart$$module$node_modules$$google$glue$lib$fx$easing",Mb);function Nb(a){return 0==a||1==a?a:1- --a*a*a*a}C("easeOutQuart$$module$node_modules$$google$glue$lib$fx$easing",Nb);
function Ob(a){return 0==a||1==a?a:.5>a?8*a*a*a*a:1-8*--a*a*a*a}C("easeInOutQuart$$module$node_modules$$google$glue$lib$fx$easing",Ob);function Pb(a){return 0==a||1==a?a:a*a*a*a*a}C("easeInQuint$$module$node_modules$$google$glue$lib$fx$easing",Pb);function Qb(a){return 0==a||1==a?a:1+--a*a*a*a*a}C("easeOutQuint$$module$node_modules$$google$glue$lib$fx$easing",Qb);function Rb(a){return 0==a||1==a?a:.5>a?16*a*a*a*a*a:1+16*--a*a*a*a*a}
C("easeInOutQuint$$module$node_modules$$google$glue$lib$fx$easing",Rb);function Sb(a){return 0==a||1==a?a:Math.pow(2,10*(a-1))}C("easeInExpo$$module$node_modules$$google$glue$lib$fx$easing",Sb);function Tb(a){return 0==a||1==a?a:1-Math.pow(2,-10*a)}C("easeOutExpo$$module$node_modules$$google$glue$lib$fx$easing",Tb);function Ub(a){return 0==a||1==a?a:.5>a?.5*Math.pow(2,10*(2*a-1)):.5*(2-Math.pow(2,-10*(2*a-1)))}C("easeInOutExpo$$module$node_modules$$google$glue$lib$fx$easing",Ub);
function Vb(a){return 0==a||1==a?a:1-Math.sqrt(1-a*a)}C("easeInCirc$$module$node_modules$$google$glue$lib$fx$easing",Vb);function Wb(a){return 0==a||1==a?a:Math.sqrt(1-(a-1)*(a-1))}C("easeOutCirc$$module$node_modules$$google$glue$lib$fx$easing",Wb);function Xb(a){return 0==a||1==a?a:.5>a?-.5*(Math.sqrt(1-a*a*4)-1):.5*(Math.sqrt(1-4*(a-1)*(a-1))+1)}C("easeInOutCirc$$module$node_modules$$google$glue$lib$fx$easing",Xb);function Yb(a){return 0==a||1==a?a:a*a*(2.70158*a-1.70158)}
C("easeInBack$$module$node_modules$$google$glue$lib$fx$easing",Yb);function Zb(a){return 0==a||1==a?a:(a-1)*(a-1)*(2.70158*(a-1)+1.70158)+1}C("easeOutBack$$module$node_modules$$google$glue$lib$fx$easing",Zb);function $b(a){return 0==a||1==a?a:.5>a?2*a*a*(7.189819*a-2.5949095):.5*((2*a-2)*(2*a-2)*(3.5949095*(2*a-2)+2.5949095)+2)}C("easeInOutBack$$module$node_modules$$google$glue$lib$fx$easing",$b);function ac(a){return 0==a||1==a?a:-1*Math.pow(2,10*(a-1))*Math.sin(2*(a-1.075)*Math.PI/.3)}
C("easeInElastic$$module$node_modules$$google$glue$lib$fx$easing",ac);function bc(a){return 0==a||1==a?a:Math.pow(2,-10*a)*Math.sin(2*(a-.075)*Math.PI/.3)+1}C("easeOutElastic$$module$node_modules$$google$glue$lib$fx$easing",bc);function cc(a){return 0==a||1==a?a:.5>a?-.5*Math.pow(2,10*(2*a-1))*Math.sin(2*(2*a-1.1125)*Math.PI/.45):.5*Math.pow(2,-10*(2*a-1))*Math.sin(2*(2*a-1.1125)*Math.PI/.45)+1}C("easeInOutElastic$$module$node_modules$$google$glue$lib$fx$easing",cc);
function dc(a){return 0==a||1==a?a:1-V(1-a)}C("easeInBounce$$module$node_modules$$google$glue$lib$fx$easing",dc);function V(a){return 0==a||1==a?a:a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-1.5/2.75)*(a-1.5/2.75)+.75:a<2.5/2.75?7.5625*(a-2.25/2.75)*(a-2.25/2.75)+.9375:7.5625*(a-2.625/2.75)*(a-2.625/2.75)+.984375}C("easeOutBounce$$module$node_modules$$google$glue$lib$fx$easing",V);function ec(a){return 0==a||1==a?a:.5>a?.5*dc(2*a):.5*V(2*a-1)+.5}
C("easeInOutBounce$$module$node_modules$$google$glue$lib$fx$easing",ec);function fc(a){return a}C("linear$$module$node_modules$$google$glue$lib$fx$easing",fc);
var gc=new Map([["ease",Bb],["easeInSine",Cb],["easeOutSine",Db],["easeInOutSine",Eb],["easeInQuad",Fb],["easeOutQuad",Gb],["easeInOutQuad",Ib],["easeInCubic",Jb],["easeOutCubic",Kb],["easeInOutCubic",Lb],["easeInQuart",Mb],["easeOutQuart",Nb],["easeInOutQuart",Ob],["easeInQuint",Pb],["easeOutQuint",Qb],["easeInOutQuint",Rb],["easeInExpo",Sb],["easeOutExpo",Tb],["easeInOutExpo",Ub],["easeInCirc",Vb],["easeOutCirc",Wb],["easeInOutCirc",Xb],["easeInBack",Yb],["easeOutBack",Zb],["easeInOutBack",$b],
["easeInElastic",ac],["easeOutElastic",bc],["easeInOutElastic",cc],["easeInBounce",dc],["easeOutBounce",V],["easeInOutBounce",ec],["linear",fc]]);C("easingFuncMap$$module$node_modules$$google$glue$lib$fx$easing",gc);(function(a){a=a||window;return a.Array.prototype.includes?!1:(a.Array.prototype.includes=function(b,c){if(null==this)throw new TypeError('"this" is null or not defined');var d=Object(this),e=d.length>>>0;if(0===e)return!1;c|=0;for(c=Math.max(0<=c?c:e-Math.abs(c),0);c<e;){var g=d[c];if(g===b||"number"===typeof g&&"number"===typeof b&&isNaN(g)&&isNaN(b))return!0;c++}return!1},!0)})();
var hc="perspective rotate rotateX rotateY rotateZ scale scaleX scaleY scaleZ translateX translateY translateZ".split(" "),ic=["opacity"],X=["transform","-o-transform","-ms-transform","-moz-transform","-webkit-transform"],jc=new Map([["deg","deg"],["rem","rem"],["em","em"],["ex","ex"],["ch","ch"],["vh","vh"],["vw","vw"],["vmin","vmin"],["vmax","vmax"],["px","px"],["mm","mm"],["cm","cm"],["in","in"],["pt","pt"],["pc","pc"],["mozmm","mozmm"],["%","%"]]);
function kc(a){this.a=a;this.g=[];this.f=null;this.c=new zb(0,0);this.b=this.h=0;this.i=!1;lc(this)}
function lc(a){var b={},c;for(c in a.a){if(a.a.hasOwnProperty(c)){var d=document.querySelectorAll(c);if(0<d.length&&0<a.a[c].length){b.v={};a.a[c].forEach(function(f){return function(h,k){Object.keys(h.from).forEach(function(p){h.from[p]&&(f.v[p]?f.v[p].push(k):f.v[p]=[k])})}}(b));for(var e=0,g=void 0;g=d[e];e++){var m={};m.element=g;m.C=a.a[c];m.ea=b.v;a.g.push(m)}}}b={v:b.v}}mc(a,!0);a.l=lb(function(){return mc(a,!0)},200);a.o=function(){return nc(a)};window.addEventListener("resize",a.l);window.addEventListener("scroll",
a.o);oc(a)}function nc(a){a.f?window.clearTimeout(a.f):(a.i=!0,pc(a));a.c=Ab();a.f=window.setTimeout(function(){a.i=!1;a.f=null},300)}function pc(a){a.i&&window.requestAnimationFrame(function(){return pc(a)});oc(a)}
function oc(a){a.h!=document.documentElement.offsetHeight&&mc(a,!1);for(var b=0;b<a.g.length;b++)for(var c=a,d=a.g[b],e=d.element,g=c.c.a,m=0;m<d.C.length;m++){var f=d.C[m];f.range||(f.range="parent");f.m||(f.m="before");var h=qc(c,e,f.range,f.scope),k=g>=h[0]&&g<=h[1],p=f.easing?f.easing:"none",t=(g-h[0])/(h[1]-h[0]);t=Math.min(Math.max(t,0),1);g<h[0]?"within"==f.m?(f.m="before",Y(e,f,"exit","up")):"after"==f.m&&(f.m="before",Y(e,f,"enter","up"),Y(e,f,"exit","up")):k?"before"==f.m?(f.m="within",
Y(e,f,"enter","down")):"after"==f.m&&(f.m="within",Y(e,f,"enter","up")):"before"==f.m?(f.m="after",Y(e,f,"enter","down"),Y(e,f,"exit","down")):"within"==f.m&&(f.m="after",Y(e,f,"exit","down"));for(var q in f.from)if(f.from.hasOwnProperty(q)&&f.to.hasOwnProperty(q))if(1==d.ea[q].length||k){var B=f.from[q];var O=f.to[q],W=t,P=p;if(0>=W)var x=B.toString();else if(1<=W)x=O.toString();else{var Hb=W;x="";P&&"linear"!=P&&"none"!=P&&"function"===typeof gc.get(P)&&(Hb=gc.get(P)(W));"string"===typeof B&&(x=
rc(B));"string"===typeof O&&(""==x?x=rc(O):x!==rc(O)&&(x=""));B=(parseFloat(O)-parseFloat(B))*Hb+parseFloat(B);""!=x&&(B=B.toFixed(2));x=parseFloat(B).toString()+x}ic.includes(q)?sc(e,q,x):hc.includes(q)&&tc(e,q,x)}else uc(c,d,q,m,h)}}function mc(a,b){a.h=document.body.scrollHeight;a.b=a.h-window.innerHeight;b&&(a.c=Ab())}
function uc(a,b,c,d,e){var g=b.element,m=!1,f=document.body.scrollHeight,h=a.c.a;if(h<e[0]){f=e[0]-h;var k=!0}else h>e[1]&&h-e[1]<f&&(f=h-e[1],k=!1);var p=d;b.ea[c].forEach(function(t){if(t!=d){var q=qc(a,g,b.C[t].range,b.C[t].scope);h>=q[0]&&h<=q[1]?m=!0:h<q[0]&&q[0]-h<f?(f=q[0]-h,p=t,k=!0):h>q[1]&&h-q[1]<f&&(f=h-q[1],p=t,k=!1)}});m||null==k||(e=b.C[p],e=k?e.from[c]:e.to[c],ic.includes(c)?sc(g,c,e):hc.includes(c)&&tc(g,c,e))}
function sc(a,b,c){if(X.includes(b))for(b=0;b<X.length;b++)a.style[X[b]]=c.toString();else"opacity"==b?a.style.opacity=parseFloat(c):a.style[b]=c.toString()}function tc(a,b,c){var d;a:{for(d=0;d<X.length;d++){var e=a.style[X[d]];if(e&&"none"!=e){d=e;break a}}d=""}if(d.includes(b)){d=d.split(")");for(e=0;e<d.length;e++)if(d[e].includes(b)){var g=d[e].split("(");g[1]="("+c;d[e]=g.join("")}d=d.join(")")}else d+=" "+b+"("+c+")";sc(a,"transform",d)}
function rc(a){return(a=a.match(/\D+$/))?jc.get(a.join(""))||"":""}
function qc(a,b,c,d){var e=document.body!=b.parentNode&&document.body.contains(b.parentNode),g=e?b.parentNode.getBoundingClientRect():document.body.getBoundingClientRect(),m=e?g.top+a.c.a-Math.max(document.documentElement.clientHeight,window.innerHeight||0):0;b=e?g.top+a.c.a+b.parentNode.offsetHeight:a.b;g=b-m;if("string"===typeof c){if("parent"==c&&e)return[m,b]}else{if("parent"==d&&e)return"number"===typeof c[0]&&"number"===typeof c[1]?[c[0]+m,c[1]+m]:c[0].includes("%")&&c[1].includes("%")?[parseFloat(c[0])/
100*g+m,parseFloat(c[1])/100*g+m]:[m+(isNaN(parseFloat(c[0]))?0:parseFloat(c[0])),m+(isNaN(parseFloat(c[1]))?0:parseFloat(c[1]))];if(Array.isArray(c))return"number"===typeof c[0]&&"number"===typeof c[1]?c:c[0].includes("%")&&c[1].includes("%")?[a.b*parseFloat(c[0])/100,a.b*parseFloat(c[1])/100]:[isNaN(parseFloat(c[0]))?0:parseFloat(c[0]),isNaN(parseFloat(c[1]))?a.b:parseFloat(c[1])]}return[0,a.b]}
function Y(a,b,c,d){if(b.callbacks)for(var e=0;e<b.callbacks.length;e++){var g=b.callbacks[e];g.timing!=c||g.direction&&g.direction!=d||"function"!==typeof g.ua||g.lb&&g.wa||(g.ua.call(a),g.wa=!0)}};var vc={".parallax__avatar":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-30px"},easing:"easeInOutQuad"}],".parallax__maps":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-100px"},easing:"easeInOutQuad"}],".parallax__video":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-100px"},easing:"easeInOutQuad"}],".parallax__title":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-30px"},easing:"easeInOutQuad"}],".parallax__sun":[{range:["0%",
"800px"],from:{translateY:"0px"},to:{translateY:"-20px"},easing:"easeInOutQuad"}],".parallax__cam":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-50px"},easing:"easeInOutQuad"}],".parallax__typing":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-350px"},easing:"easeInOutQuad"}],".parallax__middle-right":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-550px"},easing:"easeInOutQuad"}],".parallax__pizza":[{range:["0%","800px"],from:{translateY:"0px"},
to:{translateY:"-150px"},easing:"easeInOutQuad"}]};var wc={".parallax__avatar":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-30px"},easing:"easeInOutQuad"}],".parallax__red-pants":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-100px"},easing:"easeInOutQuad"}],".parallax__maps":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-100px"},easing:"easeInOutQuad"}],".parallax__video":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-100px"},easing:"easeInOutQuad"}],".parallax__title":[{range:["0%",
"800px"],from:{translateY:"0px"},to:{translateY:"-30px"},easing:"easeInOutQuad"}],".parallax__sun":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-20px"},easing:"easeInOutQuad"}],".parallax__cam":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-50px"},easing:"easeInOutQuad"}],".parallax__chat":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-50px"},easing:"easeInOutQuad"}],".parallax__dog":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-50px"},
easing:"easeInOutQuad"}],".parallax__bottom-left":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-350px"},easing:"easeInOutQuad"}],".parallax__typing":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-350px"},easing:"easeInOutQuad"}],".parallax__bottom-middle":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-350px"},easing:"easeInOutQuad"}],".parallax__bottom-right":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-375px"},easing:"easeInOutQuad"}],
".parallax__bottom-middle-right":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-550px"},easing:"easeInOutQuad"}],".parallax__pizza":[{range:["0%","800px"],from:{translateY:"0px"},to:{translateY:"-150px"},easing:"easeInOutQuad"}]};function xc(){this.a=null;var a=1024>window.innerWidth?vc:wc,b=this.a=new kc(a);b.a=a;lc(b);window.addEventListener("resize",xb(this.b.bind(this)))}xc.prototype.b=function(){var a=this.a;a.a=1024>window.innerWidth?vc:wc;lc(a)};var yc=angular.module("app",[va.name,db.name,wb.name,N.name]).value("glueModalServiceStoreRouteDisable",!0).controller("MainController",xc).name,Z=void 0;Z=void 0===Z?window:Z;sa(Z)&&Z.angular&&Z.angular.bootstrap(Z.document.documentElement,[yc],void 0);}).call(window)
