(function(h,f,u){function x(){if(1!=ipsclass.settings.do_linked_resize)return!0;for(var a=f.getElementsByTagName("IMG"),b=0,c='<img src="'+ipb_var_image_url+'/img-resized.png" style="vertical-align:middle" border="0" alt="" />',e=screen.width*(parseInt(ipsclass.settings.resize_percent)/100),d=0;d<a.length;d++)if("linked-image"==a[d].className&&(b++,a[d].width>e)){var k=a[d].width,g=a[d].height,s=0;a[d].width=e;a[d].width<k&&0<k&&0<a[d].width&&(s=Math.ceil(parseInt(a[d].width/k*100)));a[d].id="--ipb-img-resizer-"+
b;a[d]._resized=1;a[d]._width=k;var l=f.createElement("div");l.innerHTML=c+"&nbsp;"+ipsclass.lang_build_string(ipb_global_lang.image_resized,s,k,g);l.style.width=a[d].width-4+"px";l.className="resized-linked-image";l.style.paddingTop="2px";l.style.paddingBottom="2px";l.style.paddingLeft="2px";l.style.paddingRight="2px";l._is_div=1;l._resize_id=b;l.onclick=fix_linked_images_onclick;l.onmouseover=fix_linked_images_mouseover;l.title=ipb_global_lang.click_to_view;l._src=a[d].src;a[d].parentNode.insertBefore(l,
a[d])}}function A(a){try{this.style.cursor="pointer"}catch(b){}}function y(){var a=[],b=arguments,c,e,d;for(c=0;c<b.length;c++)for(d=f.getElementsByTagName(b[c]),e=0;e<d.length;e++)a.push(d[e]);return a}function r(a,b){return a&&a.getAttribute?a.getAttribute(b):u}var v=[];h.ajax_loaded=1;(function(){if(!h.add_onload_event&&$4){var a=[];$4.onInit("f-m-j",function(){for(;a.length;)h.add_onload_event(a.shift());a=null});h.add_onload_event=function(b){a.push(b)}}})();h.fix_linked_img_thumb=function(a,
b,c,e){var d='<img src="'+ipb_var_image_url+'/img-resized.png" style="vertical-align:middle" border="0" alt="" />',k=f.querySelectorAll("#ipb-attach-img-"+a),g=f.querySelectorAll("#ipb-attach-div-"+a),s=f.querySelectorAll("#ipb-attach-ct-"+a),l=f.querySelectorAll("#ipb-attach-cb-"+a);f.querySelectorAll("#ipb-attach-url-"+a);a=f.querySelectorAll("#ipb-attach-table-"+a);for(var m,q=0,h=k.length,p;q<h;q++)if(p=k[q]){tbl_obj=a[q];div_obj=g[q];ct_obj=s[q];cb_obj=l[q];var n=parseInt(p.width)?parseInt(p.width):
parseInt(p.style.width),z=parseInt(p.height)?parseInt(p.height):parseInt(p.style.height);is_ie&&(n=parseInt(p.currentStyle.width),z=parseInt(p.currentStyle.height));is_safari&&(tbl_obj.style.display="inline-block");b&&c&&(m=Math.ceil(100-parseInt(n/b*100)));p.className="ipb";p.title=ipb_global_lang.click_to_view;p.onmouseover=A;div_obj.style.width=(140<n?n:140)+"px";div_obj.style.height=z+10+28+"px";div_obj.className="resized-linked-image";div_obj.style.paddingTop="5px";div_obj.style.paddingBottom=
"5px";div_obj.style.paddingLeft="8px";div_obj.style.paddingRight="8px";div_obj.style.textAlign="center";div_obj.title=ipb_global_lang.click_to_view;ct_obj.style.fontSize="9px";cb_obj.style.fontSize="9px";cb_obj.style.textAlign="center";ct_obj.innerHTML=0<m?d+"&nbsp;"+ipsclass.lang_build_string(ipb_global_lang.image_attach_percent,m):d+"&nbsp;"+ipb_global_lang.image_attach_no_percent;cb_obj.innerHTML="";b&&c&&(cb_obj.innerHTML=ipsclass.lang_build_string(ipb_global_lang.image_attach_dims,b,c));cb_obj.innerHTML+=
ipsclass.lang_build_string(ipb_global_lang.image_attach_size,e)}};h.add_onload_event(x);h.emoticon=function(a,b,c){a=" "+a+" ";b=f.getElementById("fastreplyarea");if(4<=ua_vers&&is_ie&&is_win)if(b.isTextEdit){b.focus();c=f.selection;var e=c.createRange();e.colapse;"Text"!=c.type&&"None"!=c.type||null==e||(""!=a&&0<e.text.length&&(a=e.text+a),e.text=a)}else b.value+=a;else if(b.selectionEnd){e=b.selectionStart;c=b.scrollTop;var d=b.selectionEnd;2>=d&&(d=b.textLength);var k=b.value.substring(0,e),g=
b.value.substring(e,d),d=b.value.substring(d,b.textLength),g=a+g;b.value=k+g+d;a=e+g.length;b.selectionStart=a;b.selectionEnd=a;b.scrollTop=c}else b.value+=a;b.focus();4<=ua_vers&&is_ie&&is_win&&"undefined"!=emowindow&&emowindow.focus()};h.ajax_cancel_for_edit=function(a){""!=v[a]&&(f.getElementById("post-"+a).innerHTML=v[a],BBEditors[a]=u);return!1};h.ajax_save_for_edit=function(a){var b=ipb_var_base_url+"act=post&do=post-edit-save&p="+a+"&t="+ipb_input_t+"&f="+ipb_input_f,c=[];c.md5check=ipb_md5_check;
c.t=ipb_input_t;c.f=ipb_input_f;c.p=a;c.act="post";c["do"]="post-edit-save";c.post=f.getElementById(a+"_textarea").value;c.std_used=1;try{c.post_edit_reason=f.getElementById("post_edit_reason").value}catch(e){}if(""==c.post.replace(/^\s*|\s*$/g,""))return alert(js_no_empty_post),!1;do_request_function=function(){if(xmlobj.readystate_ready_and_ok()){xmlobj.hide_loading();var b=xmlobj.xmlhandler.responseText;if("nopermission"==b)alert(js_error_no_permission),f.getElementById("post-"+a).innerHTML=v[a];
else if("error"!=b){var c=f.getElementById("post-"+a);c.innerHTML=b;for(var g=c.querySelectorAll('script[type="text/javascript"][class="noemoticons"]'),s=g.length,l=0;l<s;l++)try{eval(g[l].innerHTML.replace(/^\<\!--|--\>$/,""))}catch(m){}jsEmoticons.parse(c);initPostBlock();xmlobj.execute_javascript(b);x()}BBEditors[a]=u}else xmlobj.show_loading()};xmlobj=new ajax_request;xmlobj.onreadystatechange(do_request_function);xmlobj.process(b,"POST",xmlobj.format_for_post(c));return!1};h.ajax_prep_for_edit=
function(a,b,c){global_cancel_bubble(b,!0);b=f.getElementById("post-main-"+a);var e=_get_obj_toppos(b);b=ipb_var_base_url+"act=post&do=post-edit-show&p="+a+"&t="+ipb_input_t+"&f="+ipb_input_f;v[a]=f.getElementById("post-"+a).innerHTML;try{menu_action_close()}catch(d){}do_request_function=function(){if(xmlobj.readystate_ready_and_ok()){xmlobj.hide_loading();var b=xmlobj.xmlhandler.responseText;if("nopermission"==b)alert(js_error_no_permission);else if("error"!=b){e&&scroll(0,e-30);f.getElementById("post-"+
a).innerHTML=b;try{BBEditors[a]=new BBEditor(a,1,ipb_var_board_url+"/jscripts"),f.getElementById("post_edit_reason").onkeydown=function(b){b=b||windows.event;13==b.keyCode&&(ajax_save_for_edit(a),b.preventDefault&&b.preventDefault(),b.returnValue=!1)},"function"===typeof c&&c(BBEditors[a])}catch(g){alert(g)}}}else xmlobj.show_loading()};xmlobj=new ajax_request;xmlobj.onreadystatechange(do_request_function);xmlobj.process(b);return!1};h.link_to_post=function(a){temp=prompt(ipb_lang_tt_prompt,ipb_var_base_url+
"showtopic="+ipb_input_t+"&view=findpost&p="+a);return!1};h.topic_toggle_pid=function(a){if(isNaN(a))return!1;saved=[];clean=[];add=1;tmp=f.modform.selectedpids.value;saved=tmp.split(",");for(i=0;i<saved.length;i++)""!=saved[i]&&(saved[i]==a?add=0:clean[clean.length]=saved[i]);add?(clean[clean.length]=a,eval("document.img"+a+".src=selectedbutton")):eval(" document.img"+a+".src=unselectedbutton");newvalue=clean.join(",");my_setcookie("modpids",newvalue,0);f.modform.selectedpids.value=newvalue;newcount=
stacksize(clean);f.modform.gobutton.value=lang_gobutton+" ("+newcount+")";return!1};h.ins=function(a,b){my_show_div(my_getbyid("qr_open"));if(f.REPLIER.post){var c=f.REPLIER.post,e=(b?"[SNAPBACK]"+b+"[/SNAPBACK] ":"")+"[b]"+a+",[/b]\n";c.BBEditor?c.BBEditor.insert_text(e,!0):c.value+=e}};var t="";h.copyQ=function(a,b,c){t=(""+(h.getSelection?h.getSelection():f.getSelection?f.getSelection():f.selection.createRange().text)).trim();""!=t.replace(" ","")&&a&&b&&c&&(a=a.replace(/"/g,'\\"'),t='[quote name="'+
a+'" date="'+b+'" post="'+c+'"]\n'+t+"\n[/quote]\n")};h.pasteQ=function(){my_show_div(my_getbyid("qr_open"));var a;if(a=f.REPLIER.post)a.BBEditor?a.BBEditor.insert_text(t,!0):f.REPLIER.post.value+=t};$4.onInit("jQuery",function(a){function b(){if(k){var a=k.data("tmr");a&&clearTimeout(a);k.data("tmr",setTimeout(function(){k.data("tmr",0);k.data("range",!1);k=!1},500))}}function c(){var g=!1;try{g=h.getSelection().getRangeAt(0)}catch(c){}if(g)if(k&&b(),g.startContainer==g.endContainer&&g.startOffset==
g.endOffset)b();else{var d=g.cloneRange();d.collapse(!1);var e=f.createElement("span");d.insertNode(e);var d=a(e).closest("[data-post]"),w=parseInt(d.data("post"));e.getBoundingClientRect();e.parentNode.removeChild(e);if(!d.length||1>w)d=!1,w=0;if(!d||1>w)b();else if(e=a('[data-quote-link="'+w+'"]',d),e.length){if(d=e.data("tmr"))clearTimeout(d),e.data("tmr",0);k=e;if(!e.data("fix-range"))e.data("fix-range",1).data("omo",e.prop("onmouseover")).prop("onmouseover","").attr("onmouseover","").prop("href",
"#").attr("href","#").on("click",function(b){b.preventDefault();try{var g=a(this),c=g.data("r"),d=h.getSelection(),e=g.data("omo");d.removeAllRanges();c&&(d.addRange(c),e instanceof Function&&e(),pasteQ(),g.data("r",!1))}catch(s){}});e.data("r",g)}else b()}else b()}function e(){g&&clearTimeout(g);g=setTimeout(c,300)}var d=a(f),k=!1,g=0;d.ready(function(){var a=!1;if("BBEditors"in h)for(var g in h.BBEditors)if(h.BBEditors.propertyIsEnumerable(g)){a=!0;break}a&&(b(),d.on("selectionchange",e))})});h.initAwar=
function(){var a,b,c,e=y("img","a");for(a=0;a<e.length;a++)if(b=e[a],(c=r(b,"attach_id"))&&b instanceof Object&&b.getAttribute&&"number"!=typeof b.a_id&&(b.a_id=parseInt(r(b,"attach_id"),10),b.a_id)){c=parseInt(r(b,"s"),10);var d=f.createElement("a");d.className="awar_btn report";0==c?(d.href='javascript:window.location="'+ipb_var_base_url+"act=awar&CODE=report&attach_id="+b.a_id+"&st="+ipb_var_st+'";',d.title="Отправить заявку на удаление файла"):(d.title="Заявка на удаление этого файла в обработке",
d.href="javascript:alert('"+d.title+"');");b.parentNode.insertBefore(d,b)}};h.initModAwar=function(){var a,b,c,e=y("img","a");for(a=0;a<e.length;a++)if(b=e[a],(c=r(b,"attach_id"))&&b instanceof Object&&b.getAttribute&&"number"!=typeof b.am_id&&(b.am_id=parseInt(r(b,"attach_id"),10),b.am_id&&(c=parseInt(r(b,"s"),10),3==c||4==c)))c=f.createElement("a"),c.className="awar_btn info",c.title="Перейти к тикету",c.href='javascript:window.location="'+ipb_var_base_url+"act=awar&CODE=ticket&attach_id="+b.am_id+
'";',b.parentNode.insertBefore(c,b)};(function(a,b,c){var e=function(a,g){var c="getElementById";g=g||b;g.querySelector&&(c="querySelector",a="#"+a);return g[c](a)},d=function(a,g){var c="getElementsByTagName";g=g||b;g.querySelectorAll&&(c="querySelectorAll");return g[c](a)};a.buildFastModPid=function(a,b,c,d){if(a&&b&&c&&d){var f=e("pb-"+b+"-mod1");f&&(f.innerHTML='<a href="#" onclick="return fastModPid('+parseInt(b)+",'"+c+"','"+d+"');\">"+a+"</a>")}};a.fastModPid=function(a,g,c){if(a&&c){var l=
ipb_var_base_url;g={act:"Mod",CODE:g,f:ipb_input_f,t:ipb_input_t,auth_key:ipb_md5_check,gobutton:1,st:ipb_var_st,tact:c};var f;g.selectedpids=parseInt(a);f=new ajax_request;f.onreadystatechange(function(){if(f.readystate_ready_and_ok()){f.hide_loading();var g=b.createElement("div"),c=[],l=[];g.innerHTML=f.xmlhandler.responseText;c=[e("post-main-"+a),e("post-main-"+a,g)];l=[e("pb-"+a+"-r3"),e("pb-"+a+"-r3",g)];c[0].parentNode.insertBefore(c[1],c[0]);c[0].parentNode.removeChild(c[0]);g=d("script",c[1]);
for(c=0;c<g.length;c++)try{eval(g[c].innerHTML)}catch(s){}g=d("script",l[1]);for(c=0;c<g.length;c++)try{eval(g[c].innerHTML)}catch(h){}}else f.show_loading()});f.process(l,"POST",f.format_for_post(g));f.show_loading();return!1}}})(h,f);f.addEventListener&&function(){function a(a,b){b||(b=f);return b.querySelector(a)}function b(a,b){return r(a,"data-"+b)}function c(g,c){c||(c=g);return function(d){if(d&&d.form){var e=a('input[type="button"][onclick^="ajax_save_for_edit("]',d.form),h=a("input#post_edit_reason",
d.form),k=d._textarea;if(e){k.selectionStart=k.selectionEnd=(k.value+"").length;try{k.onblur()}catch(p){}var n=f.createElement("input");n.type="button";n.value="Вставить";n.setAttribute("data-link",g);n.setAttribute("title",c);n.addEventListener("click",function(a){a.preventDefault&&a.preventDefault();a.returnValue=!1;a=b(n,"link");var c=r(n,"title");h&&(h.value=c);d.insert_text("[url="+a+"]"+c+"[/url]",1);k.focus();return!1},!1);e.parentNode.insertBefore(n,e);("externalMods"in d?d.externalMods:d.externalMods=
{}).toPinpost=n}}}}function e(a){for(var b=[];a;)b.push(a),a=a.parentElement||a.parentNode;b.push(h);return b}function d(a){/in/.test(f.readyState)?setTimeout(function(){d(a)},9):a()}var k=!1;f.addEventListener("click",function(a){var d=a.target||a.srcElement,f="path"in a?a.path:e(d),m=!1;for(;(d=f.shift())&&!(m=b(d,"to-pinpost")||!1););if(d&&m&&k&&(a.preventDefault&&a.preventDefault(),a.returnValue=!1,pid=parseInt(b(k,"post")),!isNaN(pid)&&0<pid&&(a=t||m,f=d.href||b(d,"href")||"",a=prompt("Введите название ссылки на пост для добавления в шапку:",
a.charAt(0).toUpperCase()+a.substr(1)))))if(d=c(f,a),BBEditors[pid]){var m=BBEditors[pid],q="externalMods"in m?m.externalMods:m.externalMods={};"toPinpost"in q||d(m,m.form);d=q.toPinpost;d.setAttribute("data-link",f);d.setAttribute("title",a);try{m.form.scrollIntoView(),m._textarea.focus()}catch(r){}}else{a=h.event;f=function(){};f={stopPropagation:f,preventDefault:f};try{h.event=f}catch(p){}ajax_prep_for_edit(pid,f,d);try{h.event=a}catch(n){}}},!1);h.reinitToPinpost=function(){var c=(k=a("#topic-pin-content [data-post]"))?
parseInt(b(k,"post")):0;post_content=u;els=f.querySelectorAll("[data-to-pinpost]");i=0;if(!isNaN(c)&&0<c)if(BBEditors[c])post_content=BBEditors[c]._textarea.value;else if(post_content=a("#post-"+c))post_content=post_content.innerHTML;for(;i<els.length;i++){var c=els[i],d=parseInt(b(c,"to-pinpost-id")),e=!isNaN(d)&&0<d?RegExp("(\\?|&(amp;)?)p(id)?="+d+"[\"'\\]]"):0;c.addEventListener("mouseover",copyQ,!1);if(k){c.style.display="";var d=c.querySelectorAll("[data-to-pinpost-exist]"),h=0,q=(e=post_content&&
e&&post_content.match(e))?"yes":"no";c.classList.toggle("blue",!e);for(c.classList.toggle("green",e);h<d.length;h++)d[h].style.display=b(d[h],"to-pinpost-exist")==q?"":"none"}else c.style.display="none"}(i=a("#topic-pin-content [data-to-pinpost]"))&&(i.style.display="none")};d(reinitToPinpost)}()})(window,document);
