(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function ea(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,g){this.a=e;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ha(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}
ea("Promise",function(a){function b(h){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{h(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.a=null}function d(h){return h instanceof b?h:new b(function(k){k(h)})}if(a)return a;c.prototype.b=function(h){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(h)};var e=da.setTimeout;c.prototype.c=function(h){e(h,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var h=this.a;this.a=[];for(var k=0;k<h.length;++k){var m=
h[k];h[k]=null;try{m()}catch(q){this.f(q)}}}this.a=null};c.prototype.f=function(h){this.c(function(){throw h;})};b.prototype.c=function(){function h(q){return function(B){m||(m=!0,q.call(k,B))}}var k=this,m=!1;return{resolve:h(this.G),reject:h(this.f)}};b.prototype.G=function(h){if(h===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof b)this.H(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.s(h):this.h(h)}};
b.prototype.s=function(h){var k=void 0;try{k=h.then}catch(m){this.f(m);return}"function"==typeof k?this.J(k,h):this.h(h)};b.prototype.f=function(h){this.i(2,h)};b.prototype.h=function(h){this.i(1,h)};b.prototype.i=function(h,k){if(0!=this.b)throw Error("Cannot settle("+h+", "+k+"): Promise already settled in state"+this.b);this.b=h;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var h=0;h<this.a.length;++h)g.b(this.a[h]);this.a=null}};var g=new c;b.prototype.H=function(h){var k=this.c();
h.A(k.resolve,k.reject)};b.prototype.J=function(h,k){var m=this.c();try{h.call(k,m.resolve,m.reject)}catch(q){m.reject(q)}};b.prototype.then=function(h,k){function m(G,O){return"function"==typeof G?function(Ia){try{q(G(Ia))}catch(Ja){B(Ja)}}:O}var q,B,Ka=new b(function(G,O){q=G;B=O});this.A(m(h,q),m(k,B));return Ka};b.prototype.catch=function(h){return this.then(void 0,h)};b.prototype.A=function(h,k){function m(){switch(q.b){case 1:h(q.g);break;case 2:k(q.g);break;default:throw Error("Unexpected state: "+
q.b);}}var q=this;null==this.a?g.b(m):this.a.push(m)};b.resolve=d;b.reject=function(h){return new b(function(k,m){m(h)})};b.race=function(h){return new b(function(k,m){for(var q=ha(h),B=q.next();!B.done;B=q.next())d(B.value).A(k,m)})};b.all=function(h){var k=ha(h),m=k.next();return m.done?d([]):new b(function(q,B){function Ka(Ia){return function(Ja){G[Ia]=Ja;O--;0==O&&q(G)}}var G=[],O=0;do G.push(void 0),O++,d(m.value).A(Ka(G.length-1),B),m=k.next();while(!m.done)})};return b});
function ia(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function ja(){this.h=!1;this.f=null;this.j=void 0;this.a=1;this.g=this.c=0;this.i=this.b=null}function ka(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}f=ja.prototype;f.B=function(a){this.j=a};function la(a,b){a.b={L:b,M:!0};a.a=a.c||a.g}f.return=function(a){this.b={return:a};this.a=this.g};f.Na=function(a){this.b={o:a};this.a=this.g};
function l(a,b,c){a.a=c;return{value:b}}f.Ec=function(a,b){a=ha(a);var c=a.next();ia(c);if(c.done)this.j=c.value,this.a=b;else return this.f=a,l(this,c.value,b)};f.o=function(a){this.a=a};f.Oa=function(){this.a=0};f.eb=function(a){this.c=0;this.g=a||0};function ma(a,b){a.a=b;a.c=0}function na(a){a.c=0;var b=a.b.L;a.b=null;return b}f.aa=function(a,b,c){c?this.i[c]=this.b:this.i=[this.b];this.c=a||0;this.g=b||0};
f.Pa=function(a,b){b=this.i.splice(b||0)[0];(b=this.b=this.b||b)?b.M?this.a=this.c||this.g:void 0!=b.o&&this.g<b.o?(this.a=b.o,this.b=null):this.a=this.g:this.a=a};f.da=function(a){return new oa(a)};function oa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}oa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function pa(a){this.a=new ja;this.b=a}
function qa(a,b){ka(a.a);var c=a.a.f;if(c)return ra(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return sa(a)}function ra(a,b,c,d){try{var e=b.call(a.a.f,c);ia(e);if(!e.done)return a.a.h=!1,e;var g=e.value}catch(h){return a.a.f=null,la(a.a,h),sa(a)}a.a.f=null;d.call(a.a,g);return sa(a)}
function sa(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,la(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.M)throw b.L;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ta(a){this.next=function(b){ka(a.a);a.a.f?b=ra(a,a.a.f.next,b,a.a.B):(a.a.B(b),b=sa(a));return b};this.throw=function(b){ka(a.a);a.a.f?b=ra(a,a.a.f["throw"],b,a.a.B):(la(a.a,b),b=sa(a));return b};this.return=function(b){return qa(a,b)};this[Symbol.iterator]=function(){return this}}function ua(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(g,e)}g(a.next())})}
var n=this||self;function va(a){a=a.split(".");for(var b=n,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function wa(){}function xa(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function ya(a){var b=xa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function za(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function Aa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Ba=Date.now||function(){return+new Date};function Ca(a,b){a=a.split(".");var c=n;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function Da(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.U=function(d,e,g){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var Ea=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Fa=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},Ga=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in e&&(d[g]=b.call(void 0,e[g],g,a));return d};function Ha(a){return Array.prototype.concat.apply([],arguments)}function La(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ma(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function Na(a){if(8192>=a.length)return String.fromCharCode.apply(null,a);for(var b="",c=0;c<a.length;c+=8192)b+=String.fromCharCode.apply(null,Ma(a,c,c+8192));return b};function Oa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Pa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var Qa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function p(a,b){return-1!=a.indexOf(b)}function Ra(a,b){return a<b?-1:a>b?1:0};var r;a:{var Sa=n.navigator;if(Sa){var Ta=Sa.userAgent;if(Ta){r=Ta;break a}}r=""};var t=0,u=0;function Ua(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;t=b;u=a}function v(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));t=c;u=a}function Va(a){var b=0>a;a=2*Math.abs(a);Ua(a);a=t;var c=u;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);t=a;u=c}
function Wa(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?t=u=0:(u=0,t=2147483648);else if(isNaN(a))u=0,t=2147483647;else if(3.4028234663852886E38<a)u=0,t=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),u=0,t=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;u=0;t=(b<<31|c+127<<23|a)>>>0}}
function Xa(a){var b=a.charCodeAt(4),c=a.charCodeAt(5),d=a.charCodeAt(6),e=a.charCodeAt(7);t=a.charCodeAt(0)+(a.charCodeAt(1)<<8)+(a.charCodeAt(2)<<16)+(a.charCodeAt(3)<<24)>>>0;u=b+(c<<8)+(d<<16)+(e<<24)>>>0}function Ya(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function Za(a){function b(h,k){for(var m=0;8>m&&(1!==h||0<k);m++)k=h*e[m]+k,e[m]=k&255,k>>>=8}function c(){for(var h=0;8>h;h++)e[h]=~e[h]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],g=0;g<a.length;g++)b(10,a.charCodeAt(g)-48);d&&(c(),b(1,1));return Na(e)};function w(a,b){this.a=a;this.b=b}function $a(a){return new w((a.a>>>1|(a.b&1)<<31)>>>0,a.b>>>1>>>0)}function ab(a){return new w(a.a<<1>>>0,(a.b<<1|a.a>>>31)>>>0)}f=w.prototype;f.Ua=function(){return!!(this.a&1)};f.add=function(a){return new w((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};f.sub=function(a){return new w((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};
function bb(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new w(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.a||0!=b.b;){var c=new w(0,0);b=new w(b.a,b.b);for(var d=new w(10,0),e=new w(1,0);!(d.b&2147483648);)d=ab(d),e=ab(e);for(;0!=e.a||0!=e.b;)0>=(d.b<b.b||d.b==b.b&&d.a<b.a?-1:d.b==b.b&&d.a==b.a?0:1)&&(c=c.add(e),b=b.sub(d)),d=$a(d),e=$a(e);c=[c,b];b=c[0];a=c[1].a+a}""==a&&(a="0");return a};
function cb(a){for(var b=new w(0,0),c=new w(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.a=parseInt(a[d],10);var e=bb(b.a);b=bb(b.b);b.b=b.a;b.a=0;b=e.add(b).add(c)}return b}f.Ma=function(){return new w(this.a,this.b)};function x(a,b){this.a=a;this.b=b}x.prototype.add=function(a){return new x((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};
x.prototype.sub=function(a){return new x((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};x.prototype.c=function(){return new x(this.a,this.b)};x.prototype.toString=function(){var a=0!=(this.b&2147483648),b=new w(this.a,this.b);a&&(b=(new w(0,0)).sub(b));return(a?"-":"")+b.toString()};function db(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=cb(a);if(null===a)return null;b&&(a=(new w(0,0)).sub(a));return new x(a.a,a.b)};function eb(){this.a=[]}f=eb.prototype;f.length=function(){return this.a.length};function fb(a){var b=a.a;a.a=[];return b}function y(a,b,c){for(;0<c||127<b;)a.a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.a.push(b)}function z(a,b,c){A(a,b);A(a,c)}function gb(a,b,c){Ya(b,c,function(d,e){y(a,d>>>0,e>>>0)})}function C(a,b){for(;127<b;)a.a.push(b&127|128),b>>>=7;a.a.push(b)}function D(a,b){if(0<=b)C(a,b);else{for(var c=0;9>c;c++)a.a.push(b&127|128),b>>=7;a.a.push(1)}}
function hb(a,b){C(a,(b<<1^b>>31)>>>0)}function ib(a,b){Xa(Za(b));Ya(t,u,function(c,d){y(a,c>>>0,d>>>0)})}f.Dc=function(a){this.a.push(a>>>0&255)};f.Cc=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};function A(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}function jb(a,b){Ua(b);A(a,t);A(a,u)}f.zb=function(a){this.a.push(a>>>0&255)};f.yb=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};
function kb(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}
function lb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)u=0<1/c?0:2147483648,t=0;else if(isNaN(c))u=2147483647,t=4294967295;else if(1.7976931348623157E308<c)u=(b<<31|2146435072)>>>0,t=0;else if(2.2250738585072014E-308>c)c/=Math.pow(2,-1074),u=(b<<31|c/4294967296)>>>0,t=c>>>0;else{var d=c,e=0;if(2<=d)for(;2<=d&&1023>e;)e++,d/=2;else for(;1>d&&-1022<e;)d*=2,e--;c*=Math.pow(2,-e);u=(b<<31|e+1023<<20|1048576*c&1048575)>>>0;t=4503599627370496*c>>>0}A(a,t);A(a,u)}
f.Ka=function(a){this.a.push.apply(this.a,a)};function mb(a){mb[" "](a);return a}mb[" "]=wa;var nb=p(r,"Opera"),E=p(r,"Trident")||p(r,"MSIE"),ob=p(r,"Edge"),pb=p(r,"Gecko")&&!(p(r.toLowerCase(),"webkit")&&!p(r,"Edge"))&&!(p(r,"Trident")||p(r,"MSIE"))&&!p(r,"Edge"),qb=p(r.toLowerCase(),"webkit")&&!p(r,"Edge"),rb=p(r,"Macintosh");function sb(){var a=n.document;return a?a.documentMode:void 0}var tb;
a:{var ub="",vb=function(){var a=r;if(pb)return/rv:([^\);]+)(\)|;)/.exec(a);if(ob)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(qb)return/WebKit\/(\S+)/.exec(a);if(nb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();vb&&(ub=vb?vb[1]:"");if(E){var wb=sb();if(null!=wb&&wb>parseFloat(ub)){tb=String(wb);break a}}tb=ub}var xb=tb,yb={},zb;if(n.document&&E){var Ab=sb();zb=Ab?Ab:parseInt(xb,10)||void 0}else zb=void 0;var Bb=zb;var Cb={},Db=null;function Eb(a,b){void 0===b&&(b=0);Fb();b=Cb[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],g=d+1<a.length,h=g?a[d+1]:0,k=d+2<a.length,m=k?a[d+2]:0,q=e>>2;e=(e&3)<<4|h>>4;h=(h&15)<<2|m>>6;m&=63;k||(m=64,g||(h=64));c.push(b[q],b[e],b[h]||"",b[m]||"")}return c.join("")}function Gb(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):p("=.",a[b-1])&&(c=p("=.",a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Hb(a,function(g){d[e++]=g});return d.subarray(0,e)}
function Hb(a,b){function c(m){for(;d<a.length;){var q=a.charAt(d++),B=Db[q];if(null!=B)return B;if(!/^[\s\xa0]*$/.test(q))throw Error("Unknown base64 encoding at char: "+q);}return m}Fb();for(var d=0;;){var e=c(-1),g=c(0),h=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|g>>4);64!=h&&(b(g<<4&240|h>>2),64!=k&&b(h<<6&192|k))}}
function Fb(){if(!Db){Db={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Cb[c]=d;for(var e=0;e<d.length;e++){var g=d[e];void 0===Db[g]&&(Db[g]=e)}}}};function Ib(){this.c=[];this.b=0;this.a=new eb;this.f=[]}function Jb(a,b){var c=fb(a.a);a.c.push(c);a.c.push(b);a.b+=c.length+b.length}function F(a,b){H(a,b,2);b=fb(a.a);a.c.push(b);a.b+=b.length;b.push(a.b);return b}function I(a,b){var c=b.pop();for(c=a.b+a.a.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.b++;b.push(c);a.b++}f=Ib.prototype;f.Wa=function(a,b,c){null!=a&&null!=b&&null!=c&&Jb(this,a.subarray(b,c))};f.La=function(){this.c=[];fb(this.a);this.b=0;this.f=[]};
function Kb(a){for(var b=new Uint8Array(a.b+a.a.length()),c=a.c,d=c.length,e=0,g=0;g<d;g++){var h=c[g];b.set(h,e);e+=h.length}c=fb(a.a);b.set(c,e);a.c=[b];return b}f.ka=function(a){return Eb(Kb(this),a)};f.V=function(a){this.f.push(F(this,a))};f.$=function(){I(this,this.f.pop())};function H(a,b,c){C(a.a,8*b+c)}
f.wb=function(a,b,c){switch(a){case 1:null!=c&&(H(this,b,1),lb(this.a,c));break;case 2:null!=c&&(H(this,b,5),a=this.a,Wa(c),A(a,t));break;case 3:null!=c&&null!=c&&(H(this,b,0),a=this.a,v(c),y(a,t,u));break;case 4:null!=c&&null!=c&&(H(this,b,0),a=this.a,v(c),y(a,t,u));break;case 5:null!=c&&Lb(this,b,c);break;case 6:null!=c&&(H(this,b,1),jb(this.a,c));break;case 7:null!=c&&(H(this,b,5),A(this.a,c));break;case 8:Mb(this,b,c);break;case 9:J(this,b,c);break;case 12:Nb(this,b,c);break;case 13:null!=c&&
Ob(this,b,c);break;case 14:Pb(this,b,c);break;case 15:null!=c&&(H(this,b,5),kb(this.a,c));break;case 16:null!=c&&(H(this,b,1),a=this.a,v(c),z(a,t,u));break;case 17:null!=c&&null!=c&&(H(this,b,0),hb(this.a,c));break;case 18:null!=c&&null!=c&&(H(this,b,0),a=this.a,Va(c),y(a,t,u))}};function Ob(a,b,c){null!=c&&(H(a,b,0),C(a.a,c))}function Lb(a,b,c){null!=c&&(H(a,b,0),D(a.a,c))}f.Bc=function(a,b){null!=b&&null!=b&&(H(this,a,0),ib(this.a,b))};function Mb(a,b,c){null!=c&&(H(a,b,0),a.a.a.push(c?1:0))}
function Pb(a,b,c){null!=c&&(H(a,b,0),D(a.a,c))}
function J(a,b,c){if(null!=c){b=F(a,b);for(var d=a.a,e=0;e<c.length;e++){var g=c.charCodeAt(e);if(128>g)d.a.push(g);else if(2048>g)d.a.push(g>>6|192),d.a.push(g&63|128);else if(65536>g)if(55296<=g&&56319>=g&&e+1<c.length){var h=c.charCodeAt(e+1);56320<=h&&57343>=h&&(g=1024*(g-55296)+h-56320+65536,d.a.push(g>>18|240),d.a.push(g>>12&63|128),d.a.push(g>>6&63|128),d.a.push(g&63|128),e++)}else d.a.push(g>>12|224),d.a.push(g>>6&63|128),d.a.push(g&63|128)}I(a,b)}}
function Nb(a,b,c){null!=c&&(c=c.constructor===Uint8Array?c:c.constructor===ArrayBuffer?new Uint8Array(c):c.constructor===Array?new Uint8Array(c):c.constructor===String?Gb(c):new Uint8Array(0),H(a,b,2),C(a.a,c.length),Jb(a,c))}f.Ab=function(a,b,c){null!=b&&(a=F(this,a),c(b,this),I(this,a))};f.Bb=function(a,b,c){null!=b&&(H(this,1,3),H(this,2,0),D(this.a,a),a=F(this,3),c(b,this),I(this,a),H(this,1,4))};f.xb=function(a,b,c){null!=b&&(H(this,a,3),c(b,this),H(this,a,4))};
f.jc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Lb(this,a,b[c])};f.kc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Lb(this,a,parseInt(d,10))}};f.lc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,0);var e=this.a;v(d);y(e,t,u)}}};f.uc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);H(this,a,1);z(this.a,g,h)}};
f.vc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);H(this,a,0);y(this.a,g,h)}};f.wc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);H(this,a,0);gb(this.a,g>>>0,h>>>0)}};f.mc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=db(e),H(this,d,0),y(this.a,e.a,e.b))}};f.xc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Ob(this,a,b[c])};
f.yc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Ob(this,a,parseInt(d,10))}};f.zc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,0);var e=this.a;v(d);y(e,t,u)}}};f.Ac=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=cb(e),H(this,d,0),y(this.a,e.a,e.b))}};f.rc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,0),hb(this.a,d))}};
f.sc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,0);var e=this.a;Va(d);y(e,t,u)}}};f.tc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,0),ib(this.a,d))}};f.dc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,5),A(this.a,d))}};f.ec=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,1),jb(this.a,d))}};
f.fc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=cb(e),H(this,d,1),z(this.a,e.a,e.b))}};f.oc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,5),kb(this.a,d))}};f.pc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,1);var e=this.a;v(d);z(e,t,u)}}};f.qc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=db(e),H(this,d,1),z(this.a,e.a,e.b))}};
f.hc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){H(this,a,5);var e=this.a;Wa(d);A(e,t)}}};f.bc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(H(this,a,1),lb(this.a,d))}};f.$b=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Mb(this,a,b[c])};f.cc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Pb(this,a,b[c])};function Qb(a,b,c){if(null!=c)for(var d=0;d<c.length;d++)J(a,b,c[d])}
f.ac=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Nb(this,a,b[c])};f.nc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=F(this,a);c(b[d],this);I(this,e)}};f.ic=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)H(this,a,3),c(b[d],this),H(this,a,4)};f.Jb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)D(this.a,b[c]);I(this,a)}};f.Kb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)D(this.a,parseInt(b[c],10));I(this,a)}};
f.Lb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=this.a;v(b[c]);y(d,t,u)}I(this,a)}};f.Tb=function(a,b,c,d){if(null!=b){a=F(this,a);for(var e=0;e<b.length;e++)z(this.a,c(b[e]),d(b[e]));I(this,a)}};f.Ub=function(a,b,c,d){if(null!=b){a=F(this,a);for(var e=0;e<b.length;e++)y(this.a,c(b[e]),d(b[e]));I(this,a)}};f.Vb=function(a,b,c,d){if(null!=b){a=F(this,a);for(var e=this.a,g=0;g<b.length;g++)gb(e,c(b[g]),d(b[g]));I(this,a)}};
f.Mb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=db(b[c]);y(this.a,d.a,d.b)}I(this,a)}};f.Wb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)C(this.a,b[c]);I(this,a)}};f.Xb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)C(this.a,parseInt(b[c],10));I(this,a)}};f.Yb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=this.a;v(b[c]);y(d,t,u)}I(this,a)}};
f.Zb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=cb(b[c]);y(this.a,d.a,d.b)}I(this,a)}};f.Qb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)hb(this.a,b[c]);I(this,a)}};f.Rb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++){var d=this.a;Va(b[c]);y(d,t,u)}I(this,a)}};f.Sb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)ib(this.a,b[c]);I(this,a)}};
f.Fb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,4*b.length),a=0;a<b.length;a++)A(this.a,b[a])};f.Gb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,8*b.length),a=0;a<b.length;a++)jb(this.a,b[a])};f.Hb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,8*b.length),a=0;a<b.length;a++){var c=cb(b[a]);z(this.a,c.a,c.b)}};f.Nb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,4*b.length),a=0;a<b.length;a++)kb(this.a,b[a])};
f.Ob=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;v(b[a]);z(c,t,u)}};f.Pb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;Xa(Za(b[a]));z(c,t,u)}};f.Ib=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,4*b.length),a=0;a<b.length;a++){var c=this.a;Wa(b[a]);A(c,t)}};f.Db=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,8*b.length),a=0;a<b.length;a++)lb(this.a,b[a])};
f.Cb=function(a,b){if(null!=b&&b.length)for(H(this,a,2),C(this.a,b.length),a=0;a<b.length;a++)this.a.a.push(b[a]?1:0)};f.Eb=function(a,b){if(null!=b&&b.length){a=F(this,a);for(var c=0;c<b.length;c++)D(this.a,b[c]);I(this,a)}};function Rb(){}var Sb="function"==typeof Uint8Array;Rb.prototype.j=function(){return this.h};var Tb=[];function Ub(a){var b=a.f+a.g;a.a[b]||(a.b=a.a[b]={})}function K(a,b){if(b<a.f){b+=a.g;var c=a.a[b];return c===Tb?a.a[b]=[]:c}if(a.b)return c=a.b[b],c===Tb?a.b[b]=[]:c}function L(a,b,c){a=K(a,b);return null==a?c:a}function M(a,b){a=K(a,b);a=null==a?a:!!a;return null==a?!1:a}function Vb(a,b,c){b<a.f?a.a[b+a.g]=c:(Ub(a),a.b[b]=c);return a}
function N(a,b,c,d){c!==d?Vb(a,b,c):b<a.f?a.a[b+a.g]=null:(Ub(a),delete a.b[b]);return a}function Wb(a,b,c,d){b=K(a,b);void 0!=d?b.splice(d,0,c):b.push(c);return a}f=Rb.prototype;f.qb=function(){if(this.c)for(var a in this.c){var b=this.c[a];if(Array.isArray(b))for(var c=0;c<b.length;c++);}};
f.N=Sb?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return Eb(this)};try{return JSON.stringify(this.a&&this.a,Xb)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.a&&this.a,Xb)};function Xb(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)}f.toString=function(){return this.a.toString()};
f.Ya=function(a){Ub(this);this.c||(this.c={});var b=a.c;return a.f?a.a()?(this.c[b]||(this.c[b]=Ga(this.b[b]||[],function(c){return new a.b(c)})),this.c[b]):this.b[b]=this.b[b]||[]:a.a()?(!this.c[b]&&this.b[b]&&(this.c[b]=new a.b(this.b[b])),this.c[b]):this.b[b]};f.cb=function(a,b){this.c||(this.c={});Ub(this);var c=a.c;a.f?(b=b||[],a.a()?(this.c[c]=b,this.b[c]=Ga(b,function(d){return d.a})):this.b[c]=b):a.a()?(this.c[c]=b,this.b[c]=b?b.a:b):this.b[c]=b;return this};f.Z=function(){return new this.constructor(Yb(this.a))};
f.Xa=function(){return new this.constructor(Yb(this.a))};function Yb(a){if(Array.isArray(a)){for(var b=Array(a.length),c=0;c<a.length;c++){var d=a[c];null!=d&&(b[c]="object"==typeof d?Yb(d):d)}return b}if(Sb&&a instanceof Uint8Array)return new Uint8Array(a);b={};for(c in a)d=a[c],null!=d&&(b[c]="object"==typeof d?Yb(d):d);return b};function Zb(a){var b=a;a=$b;this.c=null;b||(b=[]);this.h=void 0;this.g=-1;this.a=b;a:{if(b=this.a.length){--b;var c=this.a[b];if(!(null===c||"object"!=typeof c||Array.isArray(c)||Sb&&c instanceof Uint8Array)){this.f=b- -1;this.b=c;break a}}this.f=Number.MAX_VALUE}this.i={};if(a)for(b=0;b<a.length;b++)c=a[b],c<this.f?(c+=-1,this.a[c]=this.a[c]||Tb):(Ub(this),this.b[c]=this.b[c]||Tb)}Da(Zb,Rb);var $b=[10,12];f=Zb.prototype;
f.Za=function(a){var b,c={rb:L(this,1,0),locale:L(this,2,""),T:L(this,4,""),ma:L(this,5,""),sb:L(this,6,""),Fa:L(this,7,""),Ha:M(this,8),Ga:M(this,9),W:null==(b=K(this,10))?void 0:b,Ia:M(this,11),pb:null==(b=K(this,12))?void 0:b};a&&(c.P=this);return c};
f.ab=function(){var a=new Ib;var b=this.getTenantId();0!==b&&Pb(a,1,b);b=this.getLocale();0<b.length&&J(a,2,b);b=L(this,4,"");0<b.length&&J(a,4,b);b=L(this,5,"");0<b.length&&J(a,5,b);b=L(this,6,"");0<b.length&&J(a,6,b);b=this.getInsecureHost();0<b.length&&J(a,7,b);(b=M(this,8))&&Mb(a,8,b);(b=M(this,9))&&Mb(a,9,b);b=K(this,10);0<b.length&&Qb(a,10,b);(b=M(this,11))&&Mb(a,11,b);b=K(this,12);0<b.length&&Qb(a,12,b);return Kb(a)};f.getTenantId=function(){return L(this,1,0)};
f.nb=function(a){return N(this,1,a,0)};f.getLocale=function(){return L(this,2,"")};f.bb=function(a){return N(this,4,a,"")};f.fb=function(a){return N(this,5,a,"")};f.ob=function(a){return N(this,6,a,"")};f.getInsecureHost=function(){return L(this,7,"")};f.gb=function(a){return N(this,7,a,"")};f.ib=function(a){return N(this,8,a,!1)};f.hb=function(a){return N(this,9,a,!1)};f.R=function(a,b){return Wb(this,10,a,b)};f.X=function(){return Vb(this,10,[])};f.jb=function(a){return N(this,11,a,!1)};
f.S=function(a,b){return Wb(this,12,a,b)};f.Y=function(){return Vb(this,12,[])};function ac(){var a=GoogleDevelopersObject;return new Zb(a?JSON.parse(a):null)};var bc="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""};function cc(){}cc.prototype.next=function(){throw bc;};cc.prototype.a=function(){return this};function dc(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof dc)for(c=a.m(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=dc.prototype;f.l=function(){P(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};f.m=function(){P(this);return this.a.concat()};
f.Ba=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(Q(this.b,c)&&this.b[c]==a)return!0}return!1};f.ba=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||ec;P(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function ec(a,b){return a===b}f.Ca=function(){return 0==this.c};f.Aa=function(){this.b={};this.f=this.c=this.a.length=0};
function P(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Q(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],Q(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}f.get=function(a,b){return Q(this.b,a)?this.b[a]:b};f.set=function(a,b){Q(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};f.forEach=function(a,b){for(var c=this.m(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};
f.tb=function(){for(var a=new dc,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};f.Da=function(){P(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};f.ga=function(){return fc(this,!0)};f.la=function(){return fc(this,!1)};function fc(a,b){P(a);var c=0,d=a.f,e=new cc;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw bc;var g=a.a[c++];return b?g:a.b[g]};return e}
function Q(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function gc(a){if(a.l&&"function"==typeof a.l)return a.l();if("string"===typeof a)return a.split("");if(ya(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function hc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(ya(a)||"string"===typeof a)Fa(a,b,c);else{if(a.m&&"function"==typeof a.m)var d=a.m();else if(a.l&&"function"==typeof a.l)d=void 0;else if(ya(a)||"string"===typeof a){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=gc(a);g=e.length;for(var h=0;h<g;h++)b.call(c,e[h],d&&d[h],a)}};var ic=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function jc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function R(a,b){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.s=!1;if(a instanceof R){this.g=void 0!==b?b:a.g;kc(this,a.h);var c=a.j;S(this);this.j=c;c=a.b;S(this);this.b=c;lc(this,a.f);c=a.c;S(this);this.c=c;mc(this,nc(a.a));a=a.i;S(this);this.i=a}else a&&(c=String(a).match(ic))?(this.g=!!b,kc(this,c[1]||"",!0),a=c[2]||"",S(this),this.j=T(a),a=c[3]||"",S(this),this.b=T(a,!0),lc(this,c[4]),a=c[5]||"",S(this),this.c=T(a,!0),mc(this,c[6]||"",!0),a=c[7]||"",S(this),this.i=T(a)):(this.g=
!!b,this.a=new oc(null,this.g))}f=R.prototype;f.toString=function(){var a=[],b=this.h;b&&a.push(pc(b,qc,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(pc(b,qc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(pc(c,"/"==c.charAt(0)?rc:sc,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",pc(c,tc));return a.join("")};
f.resolve=function(a){var b=new R(this),c=!!a.h;c?kc(b,a.h):c=!!a.j;if(c){var d=a.j;S(b);b.j=d}else c=!!a.b;c?(d=a.b,S(b),b.b=d):c=null!=a.f;d=a.c;if(c)lc(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(p(e,"./")||p(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&g.push(""):".."==k?((1<g.length||1==g.length&&""!=
g[0])&&g.pop(),d&&h==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?(S(b),b.c=d):c=""!==a.a.toString();c?mc(b,nc(a.a)):c=!!a.i;c&&(a=a.i,S(b),b.i=a);return b};function kc(a,b,c){S(a);a.h=c?T(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function lc(a,b){S(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function mc(a,b,c){S(a);b instanceof oc?(a.a=b,uc(a.a,a.g)):(c||(b=pc(b,vc)),a.a=new oc(b,a.g));return a}f.lb=function(a,b){return mc(this,a,b)};
f.ea=function(){return T(this.a.toString())};f.sa=function(){return this.a.toString()};f.kb=function(a,b){S(this);Array.isArray(b)||(b=[String(b)]);wc(this.a,a,b);return this};f.ja=function(a){return this.a.l(a)};f.ia=function(a){return this.a.get(a)};f.Ea=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
f.Va=function(){S(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Ba()).toString(36);S(this);this.a.set("zx",a);return this};f.ta=function(a){S(this);xc(this.a,a);return this};f.mb=function(a){this.s=a;return this};f.Ja=function(){return this.s};function S(a){if(a.s)throw Error("Tried to modify a read-only Uri");}f.ua=function(a){this.g=a;this.a&&uc(this.a,a);return this};function yc(a){return a instanceof R?new R(a):new R(a,void 0)}
function T(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function pc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,zc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function zc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var qc=/[#\/\?@]/g,sc=/[#\?:]/g,rc=/[#\?]/g,vc=/[#\?@]/g,tc=/#/g;function oc(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function U(a){a.a||(a.a=new dc,a.b=0,a.c&&jc(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=oc.prototype;f.qa=function(){U(this);return this.b};f.add=function(a,b){U(this);this.c=null;a=V(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function xc(a,b){U(a);b=V(a,b);Q(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,Q(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&P(a)))}f.na=function(){this.a=this.c=null;this.b=0};
f.ra=function(){U(this);return 0==this.b};function Ac(a,b){U(a);b=V(a,b);return Q(a.a.b,b)}f.oa=function(a){var b=this.l();return 0<=Ea(b,a)};f.forEach=function(a,b){U(this);this.a.forEach(function(c,d){Fa(c,function(e){a.call(b,e,d,this)},this)},this)};f.m=function(){U(this);for(var a=this.a.l(),b=this.a.m(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
f.l=function(a){U(this);var b=[];if("string"===typeof a)Ac(this,a)&&(b=Ha(b,this.a.get(V(this,a))));else{a=this.a.l();for(var c=0;c<a.length;c++)b=Ha(b,a[c])}return b};f.set=function(a,b){U(this);this.c=null;a=V(this,a);Ac(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};f.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};function wc(a,b,c){xc(a,b);0<c.length&&(a.c=null,a.a.set(V(a,b),La(c)),a.b+=c.length)}
f.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.m(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.l(d);for(var g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.c=a.join("&")};f.ca=function(a){U(this);this.a.forEach(function(b,c){0<=Ea(a,c)||xc(this,c)},this);return this};function nc(a){var b=new oc;b.c=a.c;a.a&&(b.a=new dc(a.a),b.b=a.b);return b}
function V(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function uc(a,b){b&&!a.f&&(U(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(xc(this,d),wc(this,e,c))},a));a.f=b}f.pa=function(a){for(var b=0;b<arguments.length;b++)hc(arguments[b],function(c,d){this.add(d,c)},this)};var Bc={};function Cc(a,b){var c=Bc[a];if(void 0!==c&&(!c.I||Date.now()<=c.I+3E5))return c.p;c=new Promise(function(e,g){b.onload=function(){return e(b)};b.onerror=function(h){b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});var d={I:0,p:c};c.catch(function(){return d.I=+new Date});Bc[a]=d;return c}function Dc(a){var b=void 0===b?null:b;a=yc(a);var c=document.createElement("script");c.src=a.toString();b&&(c.type=b);return Cc(a.toString(),c)};var Ec=!E||9<=Number(Bb),Fc=!E||9<=Number(Bb),Gc;
if(Gc=E){var Hc;if(Object.prototype.hasOwnProperty.call(yb,"9"))Hc=yb["9"];else{for(var Ic=0,Jc=Qa(String(xb)).split("."),Kc=Qa("9").split("."),Lc=Math.max(Jc.length,Kc.length),Mc=0;0==Ic&&Mc<Lc;Mc++){var Nc=Jc[Mc]||"",Oc=Kc[Mc]||"";do{var W=/(\d*)(\D*)(.*)/.exec(Nc)||["","","",""],X=/(\d*)(\D*)(.*)/.exec(Oc)||["","","",""];if(0==W[0].length&&0==X[0].length)break;Ic=Ra(0==W[1].length?0:parseInt(W[1],10),0==X[1].length?0:parseInt(X[1],10))||Ra(0==W[2].length,0==X[2].length)||Ra(W[2],X[2]);Nc=W[3];
Oc=X[3]}while(0==Ic)}Hc=yb["9"]=0<=Ic}Gc=!Hc}var Pc=Gc,Qc=function(){if(!n.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{n.addEventListener("test",wa,b),n.removeEventListener("test",wa,b)}catch(c){}return a}();function Rc(){this.u=this.u;this.b=this.b}f=Rc.prototype;f.u=!1;f.O=function(){return this.u};f.fa=Rc.prototype.O;f.D=function(){this.u||(this.u=!0,this.F())};f.$a=function(a){a=Aa(Sc,a);this.u?a():(this.b||(this.b=[]),this.b.push(a))};f.F=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Sc(a){a&&"function"==typeof a.D&&a.D()};function Tc(a,b){this.type=a;this.b=this.target=b;this.H=this.f=!1}Tc.prototype.g=function(){this.f=!0};Tc.prototype.c=function(){this.H=!0};function Y(a,b){Tc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.s=this.j=0;this.key="";this.h=this.i=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.G=null;this.J=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(pb){a:{try{mb(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.j=qb||void 0!==a.offsetX?a.offsetX:a.layerX,this.s=qb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.i=a.keyCode||0;this.key=a.key||"";this.h=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.J=rb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Uc[a.pointerType]||"";this.G=a.state;this.a=a;a.defaultPrevented&&this.c()}}Da(Y,Tc);var Vc=[1,4,2],Uc={2:"touch",3:"pen",4:"mouse"};
Y.prototype.ub=function(){return(Ec?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Vc[0]))&&!(rb&&this.ctrlKey)};Y.prototype.g=function(){Y.K.g.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Y.prototype.c=function(){Y.K.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Pc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Wc="closure_listenable_"+(1E6*Math.random()|0),Xc=0;function Yc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Xc;this.v=this.C=!1}function Zc(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function $c(a){this.src=a;this.a={};this.b=0}f=$c.prototype;f.wa=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};f.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var h=ad(a,b,d,e);-1<h?(b=a[h],c||(b.C=!1)):(b=new Yc(b,this.src,g,!!d,e),b.C=c,a.push(b));return b};
f.ya=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=ad(e,b,c,d);return-1<b?(Zc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};f.za=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Zc(d[e]);delete this.a[c];this.b--}return b};f.ha=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.xa=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Pa(this.a,function(g){for(var h=0;h<g.length;++h)if(!(c&&g[h].type!=d||e&&g[h].capture!=b))return!0;return!1})};function ad(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.v&&g.listener==b&&g.capture==!!c&&g.b==d)return e}return-1};var bd="closure_lm_"+(1E6*Math.random()|0),cd={},dd=0;function ed(a,b,c,d,e){if(d&&d.once)return fd(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)ed(a,b[g],c,d,e);return null}c=gd(c);return a&&a[Wc]?a.c(b,c,za(d)?!!d.capture:!!d,e):hd(a,b,c,!1,d,e)}
function hd(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=za(e)?!!e.capture:!!e,k=id(a);k||(a[bd]=k=new $c(a));c=k.add(b,c,d,h,g);if(c.a)return c;d=jd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Qc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(kd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");dd++;return c}
function jd(){var a=ld,b=Fc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function fd(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)fd(a,b[g],c,d,e);return null}c=gd(c);return a&&a[Wc]?a.f(b,c,za(d)?!!d.capture:!!d,e):hd(a,b,c,!0,d,e)}
function md(a){if("number"!==typeof a&&a&&!a.v){var b=a.src;if(b&&b[Wc])b.g(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(kd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);dd--;if(c=id(b)){d=a.type;if(d in c.a){var e=c.a[d],g=Ea(e,a),h;(h=0<=g)&&Array.prototype.splice.call(e,g,1);h&&(Zc(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[bd]=null)}else Zc(a)}}}
function kd(a){return a in cd?cd[a]:cd[a]="on"+a}function nd(a,b,c,d){var e=!0;if(a=id(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.v&&(g=od(g,d),e=e&&!1!==g)}return e}function od(a,b){var c=a.listener,d=a.b||a.src;a.C&&md(a);return c.call(d,b)}
function ld(a,b){if(a.v)return!0;if(!Fc){var c=b||va("window.event");b=new Y(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.f&&0<=e;e--){b.b=c[e];var g=nd(c[e],a,!0,b);d=d&&g}for(e=0;!b.f&&e<c.length;e++)b.b=c[e],g=nd(c[e],a,!1,b),d=d&&g}return d}return od(a,new Y(b,this))}
function id(a){a=a[bd];return a instanceof $c?a:null}var pd="__closure_events_fn_"+(1E9*Math.random()>>>0);function gd(a){if("function"==xa(a))return a;a[pd]||(a[pd]=function(b){return a.handleEvent(b)});return a[pd]};function qd(a){Rc.call(this);this.c=a;this.a={}}Da(qd,Rc);var rd=[];f=qd.prototype;f.Ra=function(a,b,c,d,e){return sd(this,a,b,c,d,e)};function sd(a,b,c,d,e,g){Array.isArray(c)||(c&&(rd[0]=c.toString()),c=rd);for(var h=0;h<c.length;h++){var k=ed(b,c[h],d||a.handleEvent,e||!1,g||a.c||a);if(!k)break;a.a[k.key]=k}return a}function td(a,b){ud(Z.b,a,"devsite-content-updated",b,void 0)}f.Qa=function(a,b,c,d,e){return ud(this,a,b,c,d,e)};
function ud(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)ud(a,b,c[h],d,e,g);else{b=fd(b,c,d||a.handleEvent,e,g||a.c||a);if(!b)return a;a.a[b.key]=b}return a}f.Sa=function(a,b,c,d){b.a(a,c,d,this.c||this,this);return this};f.Ta=function(a,b,c,d,e){b.a(a,c,d,e||this.c||this,this);return this};f.va=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function vd(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)vd(a,b,c[h],d,e,g);else d=d||a.handleEvent,e=za(e)?!!e.capture:!!e,g=g||a.c||a,d=gd(d),e=!!e,b&&b[Wc]?c=b.a(c,d,e,g):b?(b=id(b))?(c=b.a[c.toString()],b=-1,c&&(b=ad(c,d,e,g)),c=-1<b?c[b]:null):c=null:c=null,c&&(md(c),delete a.a[c.key])}f.vb=function(a,b,c,d,e){b.b(a,c,d,e||this.c||this,this);return this};function wd(a){Oa(a.a,function(b,c){this.a.hasOwnProperty(c)&&md(b)},a);a.a={}}f.F=function(){qd.K.F.call(this);wd(this)};
f.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function xd(){var a=this;if(va("__globalAppLoader"))return va("__globalAppLoader");this.c=null;this.h=!1;this.b=new qd;this.f=[];this.g=function(b){a.f.push(b)};try{this.a=ac()}catch(b){yd("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;Ca("__globalAppLoader",this)}xd.prototype.D=function(){wd(this.b)};
function zd(a){var b=[];b.push(Dc(L(a.a,5,"")+"/js/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(Dc(L(a.a,5,"")+"/js/polyfills.js"));return Promise.all(b)}
function Ad(){var a=Bd,b,c,d,e,g,h;return ua(new ta(new pa(function(k){switch(k.a){case 1:return E&&document.body.setAttribute("ie-"+parseInt(xb,10),""),k.c=2,l(k,zd(a),4);case 4:ma(k,3);break;case 2:b=na(k),yd("Failed to load Devsite App dependencies: "+b.message);case 3:c=new Promise(function(m){Ca("__devsiteAppReadyResolver",m)});Ca("__devsiteAppReadyPromise",c);Ca("DevsiteApp.whenReady",function(){return c});if(!K(a.a,12).length){k.o(5);break}k.c=6;return l(k,Promise.all(K(a.a,12).map(function(m){m=
yc(m);var q=document.createElement("link");q.setAttribute("rel","stylesheet");q.setAttribute("type","text/css");q.setAttribute("href",m.toString());return Cc(m.toString(),q)})),8);case 8:ma(k,5);break;case 6:d=na(k),yd("Failed to load Devsite App dependencies: "+d.message);case 5:return k.c=9,l(k,Dc(L(a.a,6,"")+(a.a.getLocale()&&"en"!=a.a.getLocale()?L(a.a,4,"").replace(/\.js$/,"__"+a.a.getLocale().toLowerCase().replace("-","_")+".js"):L(a.a,4,""))),11);case 11:ma(k,10);break;case 9:e=na(k);if("en"===
a.a.getLocale()){yd("Failed to load Devsite App binary: "+e.message);k.o(10);break}N(a.a,2,"en","");k.c=13;return l(k,Dc(L(a.a,6,"")+L(a.a,4,"")),15);case 15:ma(k,10);break;case 13:g=na(k),yd("Failed to load Devsite App binary: "+g.message);case 10:if(h=document,"complete"===h.readyState||"interactive"===h.readyState)k.o(0);else return l(k,new Promise(function(m){h.addEventListener("readystatechange",function(){"interactive"!==h.readyState&&"complete"!==h.readyState||m()})}),0)}})))}
function yd(a){throw new function(b){this.message=b;this.name="DevsiteAppLoaderException"}(void 0===a?"Devsite has failed to load.":a);};var Z=new xd;(function(){var a=document.querySelector("devsite-content");a&&(sd(Z.b,window,"message",Z.g,void 0),td(a,function(){vd(Z.b,window,"message",Z.g);for(var b=ha(Z.f),c=b.next();!c.done;c=b.next())window.dispatchEvent(c.value.a);Z.f=[]}))})();var Cd;var Bd=Z;"WeakMap"in window&&"performance"in window&&"now"in window.performance?(Bd.c||(Bd.c=Ad()),Cd=Bd.c):Cd=Promise.resolve();
Cd.then(function(){va("DevsiteAppInit")||yd("Failed to load Devsite App binary");M(Z.a,9)?DevsiteAppFrameboxInit(Z.a.N(),DevsiteAppAuthorizedElements):DevsiteAppInit(Z.a.N(),DevsiteAppAuthorizedElements,DevsiteAppCoreElements)});}).call(this);
