(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function l(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var ea;
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={N:!0},ia={};try{ia.__proto__=ha;fa=ia.N;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.u=b.prototype}
function la(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}l("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=la(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});
l("Object.setPrototypeOf",function(a){return a||ja});var ma=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();
l("Reflect.construct",function(){return ma});l("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==la(this,b,"includes").indexOf(b,c||0)}});var m=this||self;function na(){}function n(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function p(a){var b=n(a);return"array"==b||"object"==b&&"number"==typeof a.length}function q(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function oa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function r(a,b){function c(){}c.prototype=b.prototype;a.u=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.aa=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var pa;var qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},t=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ra=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function sa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function ta(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ua(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function wa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<va.length;f++)c=va[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function u(a,b){this.a=a===xa&&b||"";this.b=ya}g=u.prototype;g.s=!0;g.m=function(){return this.a.toString()};g.D=!0;g.i=function(){return 1};g.ba=function(a,b){var c=za(this).toString();c=Aa.exec(c);var d=c[3]||"";a=c[1]+Ba("?",c[2]||"",a)+Ba("#",d,b);return new u(xa,a)};function za(a){return a instanceof u&&a.constructor===u&&a.b===ya?a.a:"type_error:TrustedResourceUrl"}var Aa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ya={};
function Ba(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b}var xa={};var Ca=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Da(a,b){if(b)a=a.replace(Ea,"&amp;").replace(Fa,"&lt;").replace(Ga,"&gt;").replace(Ha,"&quot;").replace(Ia,"&#39;").replace(Ja,"&#0;");else{if(!Ka.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ea,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Fa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ga,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ha,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ia,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ja,"&#0;"))}return a}
var Ea=/&/g,Fa=/</g,Ga=/>/g,Ha=/"/g,Ia=/'/g,Ja=/\x00/g,Ka=/[\x00&<>"']/;function La(a,b){return a<b?-1:a>b?1:0};function v(a,b){this.a=a===Ma&&b||"";this.b=Na}v.prototype.s=!0;v.prototype.m=function(){return this.a.toString()};v.prototype.D=!0;v.prototype.i=function(){return 1};var Na={},Ma={};var w;a:{var Oa=m.navigator;if(Oa){var Pa=Oa.userAgent;if(Pa){w=Pa;break a}}w=""};function x(){this.a="";this.c=Qa;this.b=null}x.prototype.D=!0;x.prototype.i=function(){return this.b};x.prototype.s=!0;x.prototype.m=function(){return this.a.toString()};function y(a){return a instanceof x&&a.constructor===x&&a.c===Qa?a.a:"type_error:SafeHtml"}function z(a){if(a instanceof x)return a;var b="object"==typeof a,c=null;b&&a.D&&(c=a.i());return Ra(Da(b&&a.s?a.m():String(a)),c)}
function Sa(a){function b(f){Array.isArray(f)?t(f,b):(f=z(f),e.push(y(f).toString()),f=f.i(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=z(Ta),d=c.i(),e=[];t(a,b);return Ra(e.join(y(c).toString()),d)}function Ua(a){return Sa(Array.prototype.slice.call(arguments))}var Qa={};function Ra(a,b){return Va(a,b)}function Va(a,b){var c=new x;c.a=a;c.b=b;return c}var Wa=new x;Wa.a=m.trustedTypes&&m.trustedTypes.emptyHTML?m.trustedTypes.emptyHTML:"";Wa.b=0;var Ta=Wa,Xa=Va("<br>",0);var Ya=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=y(Ta);return!b.parentElement});function Za(a,b){if(Ya())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=y(b)};function A(a){return a=Da(a,void 0)};var B="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""};function C(){}C.prototype.a=function(){throw B;};C.prototype.j=function(){return this};function $a(a){if(a instanceof C)return a;if("function"==typeof a.j)return a.j(!1);if(p(a)){var b=0,c=new C;c.a=function(){for(;;){if(b>=a.length)throw B;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function ab(a,b){if(p(a))try{t(a,b,void 0)}catch(c){if(c!==B)throw c;}else{a=$a(a);try{for(;;)b.call(void 0,a.a(),void 0,a)}catch(c){if(c!==B)throw c;}}}function bb(a){if(p(a))return sa(a);a=$a(a);var b=[];ab(a,function(c){b.push(c)});return b};var D={},cb={},db={};function E(){throw Error("Do not instantiate directly");}E.prototype.A=null;E.prototype.toString=function(){return this.H};E.prototype.a=function(){if(this.f!==cb)throw Error("Sanitized content was not of kind URI.");return new v(Ma,this.toString())};function eb(){E.call(this)}r(eb,E);eb.prototype.f=D;function fb(a){fb[" "](a);return a}fb[" "]=na;function gb(a,b){var c=hb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var ib=-1!=w.indexOf("Opera"),F=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),jb=-1!=w.indexOf("Edge"),G=-1!=w.indexOf("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"))&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"))&&-1==w.indexOf("Edge"),H=-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"),kb=-1!=w.indexOf("Macintosh");function lb(){var a=m.document;return a?a.documentMode:void 0}var mb;
a:{var nb="",ob=function(){var a=w;if(G)return/rv:([^\);]+)(\)|;)/.exec(a);if(jb)return/Edge\/([\d\.]+)/.exec(a);if(F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(H)return/WebKit\/(\S+)/.exec(a);if(ib)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ob&&(nb=ob?ob[1]:"");if(F){var pb=lb();if(null!=pb&&pb>parseFloat(nb)){mb=String(pb);break a}}mb=nb}var qb=mb,hb={};
function J(a){return gb(a,function(){for(var b=0,c=Ca(String(qb)).split("."),d=Ca(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=La(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||La(0==h[2].length,0==k[2].length)||La(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var rb;
if(m.document&&F){var sb=lb();rb=sb?sb:parseInt(qb,10)||void 0}else rb=void 0;var K=rb;function tb(a){if(null!=a)switch(a.A){case 1:return 1;case -1:return-1;case 0:return 0}return null}function ub(a){return null!=a&&a.f===D?a:a instanceof x?L(y(a).toString(),a.i()):L(A(String(String(a))),tb(a))}var L=function(a){function b(c){this.H=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.A=d);return c}}(eb);function M(a){return null!=a&&a.f===D?String(String(a.H).replace(vb,"").replace(wb,"&lt;")).replace(xb,yb):A(String(a))}
function zb(a){null!=a&&a.f===cb||null!=a&&a.f===db?a=String(a).replace(N,Ab):a instanceof v?(a=a instanceof v&&a.constructor===v&&a.b===Na?a.a:"type_error:SafeUrl",a=String(a).replace(N,Ab)):a instanceof u?a=String(za(a).toString()).replace(N,Ab):(a=String(a),a=Bb.test(a)?a.replace(N,Ab):"about:invalid#zSoyz");return a}
var Cb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function yb(a){return Cb[a]}
var Db={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function Ab(a){return Db[a]}var xb=/[\x00\x22\x27\x3c\x3e]/g,N=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Bb=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,vb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,wb=/</g;var Eb=!F||9<=Number(K),Fb=!G&&!F||F&&9<=Number(K)||G&&J("1.9.1"),Gb=F&&!J("9"),Hb=F||ib||H;function O(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}g=O.prototype;g.hb=function(){return new O(this.x,this.y)};g.ea=function(a){return a instanceof O&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.jb=function(a,b){a instanceof O?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),"number"===typeof b&&(this.y+=b));return this};g.ib=function(a,b){this.x*=a;this.y*="number"===typeof b?b:a;return this};g.Fb=function(a,b){a=a*Math.PI/180;b=b||new O(0,0);var c=this.x,d=this.y,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.y)*a+b.x;this.y=(c-b.x)*a+(d-b.y)*e+b.y};function Ib(a,b){this.width=a;this.height=b}g=Ib.prototype;g.kb=function(){return new Ib(this.width,this.height)};g.Ea=function(){return Math.max(this.width,this.height)};g.Ra=function(){return Math.min(this.width,this.height)};g.Bb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.rb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ia=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Jb(a,b){a.width*=b;a.height*=b;return a}g.Hb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Jb(this,a)};
g.Ib=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Jb(this,a)};function Kb(a){return a?new P(Q(a)):pa||(pa=new P)}function Lb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Mb(document,"*",a,b);return d||null}
function Nb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=qa(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Mb(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Nb(a,b,c,d)[0]||null}function Ob(a,b){ta(b,function(c,d){c&&"object"==typeof c&&c.s&&(c=c.m());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Pb.hasOwnProperty(d)?a.setAttribute(Pb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Pb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Qb(a){a=a.document;a=Rb(a)?a.documentElement:a.body;return new Ib(a.clientWidth,a.clientHeight)}function Sb(a){return a.scrollingElement?a.scrollingElement:!H&&Rb(a)?a.documentElement:a.body||a.documentElement}
function Tb(a){return a.parentWindow||a.defaultView}function Ub(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];p(f)&&!Vb(f)?t(Wb(f)?sa(f):f,e):e(f)}}function R(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function Rb(a){return"CSS1Compat"==a.compatMode}function Xb(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function Yb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Zb(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Vb(a){return q(a)&&0<a.nodeType}function $b(a){return q(a)&&1==a.nodeType}function ac(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function cc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return dc(b,a)}function dc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function ec(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Xb(a),a.appendChild(Q(a).createTextNode(String(b)))}function fc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||fc(a,b,c,d))return!0;a=a.nextSibling}return!1}var gc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},hc={IMG:" ",BR:"\n"};
function ic(a){return jc(a)&&kc(a)}function jc(a){return F&&!J("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function kc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function lc(a){if(Gb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];mc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Gb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function mc(a,b,c){if(!(a.nodeName in gc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in hc)b.push(hc[a.nodeName]);else for(a=a.firstChild;a;)mc(a,b,c),a=a.nextSibling}function Wb(a){if(a&&"number"==typeof a.length){if(q(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==n(a))return"function"==typeof a.item}return!1}
function nc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return oc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=qa(f.className.split(/\s+/),c));return h},!0,d)}function oc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function P(a){this.a=a||m.document||document}g=P.prototype;g.va=Kb;g.Jb=function(a){this.a=a};g.ra=function(){return this.a};
g.R=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Pa=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Y=P.prototype.R;g.Ya=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.S=function(a,b,c){return Nb(this.a,a,b,c)};g.xa=function(a,b,c){return Mb(this.a,a,b,c)};g.ya=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Nb(document,"*",a,b)};g.wa=function(a,b){return Lb(a,b||this.a)};
g.Qa=function(a,b){return Lb(a,b||this.a)};g.Z=P.prototype.S;g.Lb=Ob;g.Ta=function(a){return Qb(a||Tb(this.a)||window)};g.sa=function(){var a=Tb(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Qb(a).height,Rb(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.O=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Eb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',A(h.name),'"');if(h.type){f.push(' type="',A(h.type),'"');var k={};wa(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=R(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):Ob(f,h));2<e.length&&Ub(d,f,e,2);return f};g.$=P.prototype.O;g.Xa=function(a){return this.a.createTextNode(String(a))};
g.da=function(a,b,c){var d=this.a;c=!!c;for(var e=R(d,"TABLE"),f=e.appendChild(R(d,"TBODY")),h=0;h<a;h++){for(var k=R(d,"TR"),I=0;I<b;I++){var bc=R(d,"TD");c&&ec(bc,"\u00a0");k.appendChild(bc)}f.appendChild(k)}return e};g.Gb=function(a){var b=this.a;var c=R(b,"DIV");F?(a=Ua(Xa,a),Za(c,a),c.removeChild(c.firstChild)):Za(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.pb=function(){return Rb(this.a)};
g.ua=function(){return Sb(this.a)};g.ta=function(){var a=this.a,b=Sb(a);a=Tb(a);return F&&J("10")&&a.pageYOffset!=b.scrollTop?new O(b.scrollLeft,b.scrollTop):new O(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ka=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Va=function(a,b){a.appendChild(b)};g.Ua=function(a,b){Ub(Q(a),a,arguments,1)};g.Wa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Eb=Xb;g.nb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.mb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.lb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Za=Yb;g.$a=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ja=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Yb(a)}};
g.pa=function(a){return Fb&&void 0!=a.children?a.children:ra(a.childNodes,function(b){return 1==b.nodeType})};g.za=function(a){return void 0!==a.firstElementChild?a.firstElementChild:Zb(a.firstChild,!0)};g.Ca=function(a){return void 0!==a.lastElementChild?a.lastElementChild:Zb(a.lastChild,!1)};g.Fa=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:Zb(a.nextSibling,!0)};g.Na=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:Zb(a.previousSibling,!1)};
g.Ga=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Oa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.ub=Vb;g.qb=$b;g.wb=function(a){return q(a)&&a.window==a};g.Ma=function(a){var b;if(Hb&&!(F&&J("9")&&!J("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return $b(b)?b:null};
g.contains=ac;
g.ca=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(F&&!(9<=Number(K))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?dc(a,b):!c&&ac(e,b)?-1*cc(a,b):!d&&ac(f,a)?cc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=Q(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,a)};g.fa=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.La=Q;g.Aa=function(a){return a.contentDocument||a.contentWindow.document};
g.Ba=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Tb(c):window}else d=null;b=d}return b}catch(e){}return null};g.Mb=ec;g.Ka=function(a){if("outerHTML"in a)return a.outerHTML;var b=R(Q(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ga=function(a,b){var c=[];return fc(a,b,c,!0)?c[0]:void 0};g.ha=function(a,b){var c=[];fc(a,b,c,!1);return c};g.tb=ic;g.Kb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.sb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!jc(a)||kc(a)):ic(a))&&F){var c;"function"!=n(a.getBoundingClientRect)||F&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Sa=lc;g.Ia=function(a){return lc(a).length};
g.Ja=function(a,b){b=b||Q(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(lc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ha=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in gc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in hc)d+=hc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);q(c)&&(c.Db=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.vb=Wb;g.na=nc;g.ma=function(a,b,c){return nc(a,null,b,c)};g.la=oc;g.oa=function(a){return a.getContext("2d")};function S(a,b){b=a(b||pc,void 0);a=Kb();a=R(a.a,"DIV");if(q(b))if(b instanceof E){if(b.f!==D)throw Error("Sanitized content was not of kind HTML.");b=Va(b.toString(),b.A||null)}else b=z("zSoyz");else b=z(String(b));Za(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var pc={};function qc(){return L('<div class="devsite-snackbar-snack" type="loading"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Loading</div><div class="devsite-snackbar-action"><devsite-spinner single-color="#ffffff"></devsite-spinner></div></div></div>')}
function rc(){return L('<div class="devsite-snackbar-snack" type="refresh"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">A new version is available</div><button class="devsite-snackbar-action">Refresh</button></div></div>')}
function sc(){return L('<div class="devsite-snackbar-snack" type="error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Something went wrong. Please try again.</div><button class="devsite-snackbar-action">Retry</button></div></div>')}function tc(){return L('<div class="devsite-snackbar-snack" type="copied-to-clipboard"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Copied to clipboard</div></div></div>')}
function uc(a){a=a||{};a=a.F;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">This site uses cookies from Google to deliver its services and to analyze traffic.</div><a href="'+((a?M(zb(a)):"//policies.google.com/technologies/cookies")+'" class="devsite-snackbar-link button">');return L(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')}
function vc(){return L('<div class="devsite-snackbar-snack" type="support-attachment-error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Unsupported file type.</div><button class="devsite-snackbar-action">OK</button></div></div>')}
function wc(a){var b=a.message,c=a.link,d=a.V;a='<div class="devsite-snackbar-snack" type="'+M(a.X)+'"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+ub(b)+'</div><button class="devsite-snackbar-action">';a=a+'No, thanks</button><a href="'+(M(zb(c))+'" class="devsite-snackbar-link button" target="_blank">');a=d?a+ub(d):a+"OK";return L(a+"</a></div></div>")}
function xc(a){var b=a.W;a='<div class="devsite-snackbar-snack" type="custom"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+ub(a.message)+"</div>";b&&(a+='<button class="devsite-snackbar-action">OK</button>');return L(a+"</div></div>")};var yc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(yc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function T(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ka(T,HTMLElement);T.prototype.M=function(){console.warn(this.tagName,"has not implemented update")};T.prototype.I=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
T.prototype.L=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function zc(){this.g=this.g;this.b=this.b}g=zc.prototype;g.g=!1;g.U=function(){return this.g};g.qa=zc.prototype.U;g.G=function(){this.g||(this.g=!0,this.B())};g.Cb=function(a){a=oa(Ac,a);this.g?a():(this.b||(this.b=[]),this.b.push(a))};g.B=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Ac(a){a&&"function"==typeof a.G&&a.G()};var Bc=!F||9<=Number(K),Cc=!F||9<=Number(K),Dc=F&&!J("9"),Ec=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",na,b),m.removeEventListener("test",na,b)}catch(c){}return a}();function Fc(a,b){this.type=a;this.b=this.target=b;this.L=this.h=!1}Fc.prototype.stopPropagation=function(){this.h=!0};Fc.prototype.c=function(){this.L=!0};var Gc;Gc=H?"webkitTransitionEnd":ib?"otransitionend":"transitionend";function U(a,b){Fc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.J=this.I=0;this.key="";this.o=this.C=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.K=null;this.M=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(G){a:{try{fb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.I=H||void 0!==a.offsetX?a.offsetX:a.layerX,this.J=H||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.C=a.keyCode||0;this.key=a.key||"";this.o=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.M=kb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Hc[a.pointerType]||"";this.K=a.state;this.a=a;a.defaultPrevented&&this.c()}}r(U,Fc);var Ic=[1,4,2],Hc={2:"touch",3:"pen",4:"mouse"};
U.prototype.Nb=function(){return(Bc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Ic[0]))&&!(kb&&this.ctrlKey)};U.prototype.stopPropagation=function(){U.u.stopPropagation.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};U.prototype.c=function(){U.u.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Dc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Jc="closure_listenable_"+(1E6*Math.random()|0),Kc=0;function Lc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Kc;this.l=this.v=!1}function Mc(a){a.l=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Nc(a){this.src=a;this.a={};this.b=0}g=Nc.prototype;g.cb=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Oc(a,b,d,e);-1<h?(b=a[h],c||(b.v=!1)):(b=new Lc(b,this.src,f,!!d,e),b.v=c,a.push(b));return b};
g.fb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Oc(e,b,c,d);return-1<b?(Mc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.gb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Mc(d[e]);delete this.a[c];this.b--}return b};g.Da=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.eb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return ua(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function Oc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.l&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Pc="closure_lm_"+(1E6*Math.random()|0),Qc={},Rc=0;function Sc(a,b,c,d,e){if(d&&d.once)return V(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Sc(a,b[f],c,d,e);return null}c=Tc(c);return a&&a[Jc]?a.J(b,c,q(d)?!!d.capture:!!d,e):Uc(a,b,c,!1,d,e)}
function Uc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=q(e)?!!e.capture:!!e,k=Vc(a);k||(a[Pc]=k=new Nc(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Wc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Ec||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Xc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Rc++;return c}
function Wc(){var a=Yc,b=Cc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function V(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)V(a,b[f],c,d,e);return null}c=Tc(c);return a&&a[Jc]?a.K(b,c,q(d)?!!d.capture:!!d,e):Uc(a,b,c,!0,d,e)}
function Zc(a){if("number"!==typeof a&&a&&!a.l){var b=a.src;if(b&&b[Jc])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Xc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Rc--;if(c=Vc(b)){d=a.type;if(d in c.a){var e=c.a[d],f=qa(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(Mc(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Pc]=null)}else Mc(a)}}}
function Xc(a){return a in Qc?Qc[a]:Qc[a]="on"+a}function $c(a,b,c,d){var e=!0;if(a=Vc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.l&&(f=ad(f,d),e=e&&!1!==f)}return e}function ad(a,b){var c=a.listener,d=a.b||a.src;a.v&&Zc(a);return c.call(d,b)}
function Yc(a,b){if(a.l)return!0;if(!Cc){if(!b)a:{b=["window","event"];for(var c=m,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new U(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.h&&0<=e;e--){b.b=d[e];var f=$c(d[e],a,!0,b);c=c&&f}for(e=0;!b.h&&e<d.length;e++)b.b=d[e],f=$c(d[e],a,!1,b),c=
c&&f}return c}return ad(a,new U(b,this))}function Vc(a){a=a[Pc];return a instanceof Nc?a:null}var bd="__closure_events_fn_"+(1E9*Math.random()>>>0);function Tc(a){if("function"==n(a))return a;a[bd]||(a[bd]=function(b){return a.handleEvent(b)});return a[bd]};function W(a){zc.call(this);this.c=a;this.a={}}r(W,zc);var cd=[];function dd(a,b,c,d){ed(a,b,c,d,void 0)}g=W.prototype;g.yb=function(a,b,c,d,e){return ed(this,a,b,c,d,e)};function ed(a,b,c,d,e,f){Array.isArray(c)||(c&&(cd[0]=c.toString()),c=cd);for(var h=0;h<c.length;h++){var k=Sc(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.bb=function(a,b,c,d){return fd(this,a,b,c,d)};g.xb=function(a,b,c,d,e){return fd(this,a,b,c,d,e)};
function fd(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)fd(a,b,c[h],d,e,f);else{b=V(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.zb=function(a,b,c,d){b.a(a,c,d,this.c||this,this);return this};g.Ab=function(a,b,c,d,e){b.a(a,c,d,e||this.c||this,this);return this};g.ab=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};g.Ob=function(a,b,c,d,e){b.b(a,c,d,e||this.c||this,this);return this};
function gd(a){ta(a.a,function(b,c){this.a.hasOwnProperty(c)&&Zc(b)},a);a.a={}}g.B=function(){W.u.B.call(this);gd(this)};g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function hd(){};function id(){}r(id,hd);id.prototype.P=function(){var a=0;ab(this.j(!0),function(){a++});return a};id.prototype.T=function(){var a=bb(this.j(!0)),b=this;t(a,function(c){b.a.removeItem(c)})};function jd(a){this.a=a}r(jd,id);g=jd.prototype;g.ob=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};g.get=function(a){a=this.a.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};g.P=function(){return this.a.length};
g.j=function(a){var b=0,c=this.a,d=new C;d.a=function(){if(b>=c.length)throw B;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};return d};g.T=function(){this.a.clear()};g.key=function(a){return this.a.key(a)};function kd(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}r(kd,jd);var ld={},md=(ld[0]=uc,ld[1]=uc,ld[2]=function(a){a=a||{};a=a.F;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Google uses cookies to deliver its services, to personalize ads, and to analyze traffic. You can adjust your privacy controls anytime in your <a href="//myaccount.google.com/intro/data-and-personalization">Google settings</a>.</div><a href="'+((a?M(zb(a)):"//policies.google.com/technologies/cookies")+
'" class="devsite-snackbar-link button">');return L(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')},ld);function X(){var a=T.call(this)||this;a.h=-1;a.o=new W(a);a.b=new kd;a.a=[];return a}ka(X,T);X.prototype.connectedCallback=function(){dd(this.o,document.body,"devsite-show-custom-snackbar-msg",this.C)};X.prototype.disconnectedCallback=function(){gd(this.o)};
X.prototype.C=function(a){var b=this;this.setAttribute("type","custom");if(a=a.a.detail){var c=!!a.showClose,d=S(xc,{message:a.msg,W:c});c&&V(d.querySelector(".devsite-snackbar-action"),"click",function(){Y(b,d)});Z(this,d,!c)}};
X.prototype.attributeChangedCallback=function(a,b,c){if("type"==a){switch(b){case "loading":Y(this,this.querySelector('*[type^="loading"]'));break;case "refresh":Y(this,this.querySelector('*[type^="refresh"]'));break;case "error":Y(this,this.querySelector('*[type^="error"]'));break;case "copied-to-clipboard":Y(this,this.querySelector('*[type^="copied-to-clipboard"]'));break;case "cookie-notification":nd(this);break;case "support-attachment-error":od(this);break;case "custom":Y(this,this.querySelector('*[type^="custom"]'))}null!=
b&&b.startsWith("notification-")&&pd(this);c&&(c.includes(",")&&(this.a=c.split(","),c=this.a.shift()),qd(this,c))}};function qd(a,b){switch(b){case "loading":if(!a.querySelector('*[type^="loading"]')){var c=S(qc);Z(a,c)}break;case "refresh":rd(a);break;case "error":sd(a);break;case "copied-to-clipboard":c=S(tc);Z(a,c,!0);break;case "cookie-notification":td(a);break;case "support-attachment-error":ud(a)}b.startsWith("notification-")&&vd(a,b)}
function Z(a,b,c){c=void 0===c?!1:c;a.appendChild(b);window.requestAnimationFrame(function(){wd(a,b,c)})}function wd(a,b,c){c=void 0===c?!1:c;window.clearTimeout(a.h);a.c?Y(a,a.c,b,c):(a.c=b,window.requestAnimationFrame(function(){b.setAttribute("show","")}),c&&(a.h=window.setTimeout(function(){a.removeAttribute("type");Y(a,b)},5E3)))}function rd(a){var b=S(rc);Sc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}
function sd(a){var b=S(sc);Sc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}function Y(a,b,c,d){c=void 0===c?null:c;d=void 0===d?!1:d;b&&(V(b,Gc,function(){Yb(b);a.c=null;if(c)wd(a,c,d);else{var e=a.a.length?a.a.shift():null;null!==e&&qd(a,e)}}),b.removeAttribute("show"))}
function td(a){if(a.b.get("devsite-eu-cookie")){var b=a.a.length?a.a.shift():null;null!==b&&qd(a,b)}else{b=uc;a.hasAttribute("data-cookie-notice")&&(b=parseInt(a.getAttribute("data-cookie-notice"),10),b=md[b]);if(a.hasAttribute("data-cookie-policy")){var c=a.getAttribute("data-cookie-policy");b=S(b,{F:c})}else b=S(b);V(b.querySelector(".devsite-snackbar-action"),"click",function(){a.b.set("devsite-eu-cookie","1");nd(a)});Z(a,b)}}
function nd(a){Y(a,a.querySelector('*[type^="cookie-notification"]'))}function ud(a){var b=S(vc);Z(a,b);V(b.querySelector(".devsite-snackbar-action"),"click",function(){od(a)})}function od(a){Y(a,a.querySelector('*[type^="support-attachment-error"]'))}
function vd(a,b){var c=a.getAttribute(b+"-message"),d=a.getAttribute(b+"-link"),e=a.getAttribute(b+"-link-txt"),f=a.hasAttribute(b+"-store-key");if(c&&d){var h="devsite-notification"+d;if(!f||!a.b.get(h)){b=S(wc,{X:b,message:c,link:d,V:e});Z(a,b);var k=new W(b);dd(k,b,"click",function(I){I.stopPropagation();if(I.target.classList.contains("devsite-snackbar-link")||I.target.classList.contains("devsite-snackbar-action"))f&&a.b.set(h,"1"),pd(a),gd(k)})}}}
function pd(a){Y(a,a.querySelector('*[type^="notification"]'))}da.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["type"]}}});X.prototype.attributeChangedCallback=X.prototype.attributeChangedCallback;X.prototype.disconnectedCallback=X.prototype.disconnectedCallback;X.prototype.connectedCallback=X.prototype.connectedCallback;try{window.customElements.define("devsite-snackbar",X)}catch(a){console.warn("devsite.app.customElement.DevsiteSnackBar",a)};}).call(this);
