(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function q(a,b){if(b){var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={K:!0},ja={};try{ja.__proto__=ia;ha=ja.K;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.v=b.prototype}
q("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,f){this.a=e;p(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
q("Object.setPrototypeOf",function(a){return a||ka});function r(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var na=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ca(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();q("Reflect.construct",function(){return na});
q("WeakMap",function(a){function b(l){this.a=(h+=Math.random()+1).toString();if(l){l=ba(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!r(l,k)){var m=new c;p(l,k,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof c)return n;e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,
3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(G){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!r(l,k))throw Error("WeakMap key fail: "+l);l[k][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&r(l,k)?l[k][this.a]:void 0};b.prototype.has=function(l){return d(l)&&r(l,k)&&r(l[k],this.a)};
b.prototype.delete=function(l){return d(l)&&r(l,k)&&r(l[k],this.a)?delete l[k][this.a]:!1};return b});
q("Map",function(a){function b(){var h={};return h.i=h.next=h.head=h}function c(h,l){var m=h.a;return ma(function(){if(m){for(;m.head!=h.a;)m=m.i;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(h,l){var m=l&&typeof l;"object"==m||"function"==m?f.has(l)?m=f.get(l):(m=""+ ++k,f.set(l,m)):m="p_"+l;var n=h.b[m];if(n&&r(h.b,m))for(h=0;h<n.length;h++){var G=n[h];if(l!==l&&G.key!==G.key||l===G.key)return{id:m,list:n,index:h,f:G}}return{id:m,list:n,
index:-1,f:void 0}}function e(h){this.b={};this.a=b();this.size=0;if(h){h=ba(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(ba([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(G){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.b[m.id]=[]);m.f?m.f.value=l:(m.f={next:this.a,i:this.a.i,head:this.a,key:h,value:l},m.list.push(m.f),this.a.i.next=m.f,this.a.i=m.f,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.f&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.b[h.id],h.f.i.next=h.f.next,h.f.next.i=h.f.i,h.f.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.i=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).f};e.prototype.get=function(h){return(h=d(this,h).f)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,
h.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});var t=this||self;function oa(){}
function pa(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function qa(a){var b=pa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"function"==pa(a)}function v(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ra(a,b,c){return a.call.apply(a.bind,arguments)}
function sa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function w(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?w=ra:w=sa;return w.apply(null,arguments)}
function ta(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var ua=Date.now||function(){return+new Date};function x(a,b){function c(){}c.prototype=b.prototype;a.v=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(d,e,f){for(var k=Array(arguments.length-2),h=2;h<arguments.length;h++)k[h-2]=arguments[h];return b.prototype[e].apply(d,k)}};var va;var wa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},xa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},ya=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,k=0;k<c;k++)if(k in f){var h=f[k];b.call(void 0,h,k,a)&&(d[e++]=h)}return d};function za(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Aa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var Ba="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ca(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ba.length;f++)c=Ba[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Da=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ea(a,b){if(b)a=a.replace(Fa,"&amp;").replace(Ga,"&lt;").replace(Ha,"&gt;").replace(Ia,"&quot;").replace(Ja,"&#39;").replace(Ka,"&#0;");else{if(!La.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Fa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ga,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ha,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ia,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ja,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ka,"&#0;"))}return a}
var Fa=/&/g,Ga=/</g,Ha=/>/g,Ia=/"/g,Ja=/'/g,Ka=/\x00/g,La=/[\x00&<>"']/;function Ma(a,b){return a<b?-1:a>b?1:0};function y(a){this.b=Na===Na&&a||"";this.c=Oa}y.prototype.G=!0;y.prototype.F=function(){return this.b.toString()};y.prototype.J=!0;y.prototype.a=function(){return 1};var Oa={},Na={};var z;a:{var Pa=t.navigator;if(Pa){var Qa=Pa.userAgent;if(Qa){z=Qa;break a}}z=""};function A(){this.b="";this.g=Ra;this.c=null}A.prototype.J=!0;A.prototype.a=function(){return this.c};A.prototype.G=!0;A.prototype.F=function(){return this.b.toString()};function B(a){return a instanceof A&&a.constructor===A&&a.g===Ra?a.b:"type_error:SafeHtml"}function C(a){if(a instanceof A)return a;var b="object"==typeof a,c=null;b&&a.J&&(c=a.a());return Sa(Ea(b&&a.G?a.F():String(a)),c)}
function Ta(a){function b(f){Array.isArray(f)?xa(f,b):(f=C(f),e.push(B(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=C(Ua),d=c.a(),e=[];xa(a,b);return Sa(e.join(B(c).toString()),d)}function Va(a){return Ta(Array.prototype.slice.call(arguments))}var Ra={};function Sa(a,b){return Wa(a,b)}function Wa(a,b){var c=new A;c.b=a;c.c=b;return c}var Xa=new A;Xa.b=t.trustedTypes&&t.trustedTypes.emptyHTML?t.trustedTypes.emptyHTML:"";Xa.c=0;var Ua=Xa,Ya=Wa("<br>",0);var Za=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=B(Ua);return!b.parentElement});function $a(a,b){if(Za())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=B(b)};function ab(a){return a=Ea(a,void 0)};var bb={},cb={};function D(){throw Error("Do not instantiate directly");}D.prototype.C=null;D.prototype.b=function(){return this.a};D.prototype.toString=function(){return this.a};D.prototype.c=function(){if(this.D!==cb)throw Error("Sanitized content was not of kind URI.");return new y(this.toString())};function db(){D.call(this)}x(db,D);db.prototype.D=bb;function eb(a){eb[" "](a);return a}eb[" "]=oa;function fb(a,b){var c=gb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var hb=-1!=z.indexOf("Opera"),E=-1!=z.indexOf("Trident")||-1!=z.indexOf("MSIE"),ib=-1!=z.indexOf("Edge"),F=-1!=z.indexOf("Gecko")&&!(-1!=z.toLowerCase().indexOf("webkit")&&-1==z.indexOf("Edge"))&&!(-1!=z.indexOf("Trident")||-1!=z.indexOf("MSIE"))&&-1==z.indexOf("Edge"),H=-1!=z.toLowerCase().indexOf("webkit")&&-1==z.indexOf("Edge"),jb=-1!=z.indexOf("Macintosh");function kb(){var a=t.document;return a?a.documentMode:void 0}var lb;
a:{var mb="",nb=function(){var a=z;if(F)return/rv:([^\);]+)(\)|;)/.exec(a);if(ib)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(H)return/WebKit\/(\S+)/.exec(a);if(hb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();nb&&(mb=nb?nb[1]:"");if(E){var ob=kb();if(null!=ob&&ob>parseFloat(mb)){lb=String(ob);break a}}lb=mb}var pb=lb,gb={};
function I(a){return fb(a,function(){for(var b=0,c=Da(String(pb)).split("."),d=Da(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var k=c[f]||"",h=d[f]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==h[0].length)break;b=Ma(0==k[1].length?0:parseInt(k[1],10),0==h[1].length?0:parseInt(h[1],10))||Ma(0==k[2].length,0==h[2].length)||Ma(k[2],h[2]);k=k[3];h=h[3]}while(0==b)}return 0<=b})}var qb;
if(t.document&&E){var rb=kb();qb=rb?rb:parseInt(pb,10)||void 0}else qb=void 0;var J=qb;function sb(a){if(null!=a)switch(a.C){case 1:return 1;case -1:return-1;case 0:return 0}return null}var tb=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.C=d);return c}}(db);var ub=!E||9<=Number(J),vb=!F&&!E||E&&9<=Number(J)||F&&I("1.9.1"),wb=E&&!I("9"),xb=E||hb||H;function K(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}g=K.prototype;g.Za=function(){return new K(this.x,this.y)};g.$=function(a){return a instanceof K&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.ab=function(a,b){a instanceof K?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),"number"===typeof b&&(this.y+=b));return this};g.$a=function(a,b){this.x*=a;this.y*="number"===typeof b?b:a;return this};g.vb=function(a,b){a=a*Math.PI/180;b=b||new K(0,0);var c=this.x,d=this.y,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.y)*a+b.x;this.y=(c-b.x)*a+(d-b.y)*e+b.y};function L(a,b){this.width=a;this.height=b}g=L.prototype;g.bb=function(){return new L(this.width,this.height)};g.xa=function(){return Math.max(this.width,this.height)};g.Ka=function(){return Math.min(this.width,this.height)};g.rb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.hb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.da=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function yb(a,b){a.width*=b;a.height*=b;return a}g.xb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return yb(this,a)};
g.yb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return yb(this,a)};function M(a){return a?new N(O(a)):va||(va=new N)}function zb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Ab(document,"*",a,b);return d||null}
function Bb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,k;k=b[f];f++)e==k.nodeName&&(a[d++]=k);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;k=b[f];f++){e=k.className;var h;if(h="function"==typeof e.split)h=0<=wa(e.split(/\s+/),c);h&&(a[d++]=k)}a.length=d;return a}return b}
function Ab(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Bb(a,b,c,d)[0]||null}function Cb(a,b){Aa(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.F());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Db.hasOwnProperty(d)?a.setAttribute(Db[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Db={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Eb(a){a=a.document;a=P(a)?a.documentElement:a.body;return new L(a.clientWidth,a.clientHeight)}function Fb(a){return a.scrollingElement?a.scrollingElement:!H&&P(a)?a.documentElement:a.body||a.documentElement}
function Q(a){return a.parentWindow||a.defaultView}function Gb(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];qa(f)&&!Hb(f)?xa(Ib(f)?za(f):f,e):e(f)}}function R(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function P(a){return"CSS1Compat"==a.compatMode}function S(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function T(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function U(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Hb(a){return v(a)&&0<a.nodeType}function Jb(a){return v(a)&&1==a.nodeType}function Kb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Lb(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Mb(b,a)}function Mb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function O(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Nb(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else S(a),a.appendChild(O(a).createTextNode(String(b)))}function Ob(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Ob(a,b,c,d))return!0;a=a.nextSibling}return!1}var Pb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Qb={IMG:" ",BR:"\n"};
function Rb(a){return Sb(a)&&Tb(a)}function Sb(a){return E&&!I("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function Tb(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function Ub(a){if(wb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Vb(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");wb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Vb(a,b,c){if(!(a.nodeName in Pb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Qb)b.push(Qb[a.nodeName]);else for(a=a.firstChild;a;)Vb(a,b,c),a=a.nextSibling}function Ib(a){if(a&&"number"==typeof a.length){if(v(a))return"function"==typeof a.item||"string"==typeof a.item;if(u(a))return"function"==typeof a.item}return!1}
function Wb(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Xb(a,function(f){var k;(k=!e||f.nodeName==e)&&!(k=!c)&&(k="string"===typeof f.className)&&(k=0<=wa(f.className.split(/\s+/),c));return k},!0,d)}function Xb(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function N(a){this.a=a||t.document||document}g=N.prototype;g.pa=M;g.zb=function(a){this.a=a};g.ma=function(){return this.a};
g.M=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Ia=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.U=N.prototype.M;g.Ua=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.N=function(a,b,c){return Bb(this.a,a,b,c)};g.ra=function(a,b,c){return Ab(this.a,a,b,c)};g.sa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Bb(document,"*",a,b)};g.qa=function(a,b){return zb(a,b||this.a)};
g.Ja=function(a,b){return zb(a,b||this.a)};g.V=N.prototype.N;g.Bb=Cb;g.Ma=function(a){return Eb(a||Q(this.a)||window)};g.na=function(){var a=Q(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Eb(a).height,P(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.L=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),k=e[1];if(!ub&&k&&(k.name||k.type)){f=["<",f];k.name&&f.push(' name="',ab(k.name),'"');if(k.type){f.push(' type="',ab(k.type),'"');var h={};Ca(h,k);delete h.type;k=h}f.push(">");f=f.join("")}f=R(d,f);k&&("string"===typeof k?f.className=k:Array.isArray(k)?f.className=k.join(" "):Cb(f,k));2<e.length&&Gb(d,f,e,2);return f};g.W=N.prototype.L;g.Ta=function(a){return this.a.createTextNode(String(a))};
g.Z=function(a,b,c){var d=this.a;c=!!c;for(var e=R(d,"TABLE"),f=e.appendChild(R(d,"TBODY")),k=0;k<a;k++){for(var h=R(d,"TR"),l=0;l<b;l++){var m=R(d,"TD");c&&Nb(m,"\u00a0");h.appendChild(m)}f.appendChild(h)}return e};g.wb=function(a){var b=this.a;var c=R(b,"DIV");E?(a=Va(Ya,a),$a(c,a),c.removeChild(c.firstChild)):$a(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.oa=function(){return Fb(this.a)};
g.fa=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Qa=function(a,b){a.appendChild(b)};g.Pa=function(a,b){Gb(O(a),a,arguments,1)};g.Ra=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.ub=S;g.fb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.eb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.cb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Va=T;g.Wa=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ea=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return T(a)}};
g.ka=function(a){return vb&&void 0!=a.children?a.children:ya(a.childNodes,function(b){return 1==b.nodeType})};g.ta=function(a){return void 0!==a.firstElementChild?a.firstElementChild:U(a.firstChild,!0)};g.wa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:U(a.lastChild,!1)};g.ya=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:U(a.nextSibling,!0)};g.Ga=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:U(a.previousSibling,!1)};
g.za=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ha=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.kb=Hb;g.gb=Jb;g.mb=function(a){return v(a)&&a.window==a};g.Fa=function(a){var b;if(xb&&!(E&&I("9")&&!I("10")&&t.SVGElement&&a instanceof t.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return Jb(b)?b:null};
g.Sa=Kb;
g.Y=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(E&&!(9<=Number(J))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Mb(a,b):!c&&Kb(e,b)?-1*Lb(a,b):!d&&Kb(f,a)?Lb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=O(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(t.Range.START_TO_END,a)};g.aa=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],k=arguments[b];k;)f.unshift(k),k=k.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){k=d[0][b];for(var h=1;h<c;h++)if(k!=d[h][b])return f;f=k}return f};g.Ea=O;g.ua=function(a){return a.contentDocument||a.contentWindow.document};
g.va=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Q(c):window}else d=null;b=d}return b}catch(e){}return null};g.Cb=Nb;g.Da=function(a){if("outerHTML"in a)return a.outerHTML;var b=R(O(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ba=function(a,b){var c=[];return Ob(a,b,c,!0)?c[0]:void 0};g.ca=function(a,b){var c=[];Ob(a,b,c,!1);return c};g.jb=Rb;g.Ab=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.ib=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Sb(a)||Tb(a)):Rb(a))&&E){var c;!u(a.getBoundingClientRect)||E&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.La=Ub;g.Ba=function(a){return Ub(a).length};
g.Ca=function(a,b){b=b||O(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Ub(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Aa=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Pb))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in Qb)d+=Qb[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);v(c)&&(c.tb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.lb=Ib;g.ia=Wb;g.ha=function(a,b,c){return Wb(a,null,b,c)};g.ga=Xb;g.ja=function(a){return a.getContext("2d")};function Yb(a){a=(a||Zb).T;a=null!=a&&a.D===bb?a:a instanceof A?tb(B(a).toString(),a.a()):tb(ab(String(String(a))),sb(a));var b=tb('<span class="devsite-tooltip-msg">'+a+"</span>");a=M();a=R(a.a,"DIV");if(v(b))if(b instanceof D){if(b.D!==bb)throw Error("Sanitized content was not of kind HTML.");b=Wa(b.toString(),b.C||null)}else b=C("zSoyz");else b=C(String(b));$a(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var Zb={};var $b=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if($b&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function V(a){var b=HTMLElement.call(this)||this;a&&ac(a);return b}la(V,HTMLElement);V.prototype.s=function(){console.warn(this.tagName,"has not implemented update")};V.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
V.prototype.o=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function ac(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var bc=new Map;function W(a){var b=V.call(this)||this;a&&ac(a);return b}la(W,V);W.prototype.connectedCallback=function(){var a=this.constructor,b=bc.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):bc.set(a,this)};W.prototype.disconnectedCallback=function(){var a=this.constructor;bc.get(a)===this&&bc.delete(a)};W.prototype.disconnectedCallback=W.prototype.disconnectedCallback;W.prototype.connectedCallback=W.prototype.connectedCallback;function X(){this.l=this.l;this.b=this.b}g=X.prototype;g.l=!1;g.O=function(){return this.l};g.la=X.prototype.O;g.H=function(){this.l||(this.l=!0,this.m())};g.sb=function(a){a=ta(cc,a);this.l?a():(this.b||(this.b=[]),this.b.push(a))};g.m=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function cc(a){a&&"function"==typeof a.H&&a.H()};function dc(a,b){this.type=a;this.b=this.target=b;this.defaultPrevented=this.g=!1}dc.prototype.h=function(){this.g=!0};dc.prototype.c=function(){this.defaultPrevented=!0};var ec=!E||9<=Number(J),fc=!E||9<=Number(J),gc=E&&!I("9"),hc=function(){if(!t.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{t.addEventListener("test",oa,b),t.removeEventListener("test",oa,b)}catch(c){}return a}();var ic;ic=H?"webkitTransitionEnd":hb?"otransitionend":"transitionend";function Y(a,b){dc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.A=this.s=0;this.key="";this.j=this.o=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.P=null;this.S=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(F){a:{try{eb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.s=H||void 0!==a.offsetX?a.offsetX:a.layerX,this.A=H||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.o=a.keyCode||0;this.key=a.key||"";this.j=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.S=jb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:jc[a.pointerType]||"";this.P=a.state;this.a=a;a.defaultPrevented&&this.c()}}x(Y,dc);var kc=[1,4,2],jc={2:"touch",3:"pen",4:"mouse"};
Y.prototype.Fb=function(){return(ec?0==this.a.button:"click"==this.type?!0:!!(this.a.button&kc[0]))&&!(jb&&this.ctrlKey)};Y.prototype.h=function(){Y.v.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Y.prototype.c=function(){Y.v.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,gc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};Y.prototype.Db=function(){return this.a};var lc="closure_listenable_"+(1E6*Math.random()|0),mc=0;function nc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++mc;this.u=this.B=!1}function oc(a){a.u=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function pc(a){this.src=a;this.a={};this.b=0}pc.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};pc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var k;a:{for(k=0;k<a.length;++k){var h=a[k];if(!h.u&&h.listener==b&&h.capture==!!d&&h.b==e)break a}k=-1}-1<k?(b=a[k],c||(b.B=!1)):(b=new nc(b,this.src,f,!!d,e),b.B=c,a.push(b));return b};
function qc(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=wa(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(oc(b),0==a.a[c].length&&(delete a.a[c],a.b--))}};var rc="closure_lm_"+(1E6*Math.random()|0),sc={},tc=0;function uc(a,b,c,d,e){if(d&&d.once)return vc(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)uc(a,b[f],c,d,e);return null}c=wc(c);return a&&a[lc]?a.g.add(String(b),c,!1,v(d)?!!d.capture:!!d,e):xc(a,b,c,!1,d,e)}
function xc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=v(e)?!!e.capture:!!e,h=yc(a);h||(a[rc]=h=new pc(a));c=h.add(b,c,d,k,f);if(c.a)return c;d=zc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)hc||(e=k),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ac(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");tc++;return c}
function zc(){var a=Bc,b=fc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function vc(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)vc(a,b[f],c,d,e);return null}c=wc(c);return a&&a[lc]?a.g.add(String(b),c,!0,v(d)?!!d.capture:!!d,e):xc(a,b,c,!0,d,e)}
function Cc(a){if("number"!==typeof a&&a&&!a.u){var b=a.src;if(b&&b[lc])qc(b.g,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ac(c),d):b.addListener&&b.removeListener&&b.removeListener(d);tc--;(c=yc(b))?(qc(c,a),0==c.b&&(c.src=null,b[rc]=null)):oc(a)}}}function Ac(a){return a in sc?sc[a]:sc[a]="on"+a}
function Dc(a,b,c,d){var e=!0;if(a=yc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.u&&(f=Ec(f,d),e=e&&!1!==f)}return e}function Ec(a,b){var c=a.listener,d=a.b||a.src;a.B&&Cc(a);return c.call(d,b)}
function Bc(a,b){if(a.u)return!0;if(!fc){if(!b)a:{b=["window","event"];for(var c=t,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new Y(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(k){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.g&&0<=e;e--){b.b=d[e];var f=Dc(d[e],a,!0,b);c=c&&f}for(e=0;!b.g&&e<d.length;e++)b.b=d[e],f=Dc(d[e],a,!1,b),c=
c&&f}return c}return Ec(a,new Y(b,this))}function yc(a){a=a[rc];return a instanceof pc?a:null}var Fc="__closure_events_fn_"+(1E9*Math.random()>>>0);function wc(a){if(u(a))return a;a[Fc]||(a[Fc]=function(b){return a.handleEvent(b)});return a[Fc]};function Gc(a,b){if(!u(a))if(a&&"function"==typeof a.handleEvent)a=w(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:t.setTimeout(a,b||0)};function Hc(a,b,c){X.call(this);this.A=null!=c?w(a,c):a;this.s=b;this.o=w(this.R,this);this.c=!1;this.g=0;this.h=this.a=null;this.j=[]}x(Hc,X);g=Hc.prototype;g.I=function(a){this.j=arguments;this.c=!1;this.a?this.h=ua()+this.s:this.a=Gc(this.o,this.s)};g.Na=function(){++this.g};g.Oa=function(){this.g&&(--this.g,!this.g&&this.c&&(this.c=!1,this.A.apply(null,this.j)))};g.m=function(){this.a&&(t.clearTimeout(this.a),this.a=null);this.h=null;this.c=!1;this.j=[];Hc.v.m.call(this)};
g.R=function(){this.h?(this.a=Gc(this.o,this.h-ua()),this.h=null):(this.a=null,this.g?this.c=!0:(this.c=!1,this.A.apply(null,this.j)))};function Ic(a){X.call(this);this.c=a;this.a={}}x(Ic,X);var Jc=[];function Kc(a,b,c){Lc(a,document.body,b,c,void 0)}g=Ic.prototype;g.ob=function(a,b,c,d,e){return Lc(this,a,b,c,d,e)};function Lc(a,b,c,d,e,f){Array.isArray(c)||(c&&(Jc[0]=c.toString()),c=Jc);for(var k=0;k<c.length;k++){var h=uc(b,c[k],d||a.handleEvent,e||!1,f||a.c||a);if(!h)break;a.a[h.key]=h}return a}g.Ya=function(a,b,c,d){return Mc(this,a,b,c,d)};g.nb=function(a,b,c,d,e){return Mc(this,a,b,c,d,e)};
function Mc(a,b,c,d,e,f){if(Array.isArray(c))for(var k=0;k<c.length;k++)Mc(a,b,c[k],d,e,f);else{b=vc(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.pb=function(a,b,c,d){b.a(a,c,d,this.c||this,this);return this};g.qb=function(a,b,c,d,e){b.a(a,c,d,e||this.c||this,this);return this};g.Xa=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};g.Eb=function(a,b,c,d,e){b.b(a,c,d,e||this.c||this,this);return this};
function Nc(a){Aa(a.a,function(b,c){this.a.hasOwnProperty(c)&&Cc(b)},a);a.a={}}g.m=function(){Ic.v.m.call(this);Nc(this)};g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Oc(a){try{return a.getBoundingClientRect()}catch(b){return{left:0,top:0,right:0,bottom:0}}}function Pc(a){var b=O(a),c=new K(0,0);var d=b?O(b):document;d=!E||9<=Number(J)||P(M(d).a)?d.documentElement:d.body;if(a==d)return c;a=Oc(a);d=M(b).a;b=Fb(d);d=Q(d);b=E&&I("10")&&d.pageYOffset!=b.scrollTop?new K(b.scrollLeft,b.scrollTop):new K(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop);c.x=a.left+b.x;c.y=a.top+b.y;return c}
function Qc(a){var b=Rc;a:{var c=O(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}c||(c=a.currentStyle?a.currentStyle.display:null);if("none"!=(c||a.style&&a.style.display))return b(a);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}
function Rc(a){var b=a.offsetWidth,c=a.offsetHeight,d=H&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Oc(a),new L(a.right-a.left,a.bottom-a.top)):new L(b,c)};var Sc=["dl.google.com"],Tc="abc.xyz admob.com android.com blogger.com blogspot.com chrome.com chromium.org domains.google doubleclick.com feedburner.com g.co ggpht.com gmail.com gmodules.com goo.gl google.com google.org googleapis.com googleapps.com googlecode.com googledrive.com googlemail.com googlesource.com googlesyndication.com googletagmanager.com googleusercontent.com gv.com keyhole.com madewithcode.com panoramio.com urchin.com withgoogle.com youtu.be youtube.com ytimg.com".split(" ");
function Z(){var a=W.call(this)||this;a.a=new Ic;a.b=null;a.c=null;a.h=new Hc(function(){return Uc(a)},250);return a}la(Z,W);Z.prototype.connectedCallback=function(){document.body.hasAttribute("touch")?T(this):(Vc(this),this.h.I())};Z.prototype.disconnectedCallback=function(){W.prototype.disconnectedCallback.call(this);Nc(this.a)};
function Vc(a){Kc(a.a,"devsite-content-updated",function(){return a.h.I()});Kc(a.a,"onpointermove"in window?"pointermove":"mousemove",function(b){b=b.target;for(var c=!1;b;){b.hasAttribute&&(c=Wc(b));if(c)break;b=b.parentNode}b&&c?Xc(a,b):Yc(a)});Kc(a.a,"focusin",function(b){b=b.target;var c=b.firstElementChild;(b.classList.contains("devsite-nav-title")&&c?Wc(c):Wc(b))?Xc(a,b):Yc(a)});Kc(a.a,["devsite-sticky-scroll","devsite-sticky-resize"],function(){return Yc(a)})}
function Wc(a){return a.hasAttribute("no-tooltip")?!1:a.hasAttribute("data-title")||a.hasAttribute("data-tooltip")||a.hasAttribute("tooltip")&&a.clientWidth<a.scrollWidth}
function Xc(a,b){if(a.b!==b){Yc(a);var c=b.getAttribute("data-tooltip")||b.getAttribute("data-title")||b.textContent.trim(),d=Yb({T:c});d.style.opacity=0;document.body.appendChild(d);var e=Eb(window),f=Qc(b),k=Qc(d),h=Pc(b);c=h.y+f.height;f=h.x+f.width/2-k.width/2;k.width>e.width?f=0:(f=Math.max(f,8),e=e.width-(f+k.width+8),0>e&&(f=f+e-8));d.style.top=c+"px";d.style.left=f+"px";a.b=b;a.c=d;window.requestAnimationFrame(function(){d.style.opacity=1})}}
function Yc(a){if(a.b){a.b=null;var b=a.c;a.c=null;vc(b,ic,function(){T(b);S(b)});window.setTimeout(function(){T(b);S(b)},1E3);b.style.opacity=0}}
function Uc(a){Array.from(document.querySelectorAll(".devsite-article-body [title]")).forEach(function(b){b.setAttribute("data-title",b.getAttribute("title"));b.removeAttribute("title")});a.hasAttribute("blocked-link")&&Array.from(document.getElementsByTagName("a")).forEach(function(b){if(b.hasAttribute("href")){for(var c=(new URL(b.getAttribute("href"),document.location.origin)).hostname.replace("www.",""),d=0;d<Sc.length;d++)if(-1!==c.indexOf(Sc[d]))return;for(d=0;d<Tc.length;d++)if(-1!==c.indexOf(Tc[d])){b.setAttribute("data-title",
"This link may not be accessible in your region.");b.removeAttribute("title");break}}})}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-tooltip",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteTooltip",a)};}).call(this);
