(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function l(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ea={L:!0},fa={};try{fa.__proto__=ea;n=fa.L;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=m;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(p)p(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.l=b.prototype}l("Object.setPrototypeOf",function(a){return a||p});
var ia=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();l("Reflect.construct",function(){return ia});
l("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});var q=this||self;function r(){}function t(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}
function ja(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function v(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.W=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var la;var ma=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},na=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},oa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function pa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function ra(a,b){if(b)a=a.replace(sa,"&amp;").replace(ta,"&lt;").replace(ua,"&gt;").replace(va,"&quot;").replace(wa,"&#39;").replace(xa,"&#0;");else{if(!ya.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(sa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ta,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ua,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(va,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(wa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(xa,"&#0;"))}return a}
var sa=/&/g,ta=/</g,ua=/>/g,va=/"/g,wa=/'/g,xa=/\x00/g,ya=/[\x00&<>"']/;function za(a,b){return a<b?-1:a>b?1:0};var w;a:{var Aa=q.navigator;if(Aa){var Ba=Aa.userAgent;if(Ba){w=Ba;break a}}w=""};function Ca(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Da(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Ea="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Fa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ea.length;f++)c=Ea[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function x(a){this.b=Ga===Ga&&a||"";this.c=Ha}x.prototype.v=!0;x.prototype.s=function(){return this.b.toString()};x.prototype.F=!0;x.prototype.a=function(){return 1};var Ha={},Ga={};function y(){this.b="";this.f=Ia;this.c=null}y.prototype.F=!0;y.prototype.a=function(){return this.c};y.prototype.v=!0;y.prototype.s=function(){return this.b.toString()};function z(a){return a instanceof y&&a.constructor===y&&a.f===Ia?a.b:"type_error:SafeHtml"}function A(a){if(a instanceof y)return a;var b="object"==typeof a,c=null;b&&a.F&&(c=a.a());return Ja(ra(b&&a.v?a.s():String(a)),c)}
function Ka(a){function b(f){Array.isArray(f)?na(f,b):(f=A(f),e.push(z(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=A(La),d=c.a(),e=[];na(a,b);return Ja(e.join(z(c).toString()),d)}function Ma(a){return Ka(Array.prototype.slice.call(arguments))}var Ia={};function Ja(a,b){return Na(a,b)}function Na(a,b){var c=new y;c.b=a;c.c=b;return c}var Oa=new y;Oa.b=q.trustedTypes&&q.trustedTypes.emptyHTML?q.trustedTypes.emptyHTML:"";Oa.c=0;var La=Oa,Pa=Na("<br>",0);var Qa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=z(La);return!b.parentElement});function B(a,b){if(Qa())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=z(b)};function Ra(a){return a=ra(a,void 0)};function Sa(a){Sa[" "](a);return a}Sa[" "]=r;function Ta(a,b){var c=Ua;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Va=-1!=w.indexOf("Opera"),C=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),Wa=-1!=w.indexOf("Edge"),D=-1!=w.indexOf("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"))&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"))&&-1==w.indexOf("Edge"),E=-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"),Xa=-1!=w.indexOf("Macintosh");function Ya(){var a=q.document;return a?a.documentMode:void 0}var Za;
a:{var $a="",ab=function(){var a=w;if(D)return/rv:([^\);]+)(\)|;)/.exec(a);if(Wa)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(E)return/WebKit\/(\S+)/.exec(a);if(Va)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ab&&($a=ab?ab[1]:"");if(C){var bb=Ya();if(null!=bb&&bb>parseFloat($a)){Za=String(bb);break a}}Za=$a}var cb=Za,Ua={};
function F(a){return Ta(a,function(){for(var b=0,c=qa(String(cb)).split("."),d=qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=za(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||za(0==h[2].length,0==k[2].length)||za(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var db;
if(q.document&&C){var eb=Ya();db=eb?eb:parseInt(cb,10)||void 0}else db=void 0;var G=db;var fb=!C||9<=Number(G),gb=!C||9<=Number(G),hb=C&&!F("9"),ib=function(){if(!q.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{q.addEventListener("test",r,b),q.removeEventListener("test",r,b)}catch(c){}return a}();function H(){this.g=this.g;this.b=this.b}g=H.prototype;g.g=!1;g.P=function(){return this.g};g.ka=H.prototype.P;g.B=function(){this.g||(this.g=!0,this.o())};g.xb=function(a){a=ka(jb,a);this.g?a():(this.b||(this.b=[]),this.b.push(a))};g.o=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function jb(a){a&&"function"==typeof a.B&&a.B()};function I(a,b){this.type=a;this.b=this.target=b;this.J=this.f=!1}I.prototype.j=function(){this.f=!0};I.prototype.c=function(){this.J=!0};function J(a,b){I.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.H=this.G=0;this.key="";this.u=this.C=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.I=null;this.K=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(D){a:{try{Sa(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.G=E||void 0!==a.offsetX?a.offsetX:a.layerX,this.H=E||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.C=a.keyCode||0;this.key=a.key||"";this.u=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.K=Xa?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:kb[a.pointerType]||"";this.I=a.state;this.a=a;a.defaultPrevented&&this.c()}}v(J,I);var lb=[1,4,2],kb={2:"touch",3:"pen",4:"mouse"};
J.prototype.Qb=function(){return(fb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&lb[0]))&&!(Xa&&this.ctrlKey)};J.prototype.j=function(){J.l.j.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};J.prototype.c=function(){J.l.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,hb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};J.prototype.S=function(){return this.a};var mb="closure_listenable_"+(1E6*Math.random()|0),nb=0;function ob(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++nb;this.i=this.m=!1}function K(a){a.i=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function pb(a){this.src=a;this.a={};this.b=0}g=pb.prototype;g.Ya=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=qb(a,b,d,e);-1<h?(b=a[h],c||(b.m=!1)):(b=new ob(b,this.src,f,!!d,e),b.m=c,a.push(b));return b};
g.$a=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=qb(e,b,c,d);return-1<b?(K(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.ab=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,K(d[e]);delete this.a[c];this.b--}return b};g.ya=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.Za=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Da(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function qb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.i&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var rb="closure_lm_"+(1E6*Math.random()|0),sb={},tb=0;function ub(a,b,c,d,e){if(d&&d.once)return vb(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)ub(a,b[f],c,d,e);return null}c=wb(c);return a&&a[mb]?a.H(b,c,u(d)?!!d.capture:!!d,e):xb(a,b,c,!1,d,e)}
function xb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=u(e)?!!e.capture:!!e,k=yb(a);k||(a[rb]=k=new pb(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=zb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)ib||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ab(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");tb++;return c}
function zb(){var a=Bb,b=gb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function vb(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)vb(a,b[f],c,d,e);return null}c=wb(c);return a&&a[mb]?a.I(b,c,u(d)?!!d.capture:!!d,e):xb(a,b,c,!0,d,e)}
function Cb(a){if("number"!==typeof a&&a&&!a.i){var b=a.src;if(b&&b[mb])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ab(c),d):b.addListener&&b.removeListener&&b.removeListener(d);tb--;if(c=yb(b)){d=a.type;if(d in c.a){var e=c.a[d],f=ma(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(K(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[rb]=null)}else K(a)}}}
function Ab(a){return a in sb?sb[a]:sb[a]="on"+a}function Db(a,b,c,d){var e=!0;if(a=yb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.i&&(f=Eb(f,d),e=e&&!1!==f)}return e}function Eb(a,b){var c=a.listener,d=a.b||a.src;a.m&&Cb(a);return c.call(d,b)}
function Bb(a,b){if(a.i)return!0;if(!gb){if(!b)a:{b=["window","event"];for(var c=q,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new J(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.f&&0<=e;e--){b.b=d[e];var f=Db(d[e],a,!0,b);c=c&&f}for(e=0;!b.f&&e<d.length;e++)b.b=d[e],f=Db(d[e],a,!1,b),c=
c&&f}return c}return Eb(a,new J(b,this))}function yb(a){a=a[rb];return a instanceof pb?a:null}var Fb="__closure_events_fn_"+(1E9*Math.random()>>>0);function wb(a){if("function"==t(a))return a;a[Fb]||(a[Fb]=function(b){return a.handleEvent(b)});return a[Fb]};var Gb={},Hb={};function L(){throw Error("Do not instantiate directly");}L.prototype.a=null;L.prototype.toString=function(){return this.D};function Ib(a){if(a.h!==Gb)throw Error("Sanitized content was not of kind HTML.");return Na(a.toString(),a.a||null)}L.prototype.b=function(){if(this.h!==Hb)throw Error("Sanitized content was not of kind URI.");return new x(this.toString())};function Jb(){L.call(this)}v(Jb,L);Jb.prototype.h=Gb;var Kb=function(a){function b(c){this.D=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.a=d);return c}}(Jb);function M(a){return null!=a&&a.h===Gb?String(String(a.D).replace(Lb,"").replace(Mb,"&lt;")).replace(Nb,Qb):Ra(String(a))}
var Rb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Qb(a){return Rb[a]}var Nb=/[\x00\x22\x27\x3c\x3e]/g,Lb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Mb=/</g;var Sb=!C||9<=Number(G),Tb=!D&&!C||C&&9<=Number(G)||D&&F("1.9.1"),Ub=C&&!F("9"),Vb=C||Va||E;function N(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}g=N.prototype;g.bb=function(){return new N(this.x,this.y)};g.Z=function(a){return a instanceof N&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.eb=function(a,b){a instanceof N?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),"number"===typeof b&&(this.y+=b));return this};g.cb=function(a,b){this.x*=a;this.y*="number"===typeof b?b:a;return this};g.Hb=function(a,b){a=a*Math.PI/180;b=b||new N(0,0);var c=this.x,d=this.y,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.y)*a+b.x;this.y=(c-b.x)*a+(d-b.y)*e+b.y};function Wb(a,b){this.width=a;this.height=b}g=Wb.prototype;g.fb=function(){return new Wb(this.width,this.height)};g.za=function(){return Math.max(this.width,this.height)};g.Ma=function(){return Math.min(this.width,this.height)};g.wb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.mb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ca=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Xb(a,b){a.width*=b;a.height*=b;return a}g.Ib=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Xb(this,a)};
g.Jb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Xb(this,a)};function O(a){return a?new P(Q(a)):la||(la=new P)}function Yb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Zb(document,"*",a,b);return d||null}
function $b(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=ma(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Zb(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):$b(a,b,c,d)[0]||null}function ac(a,b){Ca(b,function(c,d){c&&"object"==typeof c&&c.v&&(c=c.s());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:bc.hasOwnProperty(d)?a.setAttribute(bc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var bc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function cc(a){a=a.document;a=R(a)?a.documentElement:a.body;return new Wb(a.clientWidth,a.clientHeight)}function dc(a){return a.scrollingElement?a.scrollingElement:!E&&R(a)?a.documentElement:a.body||a.documentElement}
function S(a){return a.parentWindow||a.defaultView}function ec(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];ja(f)&&!fc(f)?na(gc(f)?pa(f):f,e):e(f)}}function T(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function R(a){return"CSS1Compat"==a.compatMode}function hc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function ic(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function U(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function fc(a){return u(a)&&0<a.nodeType}function jc(a){return u(a)&&1==a.nodeType}function kc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function lc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return mc(b,a)}function mc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function nc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else hc(a),a.appendChild(Q(a).createTextNode(String(b)))}function oc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||oc(a,b,c,d))return!0;a=a.nextSibling}return!1}var pc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},V={IMG:" ",BR:"\n"};
function qc(a){return rc(a)&&sc(a)}function rc(a){return C&&!F("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function sc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function tc(a){if(Ub&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];uc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Ub||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function uc(a,b,c){if(!(a.nodeName in pc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in V)b.push(V[a.nodeName]);else for(a=a.firstChild;a;)uc(a,b,c),a=a.nextSibling}function gc(a){if(a&&"number"==typeof a.length){if(u(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==t(a))return"function"==typeof a.item}return!1}
function vc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return wc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=ma(f.className.split(/\s+/),c));return h},!0,d)}function wc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function P(a){this.a=a||q.document||document}g=P.prototype;g.qa=O;g.Kb=function(a){this.a=a};g.la=function(){return this.a};
g.N=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Ka=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.T=P.prototype.N;g.Ta=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.O=function(a,b,c){return $b(this.a,a,b,c)};g.sa=function(a,b,c){return Zb(this.a,a,b,c)};g.ta=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):$b(document,"*",a,b)};g.ra=function(a,b){return Yb(a,b||this.a)};
g.La=function(a,b){return Yb(a,b||this.a)};g.U=P.prototype.O;g.Mb=ac;g.Oa=function(a){return cc(a||S(this.a)||window)};g.ma=function(){var a=S(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=cc(a).height,R(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.M=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Sb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Ra(h.name),'"');if(h.type){f.push(' type="',Ra(h.type),'"');var k={};Fa(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=T(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):ac(f,h));2<e.length&&ec(d,f,e,2);return f};g.V=P.prototype.M;g.Sa=function(a){return this.a.createTextNode(String(a))};
g.Y=function(a,b,c){var d=this.a;c=!!c;for(var e=T(d,"TABLE"),f=e.appendChild(T(d,"TBODY")),h=0;h<a;h++){for(var k=T(d,"TR"),Ob=0;Ob<b;Ob++){var Pb=T(d,"TD");c&&nc(Pb,"\u00a0");k.appendChild(Pb)}f.appendChild(k)}return e};g.kb=function(){return R(this.a)};g.oa=function(){return dc(this.a)};g.na=function(){var a=this.a,b=dc(a);a=S(a);return C&&F("10")&&a.pageYOffset!=b.scrollTop?new N(b.scrollLeft,b.scrollTop):new N(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.ea=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Qa=function(a,b){a.appendChild(b)};g.Pa=function(a,b){ec(Q(a),a,arguments,1)};g.Ra=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.zb=hc;g.jb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.ib=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.hb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Ua=ic;g.Va=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.da=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return ic(a)}};
g.ja=function(a){return Tb&&void 0!=a.children?a.children:oa(a.childNodes,function(b){return 1==b.nodeType})};g.ua=function(a){return void 0!==a.firstElementChild?a.firstElementChild:U(a.firstChild,!0)};g.xa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:U(a.lastChild,!1)};g.Aa=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:U(a.nextSibling,!0)};g.Ia=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:U(a.previousSibling,!1)};
g.Ba=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ja=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.pb=fc;g.lb=jc;g.rb=function(a){return u(a)&&a.window==a};g.Ha=function(a){var b;if(Vb&&!(C&&F("9")&&!F("10")&&q.SVGElement&&a instanceof q.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return jc(b)?b:null};
g.contains=kc;
g.X=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(C&&!(9<=Number(G))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?mc(a,b):!c&&kc(e,b)?-1*lc(a,b):!d&&kc(f,a)?lc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=Q(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(q.Range.START_TO_END,a)};g.$=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Ga=Q;g.va=function(a){return a.contentDocument||a.contentWindow.document};
g.wa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?S(c):window}else d=null;b=d}return b}catch(e){}return null};g.Nb=nc;g.Fa=function(a){if("outerHTML"in a)return a.outerHTML;var b=T(Q(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.aa=function(a,b){var c=[];return oc(a,b,c,!0)?c[0]:void 0};g.ba=function(a,b){var c=[];oc(a,b,c,!1);return c};g.ob=qc;g.Lb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.nb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!rc(a)||sc(a)):qc(a))&&C){var c;"function"!=t(a.getBoundingClientRect)||C&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Na=tc;g.Da=function(a){return tc(a).length};
g.Ea=function(a,b){b=b||Q(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(tc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ca=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in pc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in V)d+=V[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);u(c)&&(c.yb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.qb=gc;g.ha=vc;g.ga=function(a,b,c){return vc(a,null,b,c)};g.fa=wc;g.ia=function(a){return a.getContext("2d")};function xc(a,b){b=b||O();b=T(b.a,"DIV");a=yc(a);B(b,a);return 1==b.childNodes.length&&(a=b.firstChild,1==a.nodeType)?a:b}function yc(a){return u(a)?a instanceof L?Ib(a):A("zSoyz"):A(String(a))}var zc={};function Ac(){return"Unusable documentation"}function Bc(){return"Poor documentation"}function Cc(){return"OK documentation"}function Dc(){return"Good documentation"}function Ec(){return"Excellent documentation"}function Fc(a){return'You rated "'+(a.A+'"')}function Gc(a){return a.A};var Hc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Hc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function W(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(W,HTMLElement);W.prototype.S=function(){console.warn(this.tagName,"has not implemented update")};W.prototype.G=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
W.prototype.J=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function X(a){H.call(this);this.c=a;this.a={}}v(X,H);var Ic=[];function Jc(a,b,c,d){Kc(a,b,c,d,void 0)}g=X.prototype;g.tb=function(a,b,c,d,e){return Kc(this,a,b,c,d,e)};function Kc(a,b,c,d,e,f){Array.isArray(c)||(c&&(Ic[0]=c.toString()),c=Ic);for(var h=0;h<c.length;h++){var k=ub(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.Xa=function(a,b,c,d){return Lc(this,a,b,c,d)};g.sb=function(a,b,c,d,e){return Lc(this,a,b,c,d,e)};
function Lc(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Lc(a,b,c[h],d,e,f);else{b=vb(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.ub=function(a,b,c,d){b.a(a,c,d,this.c||this,this);return this};g.vb=function(a,b,c,d,e){b.a(a,c,d,e||this.c||this,this);return this};g.Wa=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};g.Pb=function(a,b,c,d,e){b.b(a,c,d,e||this.c||this,this);return this};
function Mc(a){Ca(a.a,function(b,c){this.a.hasOwnProperty(c)&&Cb(b)},a);a.a={}}g.o=function(){X.l.o.call(this);Mc(this)};g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Nc(){this.a=O();this.b=null}g=Nc.prototype;g.Cb=function(a,b){var c=this.a||O();a=a(b||zc,{});a=yc(a);b=c.a;c=T(b,"DIV");C?(a=Ma(Pa,a),B(c,a),c.removeChild(c.firstChild)):B(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(a=b.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);c=a}return c};g.Bb=function(a,b){var c=this.a;return xc(a(b||zc,{}),c)};g.Db=function(a,b,c){b=yc(b(c||zc,{}));B(a,b)};g.Ab=function(a,b){a=a(b||{},{});return String(a)};
function Y(a,b){a=a(b||{},{});return String(a)}g.Gb=function(a,b){return a(b||{},{})};g.Eb=function(a,b){return Ib(a(b||{},{}))};g.Fb=function(a,b){return a(b||{},{}).Ob()};g.pa=function(){return this.a};g.gb=r;function Z(){var a=W.call(this)||this;a.a=new X;a.j=["Unusable documentation, with a rating of 1 out of 5","Poor documentation, with a rating of 2 out of 5","OK documentation, with a rating of 3 out of 5","Good documentation, with a rating of 4 out of 5","Excellent documentation, with a rating of 5 out of 5"];a.K=new Nc;a.b=0;a.u=["You rated this page 1 out of 5 stars.","You rated this page 2 out of 5 stars.","You rated this page 3 out of 5 stars.","You rated this page 4 out of 5 stars.","You rated this page 5 out of 5 stars."];
a.c=[];var b=[Y(Ac),Y(Bc),Y(Cc),Y(Dc),Y(Ec)];a.f=b;return a}ha(Z,W);
Z.prototype.connectedCallback=function(){var a=this.getAttribute("position")||"";var b=this.j,c=this.f,d="";(a&&a.R&&"footer".R?a.h!=="footer".h?0:a.toString()==="footer".toString():"footer"==a)&&(d+='<div class="devsite-rating-caption">Was this page helpful?</div>');d+='<div class="devsite-rating-stars">';for(var e=Math.max(0,Math.ceil(b.length)),f=0;f<e;f++){var h=f;d+='<div class="devsite-rating-star devsite-rating-star-outline gc-analytics-event material-icons" data-rating-val="'+M(h+1)+'" track-metadata-score="'+
M(h+1)+'" track-type="feedback" track-name="rating" track-metadata-position="'+M(a)+'" role="button" tabindex="0" data-title="'+M(c[h])+'" aria-label="'+M(b[h])+'"></div>'}a=Kb(d+"</div>");a=xc(a,void 0);this.c=Array.from(a.querySelectorAll(".devsite-rating-star"));this.hasAttribute("selected-rating")||this.setAttribute("selected-rating","0");this.hasAttribute("hover-rating-star")||this.setAttribute("hover-rating-star","0");this.appendChild(a);Oc(this)};
function Oc(a){var b="onpointerover"in window?"pointerover":"mouseover",c="onpointerout"in window?"pointerout":"mouseout";Jc(a.a,a,["click","keypress"],function(d){var e=d.target;!e.classList.contains("devsite-rating-star")||"click"!==d.type&&13!==d.C||(d=Number(e.getAttribute("data-rating-val")),d!=a.b&&(Pc("selected-rating",d),e={nonInteraction:!0,page:(new URL(document.location.toString())).pathname,referrer:(new URL(document.location.toString())).pathname,ratings_value:d,ratings_count:1},a.dispatchEvent(new CustomEvent("devsite-analytics-pageview",
{detail:e,bubbles:!0}))),3>=d&&(e=document.querySelector("devsite-feedback"))&&e.dispatchEvent(new Event("click")),a.setAttribute("aria-label",a.u[d-1]))});Jc(a.a,a,[b,"focusin"],function(d){d.target.classList.contains("devsite-rating-star")&&(d=Number(d.target.getAttribute("data-rating-val")),Pc("hover-rating-star",d))});Jc(a.a,a,[c,"focusout"],function(d){d.target.classList.contains("devsite-rating-star")&&Pc("hover-rating-star",a.b)})}
Z.prototype.attributeChangedCallback=function(a,b,c){if("selected-rating"===a&&null!=b){var d=this.b=Number(c)||0;b=Number(b)||0;var e=d-1,f=b-1;0<b&&5>=b&&this.c[f].setAttribute("data-title",Y(Gc,{A:this.f[f]}));0<d&&5>=d&&this.c[e].setAttribute("data-title",Y(Fc,{A:this.f[e]}))}"hover-rating-star"===a&&Qc(this,Number(c)||0)};Z.prototype.disconnectedCallback=function(){Mc(this.a)};
function Pc(a,b){Array.from(document.getElementsByTagName("devsite-page-rating")).forEach(function(c){return c.setAttribute(a,b)})}function Qc(a,b){a.c.forEach(function(c){Number(c.getAttribute("data-rating-val"))<=b?c.classList.add("devsite-rating-star-full"):c.classList.remove("devsite-rating-star-full")})}da.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["selected-rating","hover-rating-star"]}}});Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;
Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-page-rating",Z)}catch(a){console.warn("devsite.app.customElement.DevsitePageRating",a)};}).call(this);
