(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function q(a,b){if(b){var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={Z:!0},ja={};try{ja.__proto__=ia;ha=ja.Z;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.I=b.prototype}
q("Promise",function(a){function b(f){this.b=0;this.c=void 0;this.a=[];var k=this.f();try{f(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(f){return f instanceof b?f:new b(function(k){k(f)})}if(a)return a;c.prototype.b=function(f){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(f)};var e=ea.setTimeout;c.prototype.c=function(f){e(f,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var k=0;k<f.length;++k){var l=
f[k];f[k]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(f){this.c(function(){throw f;})};b.prototype.f=function(){function f(m){return function(n){l||(l=!0,m.call(k,n))}}var k=this,l=!1;return{resolve:f(this.R),reject:f(this.g)}};b.prototype.R=function(f){if(f===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.X(f);else{a:switch(typeof f){case "object":var k=null!=f;break a;case "function":k=!0;break a;default:k=!1}k?this.o(f):this.h(f)}};
b.prototype.o=function(f){var k=void 0;try{k=f.then}catch(l){this.g(l);return}"function"==typeof k?this.Y(k,f):this.h(f)};b.prototype.g=function(f){this.i(2,f)};b.prototype.h=function(f){this.i(1,f)};b.prototype.i=function(f,k){if(0!=this.b)throw Error("Cannot settle("+f+", "+k+"): Promise already settled in state"+this.b);this.b=f;this.c=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var f=0;f<this.a.length;++f)g.b(this.a[f]);this.a=null}};var g=new c;b.prototype.X=function(f){var k=this.f();
f.J(k.resolve,k.reject)};b.prototype.Y=function(f,k){var l=this.f();try{f.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(f,k){function l(y,J){return"function"==typeof y?function(Pa){try{m(y(Pa))}catch(Qa){n(Qa)}}:J}var m,n,x=new b(function(y,J){m=y;n=J});this.J(l(f,m),l(k,n));return x};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.J=function(f,k){function l(){switch(m.b){case 1:f(m.c);break;case 2:k(m.c);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?g.b(l):this.a.push(l)};b.resolve=d;b.reject=function(f){return new b(function(k,l){l(f)})};b.race=function(f){return new b(function(k,l){for(var m=p(f),n=m.next();!n.done;n=m.next())d(n.value).J(k,l)})};b.all=function(f){var k=p(f),l=k.next();return l.done?d([]):new b(function(m,n){function x(Pa){return function(Qa){y[Pa]=Qa;J--;0==J&&m(y)}}var y=[],J=0;do y.push(void 0),J++,d(l.value).J(x(y.length-1),n),l=k.next();while(!l.done)})};return b});
q("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,g){this.a=e;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function oa(){this.i=!1;this.f=null;this.g=void 0;this.a=1;this.h=this.c=0;this.j=this.b=null}function pa(a){if(a.i)throw new TypeError("Generator is already running");a.i=!0}h=oa.prototype;h.M=function(a){this.g=a};function qa(a,b){a.b={ba:b,W:!0};a.a=a.c||a.h}h.return=function(a){this.b={return:a};this.a=this.h};h.Wb=function(a){this.b={B:a};this.a=this.h};
function r(a,b,c){a.a=c;return{value:b}}h.yc=function(a,b){a=p(a);var c=a.next();na(c);if(c.done)this.g=c.value,this.a=b;else return this.f=a,r(this,c.value,b)};h.B=function(a){this.a=a};h.oc=function(a){this.c=0;this.h=a||0};function ra(a,b){a.a=b;a.c=0}function sa(a){a.c=0;a.b=null}h.pa=function(a,b,c){c?this.j[c]=this.b:this.j=[this.b];this.c=a||0;this.h=b||0};
h.Xb=function(a,b){b=this.j.splice(b||0)[0];(b=this.b=this.b||b)?b.W?this.a=this.c||this.h:void 0!=b.B&&this.h<b.B?(this.a=b.B,this.b=null):this.a=this.h:this.a=a};h.wa=function(a){return new ta(a)};function ta(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}ta.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function ua(a){this.a=new oa;this.b=a}
function va(a,b){pa(a.a);var c=a.a.f;if(c)return wa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return xa(a)}function wa(a,b,c,d){try{var e=b.call(a.a.f,c);na(e);if(!e.done)return a.a.i=!1,e;var g=e.value}catch(f){return a.a.f=null,qa(a.a,f),xa(a)}a.a.f=null;d.call(a.a,g);return xa(a)}
function xa(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.i=!1,{value:b.value,done:!1}}catch(c){a.a.g=void 0,qa(a.a,c)}a.a.i=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.W)throw b.ba;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ya(a){this.next=function(b){pa(a.a);a.a.f?b=wa(a,a.a.f.next,b,a.a.M):(a.a.M(b),b=xa(a));return b};this.throw=function(b){pa(a.a);a.a.f?b=wa(a,a.a.f["throw"],b,a.a.M):(qa(a.a,b),b=xa(a));return b};this.return=function(b){return va(a,b)};this[Symbol.iterator]=function(){return this}}function za(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})}
function t(a){return za(new ya(new ua(a)))}q("Object.setPrototypeOf",function(a){return a||ka});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var Aa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ba(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();q("Reflect.construct",function(){return Aa});
q("WeakMap",function(a){function b(l){this.a=(k+=Math.random()+1).toString();if(l){l=p(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!u(l,f)){var m=new c;ca(l,f,{value:m})}}function g(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof c)return n;e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,
3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(x){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var k=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!u(l,f))throw Error("WeakMap key fail: "+l);l[f][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&u(l,f)?l[f][this.a]:void 0};b.prototype.has=function(l){return d(l)&&u(l,f)&&u(l[f],this.a)};
b.prototype.delete=function(l){return d(l)&&u(l,f)&&u(l[f],this.a)?delete l[f][this.a]:!1};return b});
q("Map",function(a){function b(){var k={};return k.s=k.next=k.head=k}function c(k,l){var m=k.a;return ma(function(){if(m){for(;m.head!=k.a;)m=m.s;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(k,l){var m=l&&typeof l;"object"==m||"function"==m?g.has(l)?m=g.get(l):(m=""+ ++f,g.set(l,m)):m="p_"+l;var n=k.b[m];if(n&&u(k.b,m))for(k=0;k<n.length;k++){var x=n[k];if(l!==l&&x.key!==x.key||l===x.key)return{id:m,list:n,index:k,l:x}}return{id:m,list:n,
index:-1,l:void 0}}function e(k){this.b={};this.a=b();this.size=0;if(k){k=p(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(p([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=k||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(x){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.b[m.id]=[]);m.l?m.l.value=l:(m.l={next:this.a,s:this.a.s,head:this.a,key:k,value:l},m.list.push(m.l),this.a.s.next=m.l,this.a.s=m.l,this.size++);return this};e.prototype.delete=function(k){k=d(this,k);return k.l&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.b[k.id],k.l.s.next=k.l.next,k.l.next.s=k.l.s,k.l.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.s=b();this.size=0};e.prototype.has=function(k){return!!d(this,k).l};e.prototype.get=function(k){return(k=d(this,k).l)&&k.value};e.prototype.entries=function(){return c(this,function(k){return[k.key,k.value]})};e.prototype.keys=function(){return c(this,function(k){return k.key})};e.prototype.values=function(){return c(this,function(k){return k.value})};e.prototype.forEach=function(k,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,
k.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});var v=this||self;function Ba(a){a=a.split(".");for(var b=v,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function Ca(){}function Da(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function w(a){var b=Da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function Ea(a){return"function"==Da(a)}
function z(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Fa(a,b,c){return a.call.apply(a.bind,arguments)}function Ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function A(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?A=Fa:A=Ga;return A.apply(null,arguments)}function Ha(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Ia=Date.now||function(){return+new Date};
function B(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.la=function(d,e,g){for(var f=Array(arguments.length-2),k=2;k<arguments.length;k++)f[k-2]=arguments[k];return b.prototype[e].apply(d,f)}};var Ja;var Ka=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},C=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},La=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,g="string"===typeof a?a.split(""):a,f=0;f<c;f++)if(f in g){var k=g[f];b.call(void 0,k,f,a)&&(d[e++]=k)}return d};function Ma(a){return Array.prototype.concat.apply([],arguments)}function Na(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Oa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var Ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Sa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Ra.length;g++)c=Ra[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ta(a,b){this.a=a===Ua&&b||"";this.b=Va}h=Ta.prototype;h.L=!0;h.K=function(){return this.a.toString()};h.P=!0;h.G=function(){return 1};h.ma=function(a,b){var c=Wa(this).toString();c=Xa.exec(c);var d=c[3]||"";a=c[1]+Ya("?",c[2]||"",a)+Ya("#",d,b);return new Ta(Ua,a)};function Wa(a){return a instanceof Ta&&a.constructor===Ta&&a.b===Va?a.a:"type_error:TrustedResourceUrl"}var Xa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Va={};
function Ya(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=Array.isArray(e)?e:[e];for(var g=0;g<e.length;g++){var f=e[g];null!=f&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(f)))}}return b}var Ua={};var Za=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function $a(a,b){if(b)a=a.replace(ab,"&amp;").replace(bb,"&lt;").replace(cb,"&gt;").replace(db,"&quot;").replace(eb,"&#39;").replace(fb,"&#0;");else{if(!gb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ab,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(bb,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(cb,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(db,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(eb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(fb,"&#0;"))}return a}
var ab=/&/g,bb=/</g,cb=/>/g,db=/"/g,eb=/'/g,fb=/\x00/g,gb=/[\x00&<>"']/;function D(a,b){return-1!=a.indexOf(b)}function hb(a,b){return a<b?-1:a>b?1:0};function E(a,b){this.a=a===ib&&b||"";this.b=jb}E.prototype.L=!0;E.prototype.K=function(){return this.a.toString()};E.prototype.P=!0;E.prototype.G=function(){return 1};var jb={},ib={};var F;a:{var kb=v.navigator;if(kb){var lb=kb.userAgent;if(lb){F=lb;break a}}F=""};function G(){this.a="";this.c=mb;this.b=null}G.prototype.P=!0;G.prototype.G=function(){return this.b};G.prototype.L=!0;G.prototype.K=function(){return this.a.toString()};function nb(a){return a instanceof G&&a.constructor===G&&a.c===mb?a.a:"type_error:SafeHtml"}function ob(a){if(a instanceof G)return a;var b="object"==typeof a,c=null;b&&a.P&&(c=a.G());return pb($a(b&&a.L?a.K():String(a)),c)}
function qb(a){function b(g){Array.isArray(g)?C(g,b):(g=ob(g),e.push(nb(g).toString()),g=g.G(),0==d?d=g:0!=g&&d!=g&&(d=null))}var c=ob(rb),d=c.G(),e=[];C(a,b);return pb(e.join(nb(c).toString()),d)}function sb(a){return qb(Array.prototype.slice.call(arguments))}var mb={};function pb(a,b){return tb(a,b)}function tb(a,b){var c=new G;c.a=a;c.b=b;return c}var ub=new G;ub.a=v.trustedTypes&&v.trustedTypes.emptyHTML?v.trustedTypes.emptyHTML:"";ub.b=0;var rb=ub,vb=tb("<br>",0);var wb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=nb(rb);return!b.parentElement});function xb(a,b){if(wb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=nb(b)};function yb(a){return a=$a(a,void 0)};var H="StopIteration"in v?v.StopIteration:{message:"StopIteration",stack:""};function I(){}I.prototype.next=function(){throw H;};I.prototype.u=function(){return this};function zb(a){if(a instanceof I)return a;if("function"==typeof a.u)return a.u(!1);if(w(a)){var b=0,c=new I;c.next=function(){for(;;){if(b>=a.length)throw H;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function Ab(a,b){if(w(a))try{C(a,b,void 0)}catch(c){if(c!==H)throw c;}else{a=zb(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==H)throw c;}}}function Bb(a){if(w(a))return Na(a);a=zb(a);var b=[];Ab(a,function(c){b.push(c)});return b};function Cb(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof Cb)for(c=a.A(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}h=Cb.prototype;h.m=function(){K(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};h.A=function(){K(this);return this.a.concat()};
h.Gb=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(L(this.b,c)&&this.b[c]==a)return!0}return!1};h.Hb=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||Db;K(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function Db(a,b){return a===b}h.Ib=function(){return 0==this.c};h.Fb=function(){this.b={};this.f=this.c=this.a.length=0};
h.remove=function(a){return L(this.b,a)?(delete this.b[a],this.c--,this.f++,this.a.length>2*this.c&&K(this),!0):!1};function K(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];L(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],L(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}h.get=function(a,b){return L(this.b,a)?this.b[a]:b};h.set=function(a,b){L(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};
h.forEach=function(a,b){for(var c=this.A(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};h.wc=function(){for(var a=new Cb,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};h.vc=function(){K(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};h.Qa=function(){return this.u(!0)};h.jb=function(){return this.u(!1)};
h.u=function(a){K(this);var b=0,c=this.f,d=this,e=new I;e.next=function(){if(c!=d.f)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw H;var g=d.a[b++];return a?g:d.b[g]};return e};function L(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Eb(a){if(a.m&&"function"==typeof a.m)return a.m();if("string"===typeof a)return a.split("");if(w(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Fb(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(w(a)||"string"===typeof a)C(a,b,c);else{if(a.A&&"function"==typeof a.A)var d=a.A();else if(a.m&&"function"==typeof a.m)d=void 0;else if(w(a)||"string"===typeof a){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=Eb(a);g=e.length;for(var f=0;f<g;f++)b.call(c,e[f],d&&d[f],a)}};var Gb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function Hb(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function M(a,b){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.o=!1;if(a instanceof M){this.g=void 0!==b?b:a.g;Ib(this,a.h);var c=a.j;N(this);this.j=c;c=a.b;N(this);this.b=c;Jb(this,a.f);c=a.c;N(this);this.c=c;Kb(this,Lb(a.a));a=a.i;N(this);this.i=a}else a&&(c=String(a).match(Gb))?(this.g=!!b,Ib(this,c[1]||"",!0),a=c[2]||"",N(this),this.j=O(a),a=c[3]||"",N(this),this.b=O(a,!0),Jb(this,c[4]),a=c[5]||"",N(this),this.c=O(a,!0),Kb(this,c[6]||"",!0),a=c[7]||"",N(this),this.i=O(a)):(this.g=
!!b,this.a=new Mb(null,this.g))}h=M.prototype;h.toString=function(){var a=[],b=this.h;b&&a.push(Nb(b,Ob,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Nb(b,Ob,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Nb(c,"/"==c.charAt(0)?Pb:Qb,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",Nb(c,Rb));return a.join("")};
h.resolve=function(a){var b=new M(this),c=!!a.h;c?Ib(b,a.h):c=!!a.j;if(c){var d=a.j;N(b);b.j=d}else c=!!a.b;c?(d=a.b,N(b),b.b=d):c=null!=a.f;d=a.c;if(c)Jb(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(D(e,"./")||D(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],f=0;f<e.length;){var k=e[f++];"."==k?d&&f==e.length&&g.push(""):".."==k?((1<g.length||1==g.length&&""!=
g[0])&&g.pop(),d&&f==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?(N(b),b.c=d):c=""!==a.a.toString();c?Kb(b,Lb(a.a)):c=!!a.i;c&&(a=a.i,N(b),b.i=a);return b};function Ib(a,b,c){N(a);a.h=c?O(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function Jb(a,b){N(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function Kb(a,b,c){N(a);b instanceof Mb?(a.a=b,Sb(a.a,a.g)):(c||(b=Nb(b,Tb)),a.a=new Mb(b,a.g));return a}h.sc=function(a,b){return Kb(this,a,b)};
h.Da=function(){return O(this.a.toString())};h.qb=function(){return this.a.toString()};h.qc=function(a,b){N(this);Array.isArray(b)||(b=[String(b)]);Ub(this.a,a,b);return this};h.ab=function(a){return this.a.m(a)};h.$a=function(a){return this.a.get(a)};h.Jb=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
h.bc=function(){N(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Ia()).toString(36);N(this);this.a.set("zx",a);return this};h.rb=function(a){N(this);this.a.remove(a);return this};h.tc=function(a){this.o=a;return this};h.Ub=function(){return this.o};function N(a){if(a.o)throw Error("Tried to modify a read-only Uri");}h.sb=function(a){this.g=a;this.a&&Sb(this.a,a);return this};
function O(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Nb(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Vb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Vb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Ob=/[#\/\?@]/g,Qb=/[#\?:]/g,Pb=/[#\?]/g,Tb=/[#\?@]/g,Rb=/#/g;function Mb(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function P(a){a.a||(a.a=new Cb,a.b=0,a.c&&Hb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=Mb.prototype;h.ob=function(){P(this);return this.b};h.add=function(a,b){P(this);this.c=null;a=Q(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};h.remove=function(a){P(this);a=Q(this,a);return L(this.a.b,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};h.lb=function(){this.a=this.c=null;this.b=0};
h.pb=function(){P(this);return 0==this.b};function Wb(a,b){P(a);b=Q(a,b);return L(a.a.b,b)}h.mb=function(a){var b=this.m();return 0<=Ka(b,a)};h.forEach=function(a,b){P(this);this.a.forEach(function(c,d){C(c,function(e){a.call(b,e,d,this)},this)},this)};h.A=function(){P(this);for(var a=this.a.m(),b=this.a.A(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
h.m=function(a){P(this);var b=[];if("string"===typeof a)Wb(this,a)&&(b=Ma(b,this.a.get(Q(this,a))));else{a=this.a.m();for(var c=0;c<a.length;c++)b=Ma(b,a[c])}return b};h.set=function(a,b){P(this);this.c=null;a=Q(this,a);Wb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};h.get=function(a,b){if(!a)return b;a=this.m(a);return 0<a.length?String(a[0]):b};function Ub(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(Q(a,b),Na(c)),a.b+=c.length)}
h.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.A(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.m(d);for(var g=0;g<d.length;g++){var f=e;""!==d[g]&&(f+="="+encodeURIComponent(String(d[g])));a.push(f)}}return this.c=a.join("&")};h.qa=function(a){P(this);this.a.forEach(function(b,c){0<=Ka(a,c)||this.remove(c)},this);return this};function Lb(a){var b=new Mb;b.c=a.c;a.a&&(b.a=new Cb(a.a),b.b=a.b);return b}
function Q(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function Sb(a,b){b&&!a.f&&(P(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(this.remove(d),Ub(this,e,c))},a));a.f=b}h.nb=function(a){for(var b=0;b<arguments.length;b++)Fb(arguments[b],function(c,d){this.add(d,c)},this)};var Xb={},Yb={},Zb={};function R(){throw Error("Do not instantiate directly");}R.prototype.T=null;R.prototype.toString=function(){return this.V};R.prototype.a=function(){if(this.D!==Yb)throw Error("Sanitized content was not of kind URI.");return new E(ib,this.toString())};function $b(){R.call(this)}B($b,R);$b.prototype.D=Xb;function ac(a){ac[" "](a);return a}ac[" "]=Ca;function bc(a,b){var c=cc;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var dc=D(F,"Opera"),S=D(F,"Trident")||D(F,"MSIE"),ec=D(F,"Edge"),fc=D(F,"Gecko")&&!(D(F.toLowerCase(),"webkit")&&!D(F,"Edge"))&&!(D(F,"Trident")||D(F,"MSIE"))&&!D(F,"Edge"),gc=D(F.toLowerCase(),"webkit")&&!D(F,"Edge"),hc=D(F,"Macintosh");function ic(){var a=v.document;return a?a.documentMode:void 0}var jc;
a:{var kc="",lc=function(){var a=F;if(fc)return/rv:([^\);]+)(\)|;)/.exec(a);if(ec)return/Edge\/([\d\.]+)/.exec(a);if(S)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(gc)return/WebKit\/(\S+)/.exec(a);if(dc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();lc&&(kc=lc?lc[1]:"");if(S){var mc=ic();if(null!=mc&&mc>parseFloat(kc)){jc=String(mc);break a}}jc=kc}var nc=jc,cc={};
function T(a){return bc(a,function(){for(var b=0,c=Za(String(nc)).split("."),d=Za(String(a)).split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var f=c[g]||"",k=d[g]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==f[0].length&&0==k[0].length)break;b=hb(0==f[1].length?0:parseInt(f[1],10),0==k[1].length?0:parseInt(k[1],10))||hb(0==f[2].length,0==k[2].length)||hb(f[2],k[2]);f=f[3];k=k[3]}while(0==b)}return 0<=b})}var oc;
if(v.document&&S){var pc=ic();oc=pc?pc:parseInt(nc,10)||void 0}else oc=void 0;var qc=oc;var rc=function(a){function b(c){this.V=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.T=d);return c}}($b);function sc(a){return null!=a&&a.D===Xb?String(String(a.V).replace(tc,"").replace(uc,"&lt;")).replace(vc,wc):yb(String(a))}
function xc(a){null!=a&&a.D===Yb||null!=a&&a.D===Zb?a=String(a).replace(yc,zc):a instanceof E?(a=a instanceof E&&a.constructor===E&&a.b===jb?a.a:"type_error:SafeUrl",a=String(a).replace(yc,zc)):a instanceof Ta?a=String(Wa(a).toString()).replace(yc,zc):(a=String(a),a=Ac.test(a)?a.replace(yc,zc):"about:invalid#zSoyz");return a}
var Bc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function wc(a){return Bc[a]}
var Cc={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function zc(a){return Cc[a]}var vc=/[\x00\x22\x27\x3c\x3e]/g,yc=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Ac=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,tc=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,uc=/</g;var Dc=!S||9<=Number(qc),Ec=!fc&&!S||S&&9<=Number(qc)||fc&&T("1.9.1"),Fc=S&&!T("9"),Gc=S||dc||gc;function U(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}h=U.prototype;h.zb=function(){return new U(this.x,this.y)};h.Ab=function(a){return a instanceof U&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
h.Cb=function(a,b){a instanceof U?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),"number"===typeof b&&(this.y+=b));return this};h.Bb=function(a,b){this.x*=a;this.y*="number"===typeof b?b:a;return this};h.jc=function(a,b){a=a*Math.PI/180;b=b||new U(0,0);var c=this.x,d=this.y,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.y)*a+b.x;this.y=(c-b.x)*a+(d-b.y)*e+b.y};function Hc(a,b){this.width=a;this.height=b}h=Hc.prototype;h.Db=function(){return new Hc(this.width,this.height)};h.Sa=function(){return Math.max(this.width,this.height)};h.hb=function(){return Math.min(this.width,this.height)};h.cc=function(){return 2*(this.width+this.height)};h.aspectRatio=function(){return this.width/this.height};h.Eb=function(){return!(this.width*this.height)};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
h.ua=function(a){return this.width<=a.width&&this.height<=a.height};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Ic(a,b){a.width*=b;a.height*=b;return a}h.lc=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Ic(this,a)};
h.mc=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Ic(this,a)};function Jc(a){return a?new Kc(V(a)):Ja||(Ja=new Kc)}function Lc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Mc(document,"*",a,b);return d||null}
function Nc(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var g=d=0,f;f=b[g];g++)e==f.nodeName&&(a[d++]=f);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(g=d=0;f=b[g];g++){e=f.className;var k;if(k="function"==typeof e.split)k=0<=Ka(e.split(/\s+/),c);k&&(a[d++]=f)}a.length=d;return a}return b}
function Mc(a,b,c,d){var e=d||a,g=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(g||c)?e.querySelector(g+(c?"."+c:"")):Nc(a,b,c,d)[0]||null}function Oc(a,b){Oa(b,function(c,d){c&&"object"==typeof c&&c.L&&(c=c.K());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Pc.hasOwnProperty(d)?a.setAttribute(Pc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Pc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Qc(a){a=a.document;a=Rc(a)?a.documentElement:a.body;return new Hc(a.clientWidth,a.clientHeight)}function Sc(a){return a.scrollingElement?a.scrollingElement:!gc&&Rc(a)?a.documentElement:a.body||a.documentElement}
function Tc(a){return a.parentWindow||a.defaultView}function Uc(a,b,c,d){function e(f){f&&b.appendChild("string"===typeof f?a.createTextNode(f):f)}for(;d<c.length;d++){var g=c[d];w(g)&&!Vc(g)?C(Wc(g)?Na(g):g,e):e(g)}}function W(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function Rc(a){return"CSS1Compat"==a.compatMode}function Xc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function Yc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Zc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Vc(a){return z(a)&&0<a.nodeType}function $c(a){return z(a)&&1==a.nodeType}function ad(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function bd(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return cd(b,a)}function cd(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function V(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function dd(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Xc(a),a.appendChild(V(a).createTextNode(String(b)))}function ed(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||ed(a,b,c,d))return!0;a=a.nextSibling}return!1}var fd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},gd={IMG:" ",BR:"\n"};
function hd(a){return id(a)&&jd(a)}function id(a){return S&&!T("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function jd(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function kd(a){if(Fc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];ld(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Fc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function ld(a,b,c){if(!(a.nodeName in fd))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in gd)b.push(gd[a.nodeName]);else for(a=a.firstChild;a;)ld(a,b,c),a=a.nextSibling}function Wc(a){if(a&&"number"==typeof a.length){if(z(a))return"function"==typeof a.item||"string"==typeof a.item;if(Ea(a))return"function"==typeof a.item}return!1}
function md(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return nd(a,function(g){var f;(f=!e||g.nodeName==e)&&!(f=!c)&&(f="string"===typeof g.className)&&(f=0<=Ka(g.className.split(/\s+/),c));return f},!0,d)}function nd(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function Kc(a){this.a=a||v.document||document}h=Kc.prototype;h.Ja=Jc;h.nc=function(a){this.a=a};h.Fa=function(){return this.a};
h.ca=function(a){return"string"===typeof a?this.a.getElementById(a):a};h.fb=function(a){return"string"===typeof a?this.a.getElementById(a):a};h.ia=Kc.prototype.ca;h.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};h.da=function(a,b,c){return Nc(this.a,a,b,c)};h.La=function(a,b,c){return Mc(this.a,a,b,c)};h.Ma=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Nc(document,"*",a,b)};
h.Ka=function(a,b){return Lc(a,b||this.a)};h.gb=function(a,b){return Lc(a,b||this.a)};h.ja=Kc.prototype.da;h.rc=Oc;h.kb=function(a){return Qc(a||Tc(this.a)||window)};h.Ga=function(){var a=Tc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Qc(a).height,Rc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
h.aa=function(a,b,c){var d=this.a,e=arguments,g=String(e[0]),f=e[1];if(!Dc&&f&&(f.name||f.type)){g=["<",g];f.name&&g.push(' name="',yb(f.name),'"');if(f.type){g.push(' type="',yb(f.type),'"');var k={};Sa(k,f);delete k.type;f=k}g.push(">");g=g.join("")}g=W(d,g);f&&("string"===typeof f?g.className=f:Array.isArray(f)?g.className=f.join(" "):Oc(g,f));2<e.length&&Uc(d,g,e,2);return g};h.ka=Kc.prototype.aa;h.wb=function(a){return this.a.createTextNode(String(a))};
h.oa=function(a,b,c){var d=this.a;c=!!c;for(var e=W(d,"TABLE"),g=e.appendChild(W(d,"TBODY")),f=0;f<a;f++){for(var k=W(d,"TR"),l=0;l<b;l++){var m=W(d,"TD");c&&dd(m,"\u00a0");k.appendChild(m)}g.appendChild(k)}return e};h.kc=function(a){var b=this.a;var c=W(b,"DIV");S?(a=sb(vb,a),xb(c,a),c.removeChild(c.firstChild)):xb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};h.Ob=function(){return Rc(this.a)};
h.Ia=function(){return Sc(this.a)};h.Ha=function(){var a=this.a,b=Sc(a);a=Tc(a);return S&&T("10")&&a.pageYOffset!=b.scrollTop?new U(b.scrollLeft,b.scrollTop):new U(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};h.xa=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};h.appendChild=function(a,b){a.appendChild(b)};h.append=function(a,b){Uc(V(a),a,arguments,1)};h.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.ic=Xc;h.Nb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};h.Mb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};h.Lb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};h.removeNode=Yc;h.xb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};h.va=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Yc(a)}};
h.Ca=function(a){return Ec&&void 0!=a.children?a.children:La(a.childNodes,function(b){return 1==b.nodeType})};h.Na=function(a){return void 0!==a.firstElementChild?a.firstElementChild:Zc(a.firstChild,!0)};h.Ra=function(a){return void 0!==a.lastElementChild?a.lastElementChild:Zc(a.lastChild,!1)};h.Ta=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:Zc(a.nextSibling,!0)};h.cb=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:Zc(a.previousSibling,!1)};
h.Ua=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};h.eb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};h.Sb=Vc;h.Pb=$c;h.Vb=function(a){return z(a)&&a.window==a};h.bb=function(a){var b;if(Gc&&!(S&&T("9")&&!T("10")&&v.SVGElement&&a instanceof v.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return $c(b)?b:null};
h.vb=ad;
h.na=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(S&&!(9<=Number(qc))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,g=b.parentNode;return e==g?cd(a,b):!c&&ad(e,b)?-1*bd(a,b):!d&&ad(g,a)?bd(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:g.sourceIndex)}d=V(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(v.Range.START_TO_END,a)};h.ra=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var g=[],f=arguments[b];f;)g.unshift(f),f=f.parentNode;d.push(g);e=Math.min(e,g.length)}g=null;for(b=0;b<e;b++){f=d[0][b];for(var k=1;k<c;k++)if(f!=d[k][b])return g;g=f}return g};h.Za=V;h.Oa=function(a){return a.contentDocument||a.contentWindow.document};
h.Pa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Tc(c):window}else d=null;b=d}return b}catch(e){}return null};h.uc=dd;h.Ya=function(a){if("outerHTML"in a)return a.outerHTML;var b=W(V(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};h.sa=function(a,b){var c=[];return ed(a,b,c,!0)?c[0]:void 0};h.ta=function(a,b){var c=[];ed(a,b,c,!1);return c};h.Rb=hd;h.pc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
h.Qb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!id(a)||jd(a)):hd(a))&&S){var c;!Ea(a.getBoundingClientRect)||S&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};h.ib=kd;h.Wa=function(a){return kd(a).length};
h.Xa=function(a,b){b=b||V(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(kd(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
h.Va=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in fd))if(3==e.nodeType){var g=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=g.length}else if(e.nodeName in gd)d+=gd[e.nodeName].length;else for(g=e.childNodes.length-1;0<=g;g--)a.push(e.childNodes[g]);z(c)&&(c.hc=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};h.Tb=Wc;h.Aa=md;h.za=function(a,b,c){return md(a,null,b,c)};h.ya=nd;h.Ba=function(a){return a.getContext("2d")};function od(a){a=(a||pd).$;var b=a[0].imageUrl;var c=a[0].servePath,d=a[0].dc,e=a[0].ec,g=a[0].Kb,f=a[0].shareTitle,k=a[0].shareDescription;a=rc('<div class="devsite-badger-award"><div class="devsite-badger-award-inner"><devsite-badge-awarded badge-name="'+sc(a[0].title)+'" badge-icon-url="'+sc(xc(b))+'"'+(c?' badge-path="'+sc(c)+'"':"")+(f?' badge-share-title="'+sc(f)+'"':"")+(k?' badge-share-description="'+sc(k)+'"':"")+(d?' playlist-return-url="'+sc(xc(d))+'"':"")+(e?" redeem-another":"")+(g?" hide-buttons":
"")+" dismiss></devsite-badge-awarded></div></div>");b=rc(a);a=Jc();a=W(a.a,"DIV");if(z(b))if(b instanceof R){if(b.D!==Xb)throw Error("Sanitized content was not of kind HTML.");b=tb(b.toString(),b.T||null)}else b=ob("zSoyz");else b=ob(String(b));xb(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var pd={};var qd={};function rd(a,b){var c=qd[a];if(void 0!==c&&(!c.S||Date.now()<=c.S+3E5))return c.p;c=new Promise(function(e,g){b.onload=function(){return e(b)};b.onerror=function(f){b.parentNode&&b.parentNode.removeChild(b);g(f)};document.head.appendChild(b)});var d={S:0,p:c};c.catch(function(){return d.S=+new Date});qd[a]=d;return c}function sd(a){a=void 0===a?0:a;return new Promise(function(b){setTimeout(b,a)})};var td=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(td&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function ud(a){var b=HTMLElement.call(this)||this;a&&vd(a);return b}la(ud,HTMLElement);ud.prototype.Y=function(){console.warn(this.tagName,"has not implemented update")};ud.prototype.o=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
ud.prototype.X=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function vd(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var wd=new Map;function X(a){var b=ud.call(this)||this;a&&vd(a);return b}la(X,ud);X.prototype.connectedCallback=function(){var a=this.constructor,b=wd.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):wd.set(a,this)};X.prototype.disconnectedCallback=function(){var a=this.constructor;wd.get(a)===this&&wd.delete(a)};X.prototype.disconnectedCallback=X.prototype.disconnectedCallback;X.prototype.connectedCallback=X.prototype.connectedCallback;function xd(){var a,b,c;return t(function(d){switch(d.a){case 1:if(Ba("__globalHafezClient"))return d.return(Ba("__globalHafezClient"));if(a=Ba("__globalHafezClientLoaderPromise")){d.B(2);break}return r(d,DevsiteApp.whenReady(),3);case 3:b=new URL(DevsiteApp.getStaticPath()+"/js/hafez_client.js",document.location.origin);var e=void 0===e?null:e;var g=b.href;g=g instanceof M?new M(g):new M(g,void 0);var f=document.createElement("script");f.src=g.toString();e&&(f.type=e);e=a=rd(g.toString(),f);g=["__globalHafezClientLoaderPromise"];
f=v;g[0]in f||"undefined"==typeof f.execScript||f.execScript("var "+g[0]);for(var k;g.length&&(k=g.shift());)g.length||void 0===e?f[k]&&f[k]!==Object.prototype[k]?f=f[k]:f=f[k]={}:f[k]=e;case 2:return d.c=4,r(d,a,6);case 6:ra(d,5);break;case 4:return sa(d),d.return(null);case 5:return(c=Ba("__globalHafezClient"))?d.return(c):d.return(null)}})};function yd(){this.C=this.C;this.b=this.b}h=yd.prototype;h.C=!1;h.ga=function(){return this.C};h.Ea=yd.prototype.ga;h.U=function(){this.C||(this.C=!0,this.F())};h.fc=function(a){a=Ha(zd,a);this.C?a():(this.b||(this.b=[]),this.b.push(a))};h.F=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function zd(a){a&&"function"==typeof a.U&&a.U()};function Ad(a,b){this.type=a;this.a=this.target=b;this.defaultPrevented=this.c=!1}Ad.prototype.f=function(){this.c=!0};Ad.prototype.b=function(){this.defaultPrevented=!0};var Bd=!S||9<=Number(qc),Cd=!S||9<=Number(qc),Dd=S&&!T("9"),Ed=function(){if(!v.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{v.addEventListener("test",Ca,b),v.removeEventListener("test",Ca,b)}catch(c){}return a}();function Y(a,b){Ad.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.j=this.i=0;this.key="";this.g=this.h=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.o=!1;this.pointerId=0;this.pointerType="";this.v=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;if(b=a.relatedTarget){if(fc){a:{try{ac(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.i=gc||void 0!==a.offsetX?a.offsetX:a.layerX,this.j=gc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.h=a.keyCode||0;this.key=a.key||"";this.g=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.o=hc?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Fd[a.pointerType]||"";this.state=a.state;this.v=a;a.defaultPrevented&&this.b()}}B(Y,Ad);var Gd=[1,4,2],Fd={2:"touch",3:"pen",4:"mouse"};
Y.prototype.R=function(){return(Bd?0==this.v.button:"click"==this.type?!0:!!(this.v.button&Gd[0]))&&!(hc&&this.ctrlKey)};Y.prototype.f=function(){Y.I.f.call(this);this.v.stopPropagation?this.v.stopPropagation():this.v.cancelBubble=!0};Y.prototype.b=function(){Y.I.b.call(this);var a=this.v;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Dd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Hd="closure_listenable_"+(1E6*Math.random()|0),Id=0;function Jd(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Id;this.H=this.N=!1}function Kd(a){a.H=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Ld(a){this.src=a;this.a={};this.b=0}Ld.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};Ld.prototype.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var f=Md(a,b,d,e);-1<f?(b=a[f],c||(b.N=!1)):(b=new Jd(b,this.src,g,!!d,e),b.N=c,a.push(b));return b};
Ld.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Md(e,b,c,d);return-1<b?(Kd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};function Nd(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=Ka(d,b),g;(g=0<=e)&&Array.prototype.splice.call(d,e,1);g&&(Kd(b),0==a.a[c].length&&(delete a.a[c],a.b--))}}
function Md(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.H&&g.listener==b&&g.capture==!!c&&g.b==d)return e}return-1};var Od="closure_lm_"+(1E6*Math.random()|0),Pd={},Qd=0;function Rd(a,b,c,d,e){if(d&&d.once)return Sd(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)Rd(a,b[g],c,d,e);return null}c=Td(c);return a&&a[Hd]?a.i.add(String(b),c,!1,z(d)?!!d.capture:!!d,e):Ud(a,b,c,!1,d,e)}
function Ud(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var f=z(e)?!!e.capture:!!e,k=Vd(a);k||(a[Od]=k=new Ld(a));c=k.add(b,c,d,f,g);if(c.a)return c;d=Wd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Ed||(e=f),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Xd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Qd++;return c}
function Wd(){var a=Yd,b=Cd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Sd(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)Sd(a,b[g],c,d,e);return null}c=Td(c);return a&&a[Hd]?a.i.add(String(b),c,!0,z(d)?!!d.capture:!!d,e):Ud(a,b,c,!0,d,e)}
function Zd(a){if("number"!==typeof a&&a&&!a.H){var b=a.src;if(b&&b[Hd])Nd(b.i,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Xd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Qd--;(c=Vd(b))?(Nd(c,a),0==c.b&&(c.src=null,b[Od]=null)):Kd(a)}}}function Xd(a){return a in Pd?Pd[a]:Pd[a]="on"+a}
function $d(a,b,c,d){var e=!0;if(a=Vd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.H&&(g=ae(g,d),e=e&&!1!==g)}return e}function ae(a,b){var c=a.listener,d=a.b||a.src;a.N&&Zd(a);return c.call(d,b)}
function Yd(a,b){if(a.H)return!0;if(!Cd){var c=b||Ba("window.event");b=new Y(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(f){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.a;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.a=c[e];var g=$d(c[e],a,!0,b);d=d&&g}for(e=0;!b.c&&e<c.length;e++)b.a=c[e],g=$d(c[e],a,!1,b),d=d&&g}return d}return ae(a,new Y(b,this))}
function Vd(a){a=a[Od];return a instanceof Ld?a:null}var be="__closure_events_fn_"+(1E9*Math.random()>>>0);function Td(a){if(Ea(a))return a;a[be]||(a[be]=function(b){return a.handleEvent(b)});return a[be]};function ce(a,b){if(!Ea(a))if(a&&"function"==typeof a.handleEvent)a=A(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:v.setTimeout(a,b||0)};function de(a,b,c){yd.call(this);this.o=null!=c?A(a,c):a;this.j=b;this.i=A(this.ha,this);this.c=!1;this.f=0;this.g=this.a=null;this.h=[]}B(de,yd);h=de.prototype;h.O=function(a){this.h=arguments;this.c=!1;this.a?this.g=Ia()+this.j:this.a=ce(this.i,this.j)};h.tb=function(){++this.f};h.ub=function(){this.f&&(--this.f,!this.f&&this.c&&(this.c=!1,this.o.apply(null,this.h)))};h.F=function(){this.a&&(v.clearTimeout(this.a),this.a=null);this.g=null;this.c=!1;this.h=[];de.I.F.call(this)};
h.ha=function(){this.g?(this.a=ce(this.i,this.g-Ia()),this.g=null):(this.a=null,this.f?this.c=!0:(this.c=!1,this.o.apply(null,this.h)))};function ee(a){yd.call(this);this.c=a;this.a={}}B(ee,yd);var fe=[];function ge(a,b,c,d){he(a,b,c,d,void 0)}h=ee.prototype;h.Zb=function(a,b,c,d,e){return he(this,a,b,c,d,e)};function he(a,b,c,d,e,g){Array.isArray(c)||(c&&(fe[0]=c.toString()),c=fe);for(var f=0;f<c.length;f++){var k=Rd(b,c[f],d||a.handleEvent,e||!1,g||a.c||a);if(!k)break;a.a[k.key]=k}return a}function ie(a,b,c){je(a,b,"running",c,void 0)}h.Yb=function(a,b,c,d,e){return je(this,a,b,c,d,e)};
function je(a,b,c,d,e,g){if(Array.isArray(c))for(var f=0;f<c.length;f++)je(a,b,c[f],d,e,g);else{b=Sd(b,c,d||a.handleEvent,e,g||a.c||a);if(!b)return a;a.a[b.key]=b}return a}h.$b=function(a,b,c,d){b.a(a,c,d,this.c||this,this);return this};h.ac=function(a,b,c,d,e){b.a(a,c,d,e||this.c||this,this);return this};h.yb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};h.xc=function(a,b,c,d,e){b.b(a,c,d,e||this.c||this,this);return this};
function ke(a){Oa(a.a,function(b,c){this.a.hasOwnProperty(c)&&Zd(b)},a);a.a={}}h.F=function(){ee.I.F.call(this);ke(this)};h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function le(){};function me(){}B(me,le);me.prototype.fa=function(){var a=0;Ab(this.u(!0),function(){a++});return a};me.prototype.ea=function(){var a=Bb(this.u(!0)),b=this;C(a,function(c){b.remove(c)})};function ne(a){this.a=a}B(ne,me);function oe(a){if(!a.a)return!1;try{return a.a.setItem("__sak","1"),a.a.removeItem("__sak"),!0}catch(b){return!1}}h=ne.prototype;h.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};h.get=function(a){a=this.a.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};h.remove=function(a){this.a.removeItem(a)};
h.fa=function(){return this.a.length};h.u=function(a){var b=0,c=this.a,d=new I;d.next=function(){if(b>=c.length)throw H;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};return d};h.ea=function(){this.a.clear()};h.key=function(a){return this.a.key(a)};function pe(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}B(pe,ne);function Z(){var a=X.call(this,["devsite-badge-awarded"])||this;a.c=new ee;a.b=new pe;a.a=null;a.f=[];a.h=null;a.R=-1;a.j=null;a.g=new de(function(){return void qe(a)},250);return a}la(Z,X);function re(a){var b;return t(function(c){if(1==c.a){if(a.h)return c.B(2);b=a;return r(c,xd(),3)}2!=c.a&&(b.h=c.g);return c.return(a.h)})}Z.prototype.disconnectedCallback=function(){ke(this.c);se(this)};function te(){return"devsite-badger"}
Z.prototype.connectedCallback=function(){var a=this;ue(this);ve(this).then(function(b){b||Yc(a)}).catch(function(){Yc(a)})};function ve(a){var b;return t(function(c){if(1==c.a)return oe(a.b)?r(c,re(a),2):c.return(!1);if(3!=c.a){b=c.g;if(!b)return c.return(!1);vd(["devsite-badge-awarded"]);return r(c,window.customElements.whenDefined("devsite-badge-awarded"),3)}return c.return(!0)})}
function ue(a){ge(a.c,document.body,"devsite-before-page-change",function(){return void se(a)});ge(a.c,document.body,"devsite-award-granted",function(b){(b=b.v)&&b.detail&&(a.f.push(b.detail.award),a.g.O())});ge(a.c,document.body,["devsite-page-loaded","devsite-page-changed"],function(){we(a);a:if(oe(a.b)){var b=a.b.get("temp_badge");if(b){try{var c=JSON.parse(b)}catch(e){a.b.remove("temp_badge");break a}if(3>c.displayCount){a.b.set("temp_badge",JSON.stringify(c));b=new URL(c.awardUrl,document.location.origin);
var d=new URL(document.location.toString());b.origin===d.origin&&b.pathname===d.pathname&&(a.f.push(c),a.g.O())}else a.b.remove("temp_badge")}}})}
function we(a){var b,c,d,e,g;t(function(f){switch(f.a){case 1:return f.c=2,r(f,ve(a),4);case 4:b=f.g;if(!b)return f.return();ra(f,3);break;case 2:return sa(f),f.return();case 3:return r(f,re(a),5);case 5:c=f.g;if(!c)return f.return();d=!1;f.c=6;return r(f,c.hasWallet(),8);case 8:d=f.g;ra(f,7);break;case 6:sa(f);case 7:return d?r(f,window.customElements.whenDefined("devsite-user"),9):f.return();case 9:e=document.querySelector("devsite-user#devsite-user");if(!e){f.B(0);break}g=!1;f.c=11;return r(f,
e.isSignedIn(),13);case 13:g=f.g;ra(f,12);break;case 11:sa(f);case 12:if(g)return r(f,c.getProfile(),0);f.B(0)}})}
function qe(a){var b,c,d;return t(function(e){switch(e.a){case 1:if(a.a||0===a.f.length)return e.return();e.c=2;return r(e,window.customElements.whenDefined("devsite-badge-awarded"),4);case 4:ra(e,3);break;case 2:sa(e);case 3:b=a.f.splice(0,1);c=od({$:b});if(!c)return e.return();ge(a.c,c,"click",function(g){(g=g.target)&&g.matches("button.dismiss")&&se(a)});a.a=c;(d=c.querySelector("devsite-badge-awarded"))?(ie(a.c,d,function(){xe(a)}),document.body.appendChild(a.a)):(document.body.appendChild(a.a),
xe(a));e.a=0}})}function xe(a){t(function(b){a.a.setAttribute("show","");b.a=0})}function se(a){return t(function(b){if(1==b.a){if(!a.a)return b.return();a.b.remove("temp_badge");a.a.removeAttribute("show");return r(b,sd(200),2)}if(3!=b.a)return Yc(a.a),a.a=null,r(b,sd(250),3);a.g.O();b.a=0})}Z.prototype.connectedCallback=Z.prototype.connectedCallback;Z.getTagName=te;Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;try{window.customElements.define(te(),Z)}catch(a){console.warn("devsite.app.customElement.DevsiteBadger",a)};}).call(this);
