// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 24
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){
var aa;var __dee;(function(){(function(a){__dee=a;__dee.a="dee";__dee.b=["google"];__dee.c=!0})(function(){var a=!1;return a?"gtm.sync":"gtm.js"})})();

var __c;(function(){(function(a){__c=a;__c.a="c";__c.b=["google"];__c.c=!0})(function(a){return a["45"]})})();var __e;(function(){(function(a){__e=a;__e.a="e";__e.b=["google"];__e.c=!0})(function(){return Ha})})();



var __u;(function(){var a=function(a){return{toString:function(){return a}}};(function(a){__u=a;__u.a="u";__u.b=["google"];__u.c=!0})(function(b){var d;d=(d=b[""]?b[""]:S("gtm.url",1))||ia();var c=b[a("28")];if(!c||"URL"==c)return Sa(Ra(String(d)));var e=Ra(String(d)),f;if("QUERY"==c&&b[a("")])a:{var g=b[a("")],h;h=Ma(g)?g:String(g||"").replace(/\s+/g,"").split(",");for(var k=
0;k<h.length;k++){var l=Z(e,"QUERY",void 0,void 0,h[k]);if(null!=l){f=l;break a}}f=void 0}else f=Z(e,c,"HOST"==c?b[a("")]:void 0,"PATH"==c?b[a("")]:void 0,"QUERY"==c?b[a("")]:void 0);return f})})();
var __ctto;(function(){(function(a){__ctto=a;__ctto.a="ctto";__ctto.b=["google"];__ctto.c=!0})(function(){var a=w("dataLayer"),b=a&&a.hide;if(!b)return!1;var d=Wa.f,c=w("document");if(void 0===c.querySelector)return!1;var e=!!c.querySelector("body");return null===b.end&&e&&!0===b[d]})})();
var __ua;(function(){var a,b=function(b){var c={},d={},f={},g={},h={};if(b[""]){var k=b[""];Xa(Q(k["35"],"fieldName","value"),d);Xa(Q(k[""],"index","group"),f);Xa(Q(k[""],"index","dimension"),g);Xa(Q(k[""],"index","metric"),h);b[""]=null;k["35"]=void 0;k[""]=void 0;k[""]=void 0;
k[""]=void 0;var l=Ya(k,void 0);b=Ya(b,l)}Xa(Q(b["35"],"fieldName","value"),d);Xa(Q(b[""],"index","group"),f);Xa(Q(b[""],"index","dimension"),g);Xa(Q(b[""],"index","metric"),h);var m=$a(b[""]);if(T(m)){var n="",p="";b["39"]&&"string"==typeof b["42"]?""!==b["42"]&&(p=b["42"],n=p+
"."):(p=ab(),n=p+".");var q={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0,useAmpClientId:!0,storeGac:!0},u={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,storeGac:!0,
allowAdFeatures:!0},t=function(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];m.apply(window,b)},v=function(a,b){return void 0===b?b:a(b)},F=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&t("set",a+c,b[c])},D=function(){},E=function(a,b,c){var d=0;if(a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&q[e]||!c&&void 0===q[e])){var f=u[e]?cb(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d},J={name:p};E(d,J,!0);m("create",b["43"]||c.trackingId,J);t("set","&gtm",Ga(!0));b[""]&&t("require","recaptcha","recaptcha.js");(function(a,c){void 0!==b[c]&&t("set",
a,b[c])})("nonInteraction","");F("contentGroup",f);F("dimension",g);F("metric",h);var K={};E(d,K,!1)&&t("set",K);var G;G=b["37"];b[""]&&t("require","linkid","linkid.js");t("set","hitCallback",function(){var a=d&&d.hitCallback;T(a)&&a();b["46"]()});if("TRACK_EVENT"==
b["40"]){}else if("TRACK_SOCIAL"==
b["40"]){}else if("TRACK_TRANSACTION"==b["40"]){}else if("TRACK_TIMING"==
b["40"]){}else if("DECORATE_LINK"==b["40"]){}else if("DECORATE_FORM"==b["40"]){}else if("TRACK_DATA"==b["40"]){G?t("send","data",G):t("send","data");}else{b[""]&&(t("require","ec","ec.js"),D());if(b[""]||
"DISPLAY_FEATURES"==b[""]){var W="_dc_gtm_"+String(b["43"]).replace(/[^A-Za-z0-9-]/g,"");t("require","displayfeatures",void 0,{cookieName:W})}if("DISPLAY_FEATURES_WITH_REMARKETING_LISTS"==b[""]){var P="_dc_gtm_"+String(b["43"]).replace(/[^A-Za-z0-9-]/g,"");t("require","adfeatures",{cookieName:P})}G?t("send","pageview",G):t("send","pageview");}if(!a){var ra=b[""]?"u/analytics_debug.js":"analytics.js";b[""]&&!b[""]&&(ra="internal/"+ra);a=!0;ha(A("https:","http:","//www.google-analytics.com/"+ra,d&&d.forceSSL),function(){var a=eb();a&&a.loaded||
b["47"]();},b["47"])}}else y(b["47"])};__ua=b;__ua.a="ua";__ua.b=["google"];__ua.c=!0})();
var __dr;(function(){(function(a){__dr=a;__dr.a="dr";__dr.b=["google"];__dr.c=!0})(function(a){var b=a["44"],d=a["27"],c=a[""],e=a[""],f=S("optimize.experimentCallback",1),g=a["38"],h=a["34"],k;if(k=d){var l=ib[g];k=!(!l||l==b)}if(k)a["47"]();else{var m=S("optimize.whitelist",1);if(m&&m[g]?m[g]===c:jb()?e:1){if(T(f)){var n={xid:g,xvar:h,
activate:d};try{f(n)}catch(D){}}var p=!1,q=!0;d?kb(b,g)?p=!0:lb(b):q=mb(b);if(q){var u=d?h:void 0;nb[g]=u;for(var t=ob(g),v=0;v<t.length;v++)pb(t[v],g,u);t=ob("");for(var F=0;F<t.length;F++)pb(t[F],g,u)}a[p?"47":"46"]()}else a["47"]()}})})();
var __gthc;(function(){(function(a){__gthc=a;__gthc.a="gthc";__gthc.b=["google"];__gthc.c=!0})(function(a){var b=w("gaData",{});if(cb("true")){var d=a["43"];return b[d]&&b[d].hitcount?b[d].hitcount:0}return-1})})();



var __asprv;(function(){(function(a){__asprv=a;__asprv.a="asprv";__asprv.b=["google"];__asprv.c=!0})(function(a){var b=a["36"],d=S("eventModel");b&&Cb(b);var c,e,f;d&&(c=d.name||"",e=d.callback,f=d.remove);if(e&&T(e))if(c=String(c),!0!==f){var g=c,h=e;ob(g).push(h);if(""!==g)void 0!==nb[g]&&pb(h,g,nb[g]);else for(var k in nb)void 0!==nb[k]&&pb(h,k,nb[k])}else{var l=e,m=ob(c),n=m.indexOf(l);0<=n&&m.splice(n,1)}})})();












var rc=this,uc=function(){if(null===sc)a:{var a=rc.document,b=a.querySelector&&a.querySelector("script[nonce]");if(b){var d=b.nonce||b.getAttribute("nonce");if(d&&tc.test(d)){sc=d;break a}}sc=""}return sc},tc=/^[\w+/_-]+[=]{0,2}$/,sc=null;var Hb=function(){throw Error("Not supported in V1");};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var vc=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,wc=function(a){if(null==a)return String(a);var b=vc.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},xc=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Na=function(a){if(!a||"object"!=wc(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!xc(a,"constructor")&&!xc(a.constructor.prototype,"isPrototypeOf"))return!1}catch(d){return!1}for(var b in a);return void 0===
b||xc(a,b)},Ya=function(a,b){var d=b||("array"==wc(a)?[]:{}),c;for(c in a)if(xc(a,c)){var e=a[c];"array"==wc(e)?("array"!=wc(d[c])&&(d[c]=[]),d[c]=Ya(e,d[c])):Na(e)?(Na(d[c])||(d[c]={}),d[c]=Ya(e,d[c])):d[c]=e}return d};var Wa={},ec=null,yc=Math.random();Wa.f="GTM-KFRPN4V";Wa.Ia="1d1";var zc=null,Ha=null,Rb=!1,Ac="//www.googletagmanager.com/a?id="+Wa.f+"&cv=24",Bc={},Cc={},Sb={};var Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,Db,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Eb,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,
Kf,Lf,Mf,Nf,Of,Pf,Qf,Rf,Sf,Tf,Uf,Vf,Wf,Xf,Yf,Zf,$f,ag,bg,cg,dg,eg,fg,gg,hg,ig,jg,kg,lg,mg,ng,og,pg,qg,rg,sg,tg,ug,vg,wg,xg,yg,zg,Ag;
(function(){var a=function(a){return{toString:function(){return a}}};Dc=a("");Ec=a("0");Fc="";Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("1");Pc=a("2");Qc=a("");Rc=a("");Sc=a("");
Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");fd=a("");gd=a("");
hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("3");wd=a("");xd=a("");
yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");
Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");
ee=a("");fe=a("");ge=a("");he=a("");ie=a("5");je=a("4");ke=a("8");le=a("7");me=a("");ne=a("");oe=a("");Db=a("9");pe=a("");qe=a("46");re=a("47");se=a("");te=a("");
ue=a("10");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Eb=a("11");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("12");Me=a("");
Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("13");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("14");$e=a("");af=a("");bf=a("16");cf=a("");df=a("");ef=a("");ff=a("");
gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("");of=a("");pf=a("");qf=a("");rf=a("");sf=a("");tf=a("");uf=a("");vf=a("");wf=a("");xf=a("");yf=a("");zf=a("");
Af=a("");Bf=a("18");Cf=a("");Df=a("");Ef=a("");Ff=a("20");Gf=a("");Hf=a("");If=a("");Jf=a("");Kf=a("");Lf=a("");Mf=a("");Nf=a("");Of=a("21");Pf=
a("22");Qf=a("23");Rf=a("24");Sf=a("");Tf=a("");Uf=a("");Vf=a("");Wf=a("");Xf=a("");Yf=a("");Zf=a("");$f=a("");ag=a("");bg=a("");cg=a("");dg=a("");eg=a("");
fg=a("");gg=a("");hg=a("");ig=a("");jg=a("");kg="";lg=a("");mg=a("");ng=a("");og=a("");pg=a("");qg=a("");rg=a("");sg=a("");tg=a("");ug=a("");vg=a("");wg=
a("25");xg=a("");yg=a("");zg=a("");Ag=a("")})();var qc=function(a,b){Ya(a,b)},Bg=function(){},T=function(a){return"function"==typeof a},Ma=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Cg=function(a){return"number"==wc(a)&&!isNaN(a)},Dg=function(a){return/^[0-9]+$/.test(a)},sa=function(a){return"string"==wc(a)},Ua=function(a,b){if(Array.prototype.indexOf){var d=a.indexOf(b);return"number"==typeof d?d:-1}for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1},Eg=function(a,b){if(a&&Ma(a)&&0!=a.length)for(var d=
0;d<a.length;d++)if(a[d]&&b(a[d]))return a[d]},Qa=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},r=function(a){return Math.round(Number(a))||0},cb=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Fg=function(a){var b=[];if(Ma(a))for(var d=0;d<a.length;d++)b.push(String(a[d]));return b},Pb=function(){return new Date},Va=function(a,b){if(!Cg(a)||!Cg(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Gg=function(){this.prefix="gtm.";this.values={}};
Gg.prototype.set=function(a,b){this.values[this.prefix+a]=b};Gg.prototype.get=function(a){return this.values[this.prefix+a]};Gg.prototype.contains=function(a){return void 0!==this.get(a)};
var Hg=function(a,b,d,c){try{if(!a[Pe])return a[Db](a,b||Bg,d||Bg);d&&d()}catch(e){c&&c()}return!1},Ig=function(a,b){function d(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var c=Qa(b).split("&"),e=0;e<c.length;e++)if(c[e]){var f=c[e].indexOf("=");0>f?d(c[e],"1"):d(c[e].substring(0,f),c[e].substring(f+1))}},Jg=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Kg=function(a){var b=Wa.f;return function(){return a(b)}},Lg=function(a){for(var b=0;b<a.length;b++)a[b]()},ab=function(){return"gtm"+
Mg()},Mg=function(){var a=ec.sequence||0;ec.sequence=a+1;return a},bb=function(a,b,d){return a&&a.hasOwnProperty(b)?a[b]:d},Ng=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Og=function(a,b){0==b?a.rc=!0:a.ta=!0;var d=a.s;a.I&&(a.I.yb[d]=b);Bc[d]&&(Bc[d].state=b)},Pg=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},Qg=function(a,b){a.sort(function(a,c){return b(a,c)?-1:b(c,a)?1:0})};var cc=function(a,b){for(var d=[],c=0;c<a.length;c++)d.push(a[c]),d.push.apply(d,b[a[c]]||[]);return d};var B=window,M=document,Sg=navigator,Ob=function(a,b){var d=B[a];B[a]=void 0===d?b:d;return B[a]},Qb=function(a,b,d,c){return(c||"http:"!=B.location.protocol?a:b)+d},fc=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},x=function(a,b,d){var c=M.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;fc(c,b);d&&(c.onerror=d);uc()&&c.setAttribute("nonce",uc());var e=M,f=e.getElementsByTagName("script")[0]||
e.body||e.head;f.parentNode.insertBefore(c,f);return c},Bb=function(a,b){var d=M.createElement("iframe");d.height="0";d.width="0";d.style.display="none";d.style.visibility="hidden";var c=M,e=c.body&&c.body.lastChild||c.body||c.head;e.parentNode.insertBefore(d,e);fc(d,b);void 0!==a&&(d.src=a);return d},C=function(a,b,d){var c=new Image(1,1);c.onload=function(){c.onload=null;b&&b()};c.onerror=function(){c.onerror=null;d&&d()};c.src=a},Ba=function(a,b,d,c){a.addEventListener?a.addEventListener(b,d,!!c):
a.attachEvent&&a.attachEvent("on"+b,d)},ya=function(a,b,d,c){a.removeEventListener?a.removeEventListener(b,d,!!c):a.detachEvent&&a.detachEvent("on"+b,d)},y=function(a){B.setTimeout(a,0)},Tg=!1,Ug=[],Vg=function(a){if(!Tg){var b=M.createEventObject,d="complete"==M.readyState,c="interactive"==M.readyState;if(!a||"readystatechange"!=a.type||d||!b&&c){Tg=!0;for(var e=0;e<Ug.length;e++)y(Ug[e])}Ug.push=function(){for(var a=0;a<arguments.length;a++)y(arguments[a]);return 0}}},Wg=0,Xg=function(){if(!Tg&&
140>Wg){Wg++;try{M.documentElement.doScroll("left"),Vg()}catch(a){B.setTimeout(Xg,50)}}},la=function(a){var b=M.getElementById(a);if(b&&Oa(b,"id")!=a)for(var d=1;d<document.all[a].length;d++)if(Oa(document.all[a][d],"id")==a)return document.all[a][d];return b},Oa=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Yg=function(a){return a.target||a.srcElement||{}},Pa=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));
b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},ic=function(a){var b=M.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var d=[];b.firstChild;)d.push(b.removeChild(b.firstChild));return d},Zg=function(a,b,d){d=d||100;for(var c={},e=0;e<b.length;e++)c[b[e]]=!0;var f=a;for(e=0;f&&e<=d;e++){if(c[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},$g=!1,ah=[],bh=function(){if(!$g){$g=!0;for(var a=0;a<ah.length;a++)y(ah[a])}},ch=function(a){a=a||B;var b=
a.location.href,d=b.indexOf("#");return 0>d?"":b.substring(d+1)},Ib=function(a){window.console&&window.console.log&&window.console.log(a)};var dh=function(a,b){for(var d=a.split("&"),c=0;c<d.length;c++){var e=d[c].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},Z=function(a,b,d,c,e){var f,g=(a.protocol.replace(":","")||B.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":f=Sa(a);break;case "protocol":f=g;break;case "host":f=(a.hostname||B.location.hostname).split(":")[0].toLowerCase();if(d){var h=
/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:B.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Ua(c||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=dh(f,e));break;case "fragment":f=a.hash.replace("#","");break;case "extension":var l=a.pathname.split(".");f=1<l.length?l[l.length-1]:"";f=f.split("/")[0];
break;default:f=a&&a.href}return f},Sa=function(a){var b="";if(a&&a.href){var d=a.href.indexOf("#");b=0>d?a.href:a.href.substr(0,d)}return b},Ra=function(a){var b=M.createElement("a");a&&(b.href=a);return b};var Da=function(a,b){var d=function(){};d.prototype=a.prototype;var c=new d;a.apply(c,Array.prototype.slice.call(arguments,1));return c};var ac=function(a){return encodeURIComponent(a)},ja=function(a,b){if(!a)return!1;var d=Z(Ra(a),"host");if(!d)return!1;for(var c=0;b&&c<b.length;c++){var e=b[c]&&b[c].toLowerCase();if(e){var f=d.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&d.indexOf(e,f)==f)return!0}}return!1};
var Q=function(a,b,d){for(var c={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(d)&&(c[a[f][b]]=a[f][d],e=!0);return e?c:null},Xa=function(a,b){Ya(a,b)},db=function(a){return r(a)},lc=function(a,b){return Ua(a,b)},Kb=function(){return!1};var Cb=function(a){if(!eh[a]){eh[a]=!0;B[a]||(B[a]={});var b=function(a){return nb[a]},d=B[a].get;B[a].get=d?function(a){return void 0!==nb[a]?nb[a]:d(a)}:b}},pb=function(a,b,d){try{a(d,b)}catch(c){}},ob=function(a){fh[a]=fh[a]||[];return fh[a]},nb={},fh={},eh={};var gh=new Gg,hh={},kh={set:function(a,b){Ya(ih(a,b),hh)},get:function(a){return jh(a,2)},reset:function(){gh=new Gg;hh={}}},jh=function(a,b){return 2!=b?gh.get(a):lh(a)},lh=function(a){for(var b=a.split("."),d=0,c=hh.eventModel;void 0!==c&&d<b.length;d++){if(null===c)return!1;c=c[b[d]]}if(void 0!==c||1<d)return c;var e=hh;for(d=0;d<b.length;d++){if(null===e)return!1;if(void 0===e[b[d]])return;e=e[b[d]]}return e},Ea=function(a,b){gh.set(a,b);Ya(ih(a,b),hh)},ih=function(a,b){for(var d={},c=d,e=a.split("."),
f=0;f<e.length-1;f++)c=c[e[f]]={};c[e[e.length-1]]=b;return d};var mh=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),nh={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},oh={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},ph=function(a,b){for(var d=[],c=0;c<a.length;c++)d.push(a[c]),d.push.apply(d,b[a[c]]||[]);return d},qh=function(a){var b=jh("gtm.whitelist");
var d=b&&ph(Fg(b),nh),c=jh("gtm.blacklist")||jh("tagTypeBlacklist")||[];jb()&&(c=Fg(c),c.push("nonGooglePixels","nonGoogleScripts"));var e=c&&ph(Fg(c),oh),f={};return function(g){var h=g&&g[Db];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Ua(d,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>Ua(d,h.b[m])){l=!1;
break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(c){var p;if(!(p=0<=Ua(e,h.a)))a:{for(var q=h.b||[],u=new Gg,t=0;t<e.length;t++)u.set(e[t],!0);for(t=0;t<q.length;t++)if(u.get(q[t])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}},jb=function(){return mh.test(B.location&&B.location.hostname)};var rh;
var sh=function(a){if(!a||a.nodeType!=Node.ELEMENT_NODE)return!1;var b=a.tagName.toUpperCase();return"SCRIPT"==b||"STYLE"==b||"LINK"==b},th=function(a,b,d){null==d?a.removeAttribute(b):a.setAttribute(b,d)},vb=function(a,b,d){var c=a.getAttribute(b);th(a,b,d);return function(){th(a,b,c)}},xb=function(a,b,d){var c,e,f=a.ownerDocument||a.document||document;d=(d||"").toLowerCase();"after"==d?(c=a.parentNode,e=a.nextSibling):"insert"==d?(c=a,e=a.firstChild):"append"==d?(c=a,e=null):(c=a.parentNode,e=a);
if(!c||c==f)return{result:1,Dd:[]};var g=uh(b,c);vh(g,"SCRIPT");vh(g,"NOSCRIPT");var h=[];if(g.firstChild)for(var k=g.firstChild;k;){var l=k.nextSibling;h.push(k);c.insertBefore(k,e);k=l}var m=a.nextSibling;"replace"==d&&c.removeChild(a);return{result:function(){for(;0<h.length;)c.removeChild(h.pop());"replace"==d&&c.insertBefore(a,m)},Dd:h.slice()}},wh={SELECT:[1,'<select multiple="multiple">',"</select>"],FIELDSET:[1,"<fieldset>","</fieldset>"],MAP:[1,"<map>","</map>"],OBJECT:[1,"<object>","</object>"],
TABLE:[1,"<table>","</table>"],TBODY:[2,"<table><tbody>","</tbody></table>"],COLGROUP:[2,"<table><colgroup>","</colgroup></table>"],TR:[3,"<table><tbody><tr>","</tr></tbody></table>"]},uh=function(a,b){var d=0,c="",e="",f=wh[b.tagName];null!=f&&(d=f[0],c=f[1],e=f[2]);var g=document.createElement("div");g.innerHTML=c+(a||"")+e;for(var h=g;0<d;){var k=h.firstChild;if(!(k instanceof Element))return document.createElement("div");h=k;d--}return h},vh=function(a,b){for(var d=a.getElementsByTagName(b),c=
[],e=d.length-1;0<=e;e--){var f=d[e];f.parentNode.removeChild(f);c.push(f)}},Ub=function(a){var b=null,d=null;try{b=new Function("element",a)}catch(c){d=c}return{N:b,error:d}},Vb=function(a,b){try{var d=b(a);return"function"==typeof d?d:null}catch(c){return c}},Xb=function(a,b,d,c,e){var f=a+"{"+(b+": "+d+(c?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=xh(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",
k)}}var l=yh(f,g);zh(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},Ah=null,xh=function(a){if(Ah)return Ah;for(var b=a.styleSheets.length-1;0<=b;b--){var d=a.styleSheets[b],c=d.ownerNode;if(c&&c.parentNode&&"HEAD"==c.parentNode.tagName)return Ah=d}0==a.styleSheets.length&&a.createStyleSheet();return rh=a.styleSheets[0]},yh=function(a,b){var d=(b||document).createElement("style");void 0!==d.cssText?d.cssText=a:d.innerHTML=a;return d},zh=function(a,b){var d=b||document,c=d.getElementsByTagName("head")[0];
c||(c=d.createElement("head"),d.body.parentNode.insertBefore(c,d.body));c.appendChild(a)},Yb=function(a,b,d,c){if(a.style.setProperty)try{var e=a.style.getPropertyValue(b),f=a.style.getPropertyPriority(b);a.style.setProperty(b,d,c?"important":"");return function(){a.style.setProperty(b,"",f);a.style.setProperty(b,e,f)}}catch(h){}var g=a.style.cssText;a.style.cssText+=";"+(b+": "+d+(c?" !important":""))+";";return function(){a.style.cssText=g}},yb=function(a,b,d,c){if(sh(a))return 7;if(b)return Bh(a,
b,c);if(d&&d.parentNode){var e=a.parentNode,f=a.nextSibling;d.parentNode.insertBefore(a,d.nextSibling);return function(){e.insertBefore(a,f)}}return 4},Bh=function(a,b,d){var c=a.parentNode,e=a.nextSibling;d=(d||"").toLowerCase();if("bottom"==d)b.appendChild(a);else if("top"==d)b.insertBefore(a,b.childNodes[0]||null);else if("before"==d)if(b.parentNode)b.parentNode.insertBefore(a,b);else return 5;else if("after"==d)if(b.parentNode)b.parentNode.insertBefore(a,b.nextSibling);else return 5;return function(){c.insertBefore(a,
e)}},kc=function(a,b,d,c){if(sh(a))return 7;d=(d||"").toLowerCase();var e;if("replace"==d)e=Ch(a,b,c);else{var f=a,g,h=null,k=null;g=(d||"").toLowerCase();"before"==g?(k=f,f=f.parentNode):"after"==g?(h=f,f=f.parentNode):0<f.childNodes.length&&(0>b?k=f.childNodes[0]:b>=f.childNodes.length?h=f.childNodes[f.childNodes.length-1]:"insert"==g?k=f.childNodes[b]:"append"==g&&(h=f.childNodes[b]));e=f?Dh(c,f,h,k):1}return e},Ch=function(a,b,d){if(0<=b&&b<a.childNodes.length){var c=a.childNodes[b];if(null!=
c&&c.nodeType==Node.TEXT_NODE){var e=c.nodeValue;c.nodeValue=d;return function(){c.nodeValue=e}}return 2}return 3},Dh=function(a,b,d,c){d?c=d.nextSibling:c&&(d=c.previousSibling);if(null!=d&&d.nodeType==Node.TEXT_NODE){var e=d.nodeValue;d.nodeValue+=a;return function(){d.nodeValue=e}}if(null!=c&&c.nodeType==Node.TEXT_NODE){var f=c.nodeValue;c.nodeValue=a+c.nodeValue;return function(){c.nodeValue=f}}var g=(b.ownerDocument||b.document||document).createTextNode(a);c?b.insertBefore(g,c):b.appendChild(g);
return function(){b.removeChild(g)}},Tb=function(a){var b=document.createElement("a");a&&(b.href=a);return b};var Eh=/(^|\.)doubleclick\.net$/i,Fh=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,ca=function(a,b,d){for(var c=String(b||M.cookie).split(";"),e=[],f=0;f<c.length;f++){var g=c[f].split("="),h=Qa(g[0]);if(h&&h==a){var k=Qa(g.slice(1).join("="));k&&!1!==d&&(k=decodeURIComponent(k));e.push(k)}}return e},Hh=function(a,b,d,c,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";d&&(g+="path="+d+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==c?Gh():[c||"none"];for(var k=0;k<h.length;k++){var l=
g,m=h[k],n=d;if(Eh.test(B.location.hostname)||"/"==n&&Fh.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=M.cookie;M.cookie=l;if(p!=M.cookie||0<=Ua(ca(a),b))return!0}return!1},Ih=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Jh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Gh=function(){var a=Z(B.location,"host",!0).split(".");
if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],d=a.length-2;0<=d;d--)b.push(a.slice(d).join("."));b.push("none");return b};var Kh=function(a,b){this.j=a;this.w=b};Kh.prototype.toString=function(){var a=""+this.j;1<this.w&&(a=a+"-"+this.w);return a};var Lh=function(a,b){this.vb=a;this.Pa=b};Lh.prototype.toString=function(){return""+this.Pa+"."+this.vb};
var oa=function(a,b){var d=new Mh(null,a,b);d.Kd();return d},Mh=function(a,b,d){this.Rb=Math.floor((new Date).getTime()/864E5);this.Na=b||"auto";this.xa=d||"/";var c=Ih(this.Na),e=Jh(this.xa);this.P=a||new Kh(c,e);this.m=[];this.O=new Gg};aa=Mh.prototype;aa.Yb=function(a){if(!a)return"";var b=this.Zb(a);return b?b.vb:""};aa.oc=function(a,b,d,c,e){var f,g;f=void 0===f?10:f;g=void 0===g?3E3:g;if(!a)return!1;void 0==b&&(b="");this.Ua(a,new Lh(b,d));this.Qc(e);return this.Xd(c,f,g)};aa.Zb=function(a){return this.O.get(a)};
aa.Ua=function(a,b){a&&(""==b.vb?this.nc(a):(this.O.contains(a)||this.m.push(a),this.O.set(a,b)))};aa.Zd=function(a){for(var b=0;b<a.length;b++)this.Ua(a[b][0],a[b][1])};aa.nc=function(a){var b=Ua(this.m,a);0<=b&&this.m.splice(b,1);this.O.set(a,void 0)};aa.Rd=function(){for(var a=[],b=0;b<this.m.length;b++){var d=this.m[b];this.O.get(d).Pa<this.Rb&&a.push(d)}for(b=0;b<a.length;b++)this.nc(a[b])};aa.rd=function(){for(var a=[],b=0;b<this.m.length;b++){var d=this.m[b];a.push([d,this.O.get(d)])}return a};
aa.od=function(){for(var a=0,b=0;b<this.m.length;b++)a=Math.max(a,this.O.get(this.m[b]).Pa);return 864E5*a};aa.toString=function(){if(0==this.m.length)return"";for(var a=[],b=0;b<this.m.length;b++){var d=this.m[b];a.push(""+d+"."+this.O.get(d).toString())}return"GAX1."+this.P.toString()+"."+a.join("!")};aa.Xd=function(a,b,d){var c=new Date,e=Jh(this.xa);this.Rd();if(this.m.length>b||this.m.length>(a||10)&&M.cookie.replace(/(?:;\s*)?(_gaexp=[^;]+)(?:;\s*)?/,this.toString()).length>d)return!1;c.setTime(this.od());
if("auto"!=this.Na)return Hh("_gaexp",this.toString(),this.xa,this.Na,c);for(var f=Gh(),g=0;g<f.length;g++)if("none"!=f[g]&&(this.P=new Kh(Ih(f[g]),e),Hh("_gaexp",this.toString(),this.xa,f[g],c)))return!0;return!1};aa.Kd=function(){for(var a=this.P.j,b=this.P.w,d=ca("_gaexp"),c=[],e=0;e<d.length;e++){var f=this.Ld(d[e]);f&&c.push(f)}Qg(c,function(c,d){var e=c.P,f=d.P;return e.j==f.j&&e.w==f.w?!1:e.j==a&&e.w==b?!0:f.j==a&&f.w==b?!1:e.j==a?f.j!=a||e.w<f.w:f.j==a?!1:e.w==b?f.j!=a&&(f.w!=b||e.j<f.j):
f.w==b?!1:e.j<f.j||e.j==f.j&&e.w<f.w});this.P=0<c.length?c[0].P:new Kh(a,b);for(var g=c.length-1;0<=g;g--)this.Zd(c[g].rd())};aa.Ld=function(a){var b=a.match(/GAX1\.([^.]+).(.*)/);if(b){var d;a:{var c=(b[1]||"").split("-");if(!(0==c.length||2<c.length)){var e=Qa(c[0]);if(0!=e.length){var f=2==c.length?Qa(c[1]):"1";if(Dg(e)&&Dg(f)){d=new Kh(r(e),r(f));break a}}}d=void 0}var g=d;if(g){for(var h=new Mh(g,this.Na,this.xa),k=(b[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Dg(m[1]))return;
h.Ua(m[0],new Lh(m[2],r(m[1])))}}return h}}};aa.Qc=function(a){a=a||{};var b=0;a.hasOwnProperty("")&&Dg(a[""])&&(b=this.Rb-r(a[""]));for(var d=0;d<this.m.length;d++){var c=this.m[d];if(a.hasOwnProperty(c)&&Dg(a[c])){var e=this.Zb(c);e.Pa=r(a[c])+b;this.Ua(c,e)}}};var ka=function(a){var b=M;return qb?b.querySelectorAll(a):null},Nh=!1;if(M.querySelectorAll)try{var Oh=M.querySelectorAll(":root");Oh&&1==Oh.length&&Oh[0]==M.documentElement&&(Nh=!0)}catch(a){}var qb=Nh;
var ib={},Ph={},rb=void 0,lb=function(a){var b=Ph[a];b||(b={id:a,D:[],ua:0,Bb:null,mb:void 0,sb:!1},Ph[a]=b);rb=b},kb=function(a,b){ib[b]=a;var d=Ph[a];if(!d)return!1;for(var c=d.ua=0;c<d.D.length;c++)d.D[c].finished=!1;Qh(d);return!0},mb=function(a){var b=Ph[a];if(!b||b.sb)return!1;for(;b.D.length;)for(var d=b.D.pop();d.la.length;){var c=d.la.pop();if(T(c))try{c()}catch(e){}}b.sb=!0;delete Ph[a];return!0},ub=function(a,b,d,c){var e=rb;if(!qb||!e)return!1;var f={id:e.id+":"+e.D.length,Rc:b,la:[],
Kc:d,R:a,$a:0,Va:c||null,Qb:0,finished:!1};e.D.push(f);null===a?(f.finished=!0,b(null)):Qh(e);return!0},sb=function(a){var b=Xb(a,"visibility","hidden",!0);return function(){T(b)&&b.apply();b=null}},wb=function(a,b,d,c){var e=b;if(!Tg){var f=sb(a.h);Ug.push(f);e=function(a,c){var d=b(a,c);f();return d}}return ub(a,e,d,c)},Qh=function(a){if(!a.sb){for(var b=a.ua;b<a.D.length;b++){var d=a.D[b],c=b==a.ua;if(!d.finished&&!Rh(c,d))break;d.finished&&c&&a.ua++}a.D.length>a.ua?(a.Bb||(a.Bb=B.setTimeout(function(){a.Bb=
null;Qh(a)},80)),Tg||a.mb||(a.mb=function(){y(function(){Qh(a)})},Ba(M,"DOMContentLoaded",a.mb))):Sh(a)}},Sh=function(a){for(var b=0;b<a.D.length;b++){var d=a.D[b];if(d.R)for(var c=ka(d.R.h)||[],e=0;e<c.length;e++){var f=c[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[d.id]||(Th(f,d.id),d.la.push(Uh(f,d.id)))}}},Rh=function(a,b){var d=[];if(b.R){var c=Vh(b.R,b.id),e=null;b.Va&&(e=Vh(b.Va,b.id+"-t"));for(var f=0;f<c.length;f++){var g=c[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!Tg&&(null===
b.Va.g||b.Qb+d.length<b.Va.g)))break;d.push({element:g,ae:h})}}if(!Tg&&b.Kc&&(!a||null==b.R.g||b.R.g!=b.$a+d.length))return!1;for(var k=0;k<d.length;k++){var l=d[k].element,m=d[k].ae,n;b.$a++;Th(l,b.id);m&&(b.Qb++,n=b.id+"-t",Th(m,n));var p=b.Rc(l,m);T(p)&&b.la.push(p);b.la.push(Uh(l,b.id));m&&n&&b.la.push(Uh(m,n))}if(b.R.g&&b.R.g==b.$a||Tg)b.finished=!0;return!0},Th=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Uh=function(a,b){return function(){a.gtmProgressiveApplied&&
delete a.gtmProgressiveApplied[b]}},Vh=function(a,b){for(var d=ka(a.h)||[],c=[],e=0;e<d.length;e++){var f=d[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.o&&!Wh(f))break;c.push(f)}}return c},Wh=function(a){if(Tg)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Y={};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Yh={event:function(a){var b=a[1];if(sa(b)&&!(3<a.length)){var d;if(2<a.length){if(!Na(a[2]))return;d=a[2]}var c=d,e={event:b};c&&(c=Ya(c,void 0),e.eventModel=c,e.eventCallback=c.eventCallback);return e}},set:function(a){var b;2==a.length&&Na(a[1])?b=Ya(a[1],void 0):3==a.length&&sa(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var Zh=!1,ea=!1;var $a=function(a){var b=B;b.GoogleAnalyticsObject||(b.GoogleAnalyticsObject=a||"ga");var d=b.GoogleAnalyticsObject;if(!b[d]){var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(Pb());b[d]=c}return b[d]},eb=function(){var a=B;return a.GoogleAnalyticsObject&&a[a.GoogleAnalyticsObject]},fb=function(a,b,d,c){b=String(b).replace(/\s+/g,"").split(",");var e=eb();e(a+"require","linker");e(a+"linker:autoLink",b,d,c)};var $h=Math.random(),ai="0.050000">$h;
var bi=function(a,b){if(ai){var d=Ac,c=function(a,b){b&&(d+=a+encodeURIComponent(b))};c("&v=","t");c("&n=",a);c("&s=",b&&b.state);c("&h=",b&&b.hideLatency);c("&g=",b&&b.gaLatency);c("&p=",b&&b.loadBy);c("&o=",b&&b.timeout);c("&l=",Pb().getTime()-r(zc));d+="&sr=0.050000";c("&ps=",$h);c("&cb=",Va());C(d)}},ci=Bg,di=function(){var a=!1;
a||(ci=function(){var a,d,c,e,f,g=Pb().getTime(),h;a:{var k=w(w("GoogleAnalyticsObject")||"ga"),l="";""==l&&(l="t0");var m=k&&k.getByName&&k.getByName(l),n=m&&m.get("&gtm")?"gtm":"ga",p,q=Pb().getTime(),u;for(u in k)if(k.hasOwnProperty(u)){var t=k[u];"l"!=u&&"answer"!=u&&"number"==typeof t&&1E5>q-t&&0<q-t&&(p=t)}h={Fd:n,Xb:p};break a;h=void 0}h&&(e=
h.Fd,h.Xb&&(c=g-h.Xb));var v=B["dataLayer"].hide;if(v){if(void 0===v[Wa.f])a="h2";else{var F=!!M.querySelector("body");a=null!==v.end||!0!==v[Wa.f]?"h1":F?"h0":"h3"}v.start&&!isNaN(v.start)&&(d=g-v.start);isNaN(v.timeout)||(f=v.timeout)}bi("ga",{state:a,hideLatency:d,gaLatency:c,loadBy:e,timeout:f})});};var fi=function(a){var b=ec.zones;return b?b.checkState(Wa.f,a):ei},bc=function(a){var b=ec.zones;!b&&a&&(b=ec.zones=a());return b},ei={active:!0,isWhitelisted:function(){return!0}};var gi=Bg,hi=[],ii=!1,ji=function(a){return B["dataLayer"].push(a)},ki=function(a){var b=!1;return function(){!b&&T(a)&&y(Kg(a));b=!0}},si=function(){for(var a=!1;!ii&&0<hi.length;){ii=!0;delete hh.eventModel;var b=hi.shift();if(T(b))try{b.call(kh)}catch(P){}else if(Ma(b))a:{var d=b;if(sa(d[0])){for(var c=d[0].split("."),e=c.pop(),f=d.slice(1),g=hh,h=0;h<c.length;h++){if(void 0===g[c[h]])break a;g=g[c[h]]}try{g[e].apply(g,f)}catch(P){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&sa(l[0])){var m=Yh[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){ii=!1;continue}}var n=void 0,p=void 0,q=b,u=q._clear;for(p in q)q.hasOwnProperty(p)&&"_clear"!==p&&(u&&Ea(p,void 0),Ea(p,q[p]));var t=!1,v=q.event;if(v){q.hasOwnProperty("gtm.uniqueEventId")||(q["gtm.uniqueEventId"]=Mg(),Ea("gtm.uniqueEventId",q["gtm.uniqueEventId"]));n=q["gtm.uniqueEventId"];Ha=v;var F=fi(n);if(F.active){var D=ki(q.eventCallback),E=q.eventTimeout;
E&&B.setTimeout(D,Number(E));t=gi(n,v,F.isWhitelisted,D,q.eventReporter)}}zc||(zc=q["gtm.start"])&&ci();var J,K=q,G=n,z=v,H=hh;Ha=null;a=t||a}ii=!1}return!a},ti=function(){var a=si();try{var b=B["dataLayer"].hide;if(b&&void 0!==b[Wa.f]&&b.end){b[Wa.f]=!1;var d=!0,c;for(c in b)if(b.hasOwnProperty(c)&&!0===b[c]){d=!1;break}d&&(b.end(),b.end=null)}}catch(e){}return a},ui=function(){var a=Ob("dataLayer",[]),b=Ob("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};Ug.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});ah.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var d=a.push;a.push=function(){var b=[].slice.call(arguments,0);d.apply(a,b);for(hi.push.apply(hi,b);300<this.length;)this.shift();return si()};hi.push.apply(hi,a.slice(0));y(ti)};var vi,wi,xi;
var Gi=function(a,b,d,c){var e={event:d||"","gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||Oa(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};c&&(e["gtm.triggers"]=c.join(","));if(b&&zi)if("LINK_CLICK"==b)e["gtm.elementUrl"]=a.href;else if("FORM_SUBMIT"==b){var f=a.action;f&&f.tagName&&(f=a.cloneNode(!1).action);e["gtm.elementUrl"]=f}e.hasOwnProperty("gtm.elementUrl")||(e["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||
a.src||a.code||a.codebase||"");return e},Pi=function(a){ec.hasOwnProperty("autoEventsSettings")||(ec.autoEventsSettings={});var b=ec.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},wa=function(a,b,d){Pi(a)[b]=d},Nb=function(a,b,d,c){var e=Pi(a),f=bb(e,b,c);e[b]=d(f)},Ca=function(a,b,d){var c=Pi(a);return bb(c,b,d)},xa=function(a){return!!Ca(a,"init",!1)},Aa=function(a){wa(a,"init",!0)},Qi=function(){};var Ri=/^~?[\w-]+$/,Ti=function(a){for(var b=[],d=String(M.cookie||document.cookie).split(";"),c=0;c<d.length;c++){var e=d[c].split("="),f=e[0].replace(/^\s*|\s*$/g,"");if(f&&f==a){var g=e.slice(1).join("=").replace(/^\s*|\s*$/g,"");b.push(g)}}var h=[];if(!b||0==b.length)return h;for(var k=0;k<b.length;k++){var l=b[k].split(".");3==l.length&&"GCL"==l[0]&&l[1]&&h.push(l[2])}return Si(h)},Si=function(a){return a.filter(function(a){return Ri.test(a)})};var Ui=/^\w+$/,Vi=/^[\w-]+$/,Wi=/^\d+\.fls\.doubleclick\.net$/;function Xi(a){return a&&"string"==typeof a&&a.match(Ui)?a:"_gcl"}function Yi(a){if(a){if("string"==typeof a){var b=Xi(a);return{dc:b,aw:b,gf:b}}if(a&&"object"==typeof a)return{dc:Xi(a.dc),aw:Xi(a.aw),gf:Xi(a.gf)}}return{dc:"_gcl",aw:"_gcl",gf:"_gcl"}}function Zi(a){var b=Ra(B.location.href),d=Z(b,"host",!1);if(d&&d.match(Wi)){var c=Z(b,"path").split(a+"=");if(1<c.length)return c[1].split(";")[0].split("?")[0]}}
function $i(a){return a.filter(function(a){return Vi.test(a)})}var bj=function(a){var b=Zi("gclaw");if(b)return b.split(".");var d=Yi(a);if("_gcl"==d.aw){var c=aj();if(c&&(null==c.H||"aw.ds"==c.H))return[c.fa]}return $i(Ti(d.aw+"_aw"))},cj=function(a){var b=Zi("gcldc");if(b)return b.split(".");var d=Yi(a);if("_gcl"==d.dc){var c=aj();if(c&&("ds"==c.H||"aw.ds"==c.H))return[c.fa]}return $i(Ti(d.dc+"_dc"))};
function aj(){var a=Ra(B.location.href),b=Z(a,"query",!1,void 0,"gclid"),d=Z(a,"query",!1,void 0,"gclsrc");if(!b||!d){var c=Z(a,"fragment");b=b||dh(c,"gclid");d=d||dh(c,"gclsrc")}return void 0!==b&&b.match(Vi)?{fa:b,H:d}:null}
var dj=function(){var a=Zi("gac");if(a)return decodeURIComponent(a);for(var b=[],d=M.cookie.split(";"),c=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<d.length;e++){var f=d[e].match(c);f&&b.push({Ab:f[1],value:f[2]})}var g={};if(b&&b.length)for(var h=0;h<b.length;h++){var k=b[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[b[h].Ab]||(g[b[h].Ab]=[]),g[b[h].Ab].push({timestamp:k[1],fa:k[2]}))}var l=[],m;for(m in g)if(g.hasOwnProperty(m)){for(var n=[],p=g[m],q=0;q<p.length;q++)n.push(p[q].fa);n=$i(n);
n.length&&l.push(m+":"+n.join(","))}return l.join(";")};var fj={"":"n",UA:"u",AW:"a",DC:"d",GTM:ej()};function ej(){if(3===Wa.Ia.length)return"g";return"G"}function gj(){return"z";return"w"}var Ga=function(a){var b=Wa.f.split("-"),d=b[0].toUpperCase(),c=fj[d]||"i",e=a&&"GTM"===d?b[1]:"";return(3===Wa.Ia.length?"2"+gj():"")+c+Wa.Ia+e};var Wb=new String("undefined"),lj=function(a){this.resolve=function(b){for(var d=[],c=0;c<a.length;c++)d.push(a[c]===Wb?b:a[c]);return d.join("")}};lj.prototype.toString=function(){return this.resolve("undefined")};lj.prototype.valueOf=lj.prototype.toString;var mj={},nj=function(a,b){var d=Mg();mj[d]=[a,b];return d},oj=function(a){var b=a?0:1;return function(a){var c=mj[a];if(c&&T(c[b]))c[b]();mj[a]=void 0}};var pj={},qj,rj;
var Aj=function(){var a=ec.Ad;a&&a.qc&&a.qc("opt");};var Bj=!!B.MutationObserver,pc=void 0,zb=function(a){if(!pc){var b=function(){var a=M.body;if(a)if(Bj)(new MutationObserver(function(){for(var a=0;a<pc.length;a++)y(pc[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;Ba(a,"DOMNodeInserted",function(){b||(b=!0,y(function(){b=!1;for(var a=0;a<pc.length;a++)y(pc[a])}))})}};pc=[];M.body?b():y(b)}pc.push(a)};var Fb=function(a,b,d,c){Ba(a,b,d,c)},pa=function(a,b){return B.setTimeout(a,b)},ha=function(a,b,d){x(a,b,d)},ba=function(){return new Date},ia=function(){return B.location.href},Gb=function(a){return Z(Ra(a),"fragment")},S=function(a,b){return jh(a,b||2)},ta=function(a,b,d){b&&(a.eventCallback=b,d&&(a.eventTimeout=d));return ji(a)},fa=function(a,b){B[a]=b},w=function(a,b,d){var c=B;b&&(void 0===c[a]||d&&!c[a])&&(c[a]=b);return c[a]},da=function(a,b,d,c){return Hh(a,b,"/","auto",d,c)},Ka=function(a,
b,d){var c=b,e=d,f=Yi(a);e=e||"auto";c=c||"/";var g=aj();if(null!==g){var h=(new Date).getTime(),k=new Date(h+7776E6),l=["GCL",Math.round(h/1E3),g.fa].join(".");g.H&&"aw.ds"!=g.H||Hh(f.aw+"_aw",l,c,e,k,!0);"aw.ds"!=g.H&&"ds"!=g.H||Hh(f.dc+"_dc",l,c,e,k,!0);"gf"==g.H&&Hh(f.gf+"_gf",l,c,e,k,!0)}},Ja=function(){throw Error("Not supported in V1");},Ia=function(){throw Error("Not supported in V1");},La=function(){throw Error("Not supported in V1");},Lb=function(a,b,d){return Zg(a,b,d)},A=function(a,b,
d,c){var e=!c&&"http:"==B.location.protocol;e&&(e=2!==$b());return(e?b:a)+d},tb=function(a){Tg?a():Ug.push(a)};
var ma=function(a){var b=0;return b},nc=function(a){},na=function(a){var b=!1;return b},Mb=function(a,b){return Eg(a,
b)},Ta=function(a,b,d){return Gi(a,void 0,b,d)},va=function(a,b,d,c){Nb(a,b,d,c)},za=function(a,b,d){return Ca(a,b,d)};var $b=function(){for(var a=1,b=M.getElementsByTagName("script"),d=0;d<b.length&&100>d;d++){var c=b[d].src;if(c){c=c.toLowerCase();if(Pg(c,"http://www.google-analytics.com/gtm.js"))return 3;1===a&&Pg(c,"https://www.google-analytics.com/gtm.js")&&(a=2)}}return a};var mc=function(){return eb()};
var dc=function(a,b,d){var c;c=((void 0===d?0:d)?"www.google-analytics.com/gtag/js":"www.google-analytics.com/gtm.js")+("?id="+encodeURIComponent(a)+"&l=dataLayer");if(b)for(var e in b)b[e]&&b.hasOwnProperty(e)&&(c+="&"+e+"="+encodeURIComponent(b[e]));x(A("https://","http://",c),void 0,void 0)};var hc=function(a,b,d){a instanceof lj&&(a=a.resolve(nj(b,d)),b=Bg);return{jb:a,B:b}};var _sel=function(a){return ka(a[Bf])};_sel.a="sel";_sel.b=["customScripts"];var _eu=function(a){var b=String(jh("gtm.elementUrl")||a[Nd]||""),d=Ra(b);return b};_eu.a="eu";_eu.b=["google"];var _gaoo_c=function(a){if(a[wg])return!0;var b=window._gaUserPrefs;if(b&&b.ioo&&b.ioo())return!0;try{var d=window.external;if(d&&"oo"==d._gaUserPrefs)return!0}catch(c){}return!!window["ga-disable-"+a[Ec]]};_gaoo_c.a="gaoo_c";_gaoo_c.b=["google"];var _f=function(a){var b=String(jh("gtm.referrer")||M.referrer);if(!b)return b;var d=Ra(b);return b};_f.a="f";_f.b=["google"];var _uv=function(){};_uv.a="uv";_uv.b=["google"];var Qj=function(a){var b=B.location,d;(d=a[Cd]?a[Cd]:jh("gtm.url"))&&(b=Ra(String(d)));var c=b.href,e=c.indexOf("#"),f=0>e?c:c.substr(0,e);return f},_u=Qj;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Oc])==String(a[Pc])};_eq.a="eq";_eq.b=["google"];var Vj=function(a){var b=Ra(a),d=Z(b,"protocol"),c=Z(b,"host",!0),e=Z(b,"port"),f=Z(b,"path").toLowerCase().replace(/\/$/,"");if(void 0===d||"http"==d&&"80"==e||"https"==d&&"443"==e)d="web",e="default";return[d,c,e,f]},_um=function(a){for(var b=Vj(a[Oc]),d=Vj(a[Pc]),c=0;c<b.length;c++)if(b[c]!==d[c])return!1;return!0};_um.a="um";_um.b=["google"];var _exsu=function(a,b,d){oa(a[pd],a[sd]).oc(a[ie],a[Ze],a[ke],a[Re],a[le])?b():d()};_exsu.a="exsu";_exsu.b=["google"];var Tk=function(a){if(!a)return!1;if(a[Nc]&&Ma(a[Pc])){for(var b=a[Pc],d=0;d<b.length;d++)if(a[Pc]=b[d],Hg(a))return!0;return!1}return Hg(a)};var Uk=98,Vk=[],Wk=[],mi=[],Xk=new Gg,Yk=[],Zk=[],Mi=[],Ni=[],$k=function(){this.X=[]};$k.prototype.set=function(a,b){this.X.push([a,b]);return this};$k.prototype.resolve=function(a,b){for(var d={},c=0;c<this.X.length;c++){var e=pi(this.X[c][0],a,b),f=pi(this.X[c][1],a,b);d[e]=f}return d};var al=function(a){this.index=a};al.prototype.resolve=function(a,b){var d=mi[this.index];if(d&&!b(d)){var c=d[Eb];if(a){if(a.get(c))return;a.set(c,!0)}d=pi(d,a,b);a&&a.set(c,!1);return Hg(d)}};
var _M=function(a){return new al(a)},bl=function(a){this.resolve=function(b,d){for(var c=[],e=!1,f=0;f<a.length;f++){var g=pi(Vk[a[f]],b,d);g===Wb&&(e=!0);c.push(g)}return e?new lj(c):c.join("")}},_T=function(a){return new bl(arguments)},cl=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(d,c){var e=pi(a[0],d,c);if(a[0]instanceof al&&b(8)&&b(16)){if(e===Wb)return e;var f=ab();Xk.set(f,e);return'google_tag_manager["'+Wa.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=yk[a[g]](e);return e}},_E=function(a,b){return new cl(arguments)},dl=function(a,b){this.C=a;this.Ba=b},_R=function(a,b){return new dl(a,b)};
var pi=function(a,b,d){var c=a;if(a instanceof al||a instanceof $k||a instanceof bl||a instanceof cl)return a.resolve(b,d);if(!(a instanceof dl))if(Ma(a)){c=[];for(var e=0;e<a.length;e++)c[e]=pi(a[e],b,d)}else if(a&&"object"==typeof a){c={};for(var f in a)a.hasOwnProperty(f)&&(c[f]=pi(a[f],b,d))}return c},gl=function(){for(var a=[_eq,__e,'_event','1',_M(0),__dee,'_dee_0',_M(1),'','8535772_4','optimize.callback','8535772_5',__asprv,'google_optimize',6,'_EXPERIMENT_ENABLED_8',true,'GTM-KFRPN4V_OPT-5JJ9H',_um,__u,'Page URL','URL',false,_M(3),'https://www.000webhost.com/','_IN_EXPERIMENT_7',__gthc,'_gthc_12','UA-10701068-4',_M(5),0,'8535772_13','__serverSideCookieCheckFor__GA_OPT_OUT_16',_gaoo_c,'_GA_OPT_OUT_16',_M(6),_M(7),'8535772_17',__ctto,'_ctto_18',_M(8),'8535772_19',_sel,'_CSS_SELECTOR_20',':root',_M(9),'null','8535772_21',__ua,_R(3,1),[49],'_gtn_15',_M(10),'TRACK_DATA','fieldName','value','cookieDomain','auto',{54:56,55:57},[58],'title','anonymizeIp','nonInteraction','adSenseId','language','encoding','screenColors','screenResolution','viewportSize','flashVersion','referrer','location',_uv,'_UNDEFINED_VALUE_1',_M(11),{60:8,61:3,62:16,63:74,64:74,65:74,66:74,67:74,68:74,69:74,70:74,71:74},22,'_EXPERIMENT_VARIATION_INDEX_10',_M(12),'8535772_23',_ol,_R(5,1),[81],[],27,_uae,_R(4,1),[86],'gP_3b1MCS6u9SNndYR4Gxw',_T(78),14,_exsu,18104,'_EXPERIMENT_EXPIRATION_DATES_2',_M(13),11,__dr,'Experiment_GTM-KFRPN4V_OPT-5JJ9H:0',24,__c,true,true,false,'',0,{106:107,108:109},'',17924,'gP_3b1MCS6u9SNndYR4Gxw',18017],b=[],d=0;d<a.length;d++)b[d]=
fl(d,a);return b},fl=function(a,b){var d=b[a],c=d;if(d instanceof al||d instanceof cl||d instanceof bl||d instanceof dl)c=d;else if(Ma(d)){c=[];for(var e=0;e<d.length;e++)c[e]=fl(d[e],b)}else if("object"==typeof d){c=new $k;for(var f in d)d.hasOwnProperty(f)&&c.set(b[f],fl(d[f],b))}return c},il=function(a,b){for(var d=b?b.split(","):[],c=0;c<d.length;c++){var e=d[c]=d[c].split(":");0==a&&(e[1]=
Vk[e[1]]);if(1==a){var f=hl(e[0]);e=d[c]={};for(var g=0;g<f.length;g++){var h=Wk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=hl(e[g]);3==a&&(d[c]=Vk[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Vk[e[g][k]]}else e[g]=[];5==a&&(d[c]=e[0])}return d},hl=function(a){var b=[];if(!a)return b;for(var d=0,c=0;c<a.length&&d<Uk;d+=6,c++){var e=a&&a.charCodeAt(c)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(d);2&f&&b.push(d+1);4&f&&b.push(d+2);8&f&&b.push(d+3);16&f&&b.push(d+4);32&f&&b.push(d+5)}}return b},jl=function(a,b,d){a.push.apply(a,il(b,d))};var kl;
var oi=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var d={},c;for(c in a)if(a.hasOwnProperty(c)){var e=nl[c];e&&0==e.indexOf("vtp_")&&(d[e]=a[c])}d.__metadata=b;return d}return a},ql=function(a){},rl=function(a,b){},sl=function(a,b){},ri=function(a){};var tl,ul,vl;
var wl=function(){return"&tc="+Zk.filter(function(a){return a}).length},xl="0.005000">Math.random(),yl=function(){var a=0,b=0;return{Ed:function(){if(2>a)return!1;1E3<=Pb().getTime()-b&&(a=0);return 2<=a},Ud:function(){1E3<=Pb().getTime()-b&&(a=0);a++;b=Pb().getTime()}}},zl=function(){tl=[Ac,"&v=3&t=t","&pid="+Va(),"&rv="+Wa.Ia,"&r=1"].join("")},Al={},Bl="",Cl={},Dl={},El=null,Fl=1E3,Gl=function(){var a=ul;return void 0===a?"":[tl,Al[a]?"":"&es=1",Cl[a],wl(),Bl,"&z=0"].join("")},
Hl=function(){vl&&(B.clearTimeout(vl),vl=void 0);void 0===ul||Al[ul]&&!Bl||(Dl[ul]||El.Ed()||0>=Fl--?Dl[ul]=!0:(El.Ud(),C(Gl()),Al[ul]=!0,Bl=""))},Il=function(a,b,d){if(xl&&!Dl[a]&&b){a!==ul&&(Hl(),ul=a);var c=d+String(b[Db]?b[Db].a:"").replace(/_/g,"");Bl=Bl?Bl+"."+c:"&tr="+c;vl||(vl=B.setTimeout(Hl,500));2022<=Gl().length&&Hl()}};var Jl=function(a){var b=this;this.s=a;this.ta=this.rc=!1;this.wb=[];this.fb=[];this.B=function(){b.ta||Lg(b.wb);Og(b,1);if(Cc[a])for(var d=0;d<Cc[a].length;d++)Cc[a].shift().B()};this.G=function(){b.ta||Lg(b.fb);Og(b,2);if(Cc[a])for(var d=0;d<Cc[a].length;d++)Cc[a].shift().G()};this.K=Bg},Kl=function(a,b){a.wb.push(b)},Ll=function(a,b){a.fb.push(b)},Ml=function(a){this.S=[];this.xb=[];this.Tb={};this.fc=[];this.ha=0;this.ub={};this.zb={};this.yb={};this.event=a};Ml.prototype.addListener=function(a){this.fc.push(a)};
var Nl=function(a){0<a.ha||Lg(a.fc)},Ol=function(a,b,d,c,e,f){if(!d.ta){a.S[b]=d;void 0==c&&(c=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);c=Ma(c)?c.slice():["or",c];e=Ma(e)?e.slice():[e];f=Ma(f)?f.slice():[f];a.Tb[b]=c;a.ub[b]=0<e.length;a.zb[b]=0<f.length;a.ha++;var g=function(){0<a.ha&&!a.ub[b]&&!a.zb[b]&&a.ha--;Nl(a)};Kl(d,g);Ll(d,g)}},Tl=function(a){for(var b=[],d={},c=0;c<a.S.length;d={T:d.T},c++)if(d.T=a.S[c],d.T){var e=a.Tb[c],f=a.ub[c],g=a.zb[c];if(0!=e.length||f||g){if(0<e.length)for(var h=
Pl(e,d.T.K),k=0;k<e.length;k++)e[k]instanceof dl&&e[k].C!=c&&Ql(a,e[k].C,h);(f||g)&&Rl(a,c,function(a){return function(){0<a.T.I.ha&&a.T.I.ha--;Nl(a.T.I)}}(d))}else b.push(c)}for(c=0;c<b.length;c++)a.S[b[c]].K();for(c=0;c<a.xb.length;c++){var l=a.xb[c];Sl(l);0<l.length&&l[0].K()}},Ql=function(a,b,d){a.S[b]&&(Kl(a.S[b],function(){d(b,!0)}),Ll(a.S[b],function(){d(b,!1)}))},Pl=function(a,b){var d=!1;return function(c,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof dl&&a[g].C===c||a[g]===c){f=
g;break a}f=-1}d||0>f||("or"==a[0]?e?(d=!0,b()):(a.splice(f,1),1==a.length&&(d=!0)):e?(a.splice(f,1),1==a.length&&(d=!0,b())):d=!0)}},Rl=function(a,b,d){var c=[],e=!1,f=function(b){var d,g,h=Zk[b];if(a.event.i(h)){}else g=Ul(h,b,a.event.i,a);if(d=g){var k=Vl(b,!0);0<k.length&&f(k[0].C);c.push(d);var l=Vl(b,!1);0<l.length&&f(l[0].C)}else e=!0};f(b);if(e)Wl(b,a.event);else{for(var g=0;g<c.length;g++){var h=c[g],k=Vl(h.s,!0);
if(0<k.length){var l=c[g-1],m=Xl(h);Kl(l,m);0==k[0].Ba?Ll(l,m):Ll(l,d)}var n=Vl(h.s,!1);0<n.length&&(m=Xl(c[g+1]),Kl(h,m),0==n[0].Ba?Ll(h,m):Ll(h,d))}Kl(c[c.length-1],d);Ll(c[c.length-1],d);a.xb.push(c)}},Vl=function(a,b){var d=b?Ff:Wf,c=Zk[a],e=void 0===c[d]?[]:c[d];return Ma(e)?e:[e]},Xl=function(a){return function(){a.K()}},Sl=function(a){for(var b=[],d=0;d<a.length;d++){var c=a[d],e=c.s,f=Bc[e],g=f.firingOption;if(0!=g&&(1==g&&void 0!==c.I.yb[e]||2==g&&void 0!==f.state)&&(b.push(c),2==f.state&&
d!=a.length-1)){var h=Vl(a[d+1].s,!0);if(0<h.length&&1==h[0].Ba)for(++d;d<a.length;d++)b.push(a[d])}}var k=Yl(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],q=p[0],u=p[p.length-1],t,v=0;v<a.length;v++){var F=a[v];!m&&F.s==q&&0<v&&(m=a[v-1]);F.s==u&&v<a.length-1&&(n=a[v+1]);if(-1<Ua(p,F.s))if(t=a.splice(v,1)[0],F.s==u)break;else v--}if(t){var D=Number(l),E=m,J=n;if(E){var K=E;K.wb=[];K.fb=[]}if(E&&J){var G=Xl(J);Kl(E,G);var z=Vl(E.s,!1);0<z.length&&z[0].C!=D&&0==z[0].Ba&&
Ll(E,G);var H=Vl(J.s,!0);0<H.length&&H[0].C!=D&&0==H[0].Ba&&Ll(E,G)}}}},Yl=function(a){for(var b={},d=0;d<a.length;d++){var c=a[d],e=[],f=function(a){var b=Vl(a,!0);0<b.length&&f(b[0].C);e.push(a);var c=Vl(a,!1);0<c.length&&f(c[0].C)};f(c.s);b[c.s]=e}Zl(a,b);return b},Zl=function(a,b){for(var d=0;d<a.length;d++){var c=a[d].s,e;for(e in b)if(b.hasOwnProperty(e)&&e!=c&&-1<Ua(b[e],c)){delete b[c];break}}},Wl=function(a,b){if(!xl)return;var d=function(a){return Ma(a)?
a[0]:a},c=function(a){var e=Zk[a];if(e){var g=d(void 0===e[Ff]?[]:e[Ff]);g&&c(g.C);var h=b.i(Zk[a])?"3":"4";Il(b.id,Zk[a],h);var k=d(void 0===e[Wf]?[]:e[Wf]);k&&c(k.C)}};c(a);};var $l=function(a,b,d){return function(){var c=b.I?b.I.event:void 0;a[qe]=function(){c&&Il(c.id,a,"5");b.B()};a[re]=function(){c&&Il(c.id,a,"6");b.G()};var e=b.s,f=b.I&&b.I.yb[e],g=Bc[e]&&Bc[e].state,h=f?void 0!==f:b.rc||b.ta,k=Bc[e]&&Bc[e].firingOption,l=k&&2==k,m=k&&1==k;if(!h&&void 0===g||!h&&!l||!l&&!m){Og(b,0);a=pi(a,new Gg,d);var n=Bg;if(c){
Il(c.id,a,"1"),n=function(){Il(c.id,a,"7")};rl(c,e)}Hg(a,b.B,b.G,n)}else l&&0==g||m&&0==f?Cc[e].push(b):l&&1==g||m&&1==f?b.B():b.G()}},Ul=function(a,b,d,c){function e(a){return a.s===b}var f=function(){var a=c&&c.S;return a&&Eg(a,e)}()||new Jl(b);f.I=c;f.K=$l(a,f,d);return f};
var am=function(a,b,d,c,e){this.list=a;this.context=b;this.i=d;this.B=c;this.G=e};am.prototype.K=function(a){if(a>=this.list.length)this.B();else{var b=this.list[a].tag_reference.C,d=Zk[b];d[Qf]=this.context;d[Rf]=a;var c=this,e=Ul(d,b,this.i);Kl(e,function(){c.callback(a,!0)});Ll(e,function(){c.callback(a,!1)});e.K()}};am.prototype.callback=function(a,b){if(!b)switch(this.list[a].failed_behavior){case "FAILED_ABORT":this.G();return}this.K(a+1)};var bm=function(a,b,d){var c=a[Pf];if(c){var e=a[Eb]||
bm.a+Math.random(),f=S("gtm.uniqueEventId")||0,g=fi(f),h=qh(g.isWhitelisted);a:{for(var k=c,l=[],m=0;m<k.length;m++){var n=k[m];if(h(Zk[n.tag_reference.C]))switch(n.blacklisted_behavior){case "BLACKLISTED_DISABLE":c=[];break a;case "BLACKLISTED_IGNORE":continue;case "BLACKLISTED_ABORT":c=l;break a}else l.push(n)}c=l}(new am(c,e,h,b,d)).K(0)}else d()},_ol=bm;_ol.a="ol";_ol.b=["google"];var _uae=function(a,b){var d=Ob("gaData",{}),c=a[Ec],e=a[ie],f=a[je];if(c){d[c]=d[c]||{};var g=d[c];g.pending_experiments=g.pending_experiments||{};g.pending_experiments[e]=f;g.experiments=g.experiments||{};g.experiments[e]=f}var h=cb("true");c&&h||(d.expId=e,d.expVar=f);b()};_uae.a="uae";_uae.b=["google"];var gm=function(){var a=[];return function(b,d){if(void 0===a[b]){var c=Yk[b]&&pi(Yk[b],new Gg,d),e=c;c&&(e=Tk(c));a[b]=[e,c]}return a[b]}},hm=function(a,b){for(var d=b[0],c=0;c<d.length;c++)if(!a.ea(d[c],a.i)[0])return!1;var e=b[2];for(c=0;c<e.length;c++)if(a.ea(e[c],a.i)[0])return!1;return!0},im=!1;
gi=function(a,b,d,c,e){switch(b){case "gtm.js":if(im)return!1;im=!0;break;case "gtm.sync":if(jh("gtm.snippet")!=yc)return!1}for(var f={id:a,name:b,callback:c||Bg,sa:hl(),Sa:hl(),ea:gm(),i:qh(d)},g=[],h=0;h<Mi.length;h++)if(hm(f,Mi[h])){g[h]=!0;for(var k=f,l=Mi[h],m=l[1],n=0;n<m.length;n++)k.sa[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Sa[p[n]]=!0}else g[h]=!1;xl&&!Dl[a]&&ul!==a&&(Hl(),ul=a,Bl="",Cl[a]="&e="+(0===b.indexOf("gtm.")?encodeURIComponent(b):"*")+"&eid="+a,vl||(vl=B.setTimeout(Hl,500)));for(var U=[],L=0;L<Uk;L++)!f.sa[L]||
f.Sa[L]||f.i(Zk[L])||(U[L]=Zk[L]);f.ya=U;for(var R=new Ml(f),W=0;W<Uk;W++)if(f.sa[W]&&!f.Sa[W])if(f.i(Zk[W])){Wl(W,f)}else{var P=f.ya[W],ra=Ul(P,W,f.i,R);Ol(R,W,ra,P[Od],P[Ff],P[Wf]);if(P[Dc])break}R.addListener(f.callback);Tl(R);Nl(R);e&&T(e)&&e({passingRules:g,resolvedTags:f.ya});if("gtm.js"==b||"gtm.sync"==b)a:{
if(Zh||ea)break a;var qa=B.GoogleAnalyticsObject||"ga",Za=qa&&B[qa];T(Za)&&(Za("provide",Wa.f,Bg),Zh=!0);}var ed={cl:!0,evl:!0,fsl:!0,hl:!0,jel:!0,lcl:!0,sdl:!0,tl:!0,ytl:!0},Jb;for(Jb in f.ya)if(f.ya.hasOwnProperty(Jb)&&!ed[f.ya[Jb][Db].a.replace(/_/g,"")])return!0;return!1};var km=function(){};var lm=function(){};var jm={macro:function(a){if(Xk.contains(a))return Xk.get(a)}};jm.dataLayer=kh;jm.onHtmlSuccess=oj(!0);jm.onHtmlFailure=oj(!1);jm.callback=function(a){Sb.hasOwnProperty(a)&&T(Sb[a])&&Sb[a]();delete Sb[a]};
jm.Yc=function(){var a=B.google_tag_manager;a||(a=B.google_tag_manager={});ec=a;if(a[Wa.f]){var b=ec.zones;b&&b.unregisterChild(Wa.f)}else{a[Wa.f]=jm;Aj();Qi();Vk.push.apply(Vk,gl());jl(Wk,0,"9:0,9:1,11:2,26:3,1:4,9:5,11:6,2:7,2:10,9:12,36:13,21:14,11:15,6:17,2:16,9:18,9:19,11:20,28:21,30:22,1:23,2:24,11:25,9:26,11:27,43:28,1:29,2:30,11:32,0:28,9:33,11:34,25:35,1:36,9:38,11:39,1:40,9:42,11:43,18:44,1:45,2:46,9:48,12:16,20:50,16:16,39:16,11:51,42:52,40:53,35:59,9:72,11:73,37:75,31:22,32:22,33:22,29:16,41:16,21:76,11:77,17:30,9:80,20:82,22:83,23:8,24:30,21:84,9:85,20:87,5:88,4:89,21:90,9:91,15:16,14:89,8:92,11:93,7:94,21:95,9:96,38:88,34:89,27:16,44:97,21:98,9:99,45:100,9:99,45:101,9:99,45:102,9:99,45:103,9:99,45:104,9:99,45:105");jl(mi,1,"O,oB,AADAAAAAAAAAAAM,IAwD,AACQAAAAAAAAAAw,IAAgD,AAAAwAAAAAAAAAAD,AAAAgH,IAAAAw,AAAAAAO,AAAAAAAgAAAAAAAM,AAAAAAAAY,AACAAAAAAADAAAAw,AAAAAAAAAAAAgAAAD");jl(Yk,1,"RC,RE,AAIM,BAAAM,BAEAAI,BAEAAAB,BAAAAAw");jl(Zk,1,"I4,IAAACAAfn_,AAAAAAAAAA8D,AAAAgAAKAAA8B,AAAAAAAAAAAQeD,IAAAAAAEAAAAE8D");jl(Mi,2,"B:B::,C:B::,F:C:I:,F:E::,Q:::G,g:::G,AB:::G");jl(Ni,4,"9:,11:,31:,79:,:37.37,:41.41,:47.47");for(var d=0;d<Zk.length;d++){var c=Zk[d],e=1;c[bf]?e=2:
c[ng]&&(e=0);Bc[d]={firingOption:e,state:void 0};Cc[d]=[]}di();ui();var n=M,p=B;if("interactive"==n.readyState&&!n.createEventObject||"complete"==n.readyState)Vg();else{Ba(n,"DOMContentLoaded",Vg);Ba(n,"readystatechange",Vg);if(n.createEventObject&&n.documentElement.doScroll){var q=!0;try{q=!p.frameElement}catch(D){}q&&Xg()}Ba(p,"load",Vg)}"complete"===M.readyState?bh():Ba(B,"load",bh);a:{if(!xl)break a;zl();ul=void 0;Cl={};Al={};vl=void 0;Dl={};Bl="";El=yl();B.setInterval(zl,864E5);}lm();km();a:{}}};jm.Yc();var _vs="res_ts:1548707688734000,srv_cl:231182105,ds:live,cv:24";
})()
